### ISSUE TITLE
-K works, -k doesn't

### ISSUE THREAD

**Issue by donwildman** [ZerBea/hcxtools#110]
-K writes the outfile, but that's not the correct format, I can't use the raw PMKID file, I need the hashcat 16800 format.

Any ideas on how to fix this?

pcap file is from bettercap 2

**Comment by ZerBea** [comment]
Yes, please read this completeley:
https://github.com/ZerBea/hcxtools/issues/109
and that completely:
https://github.com/bettercap/bettercap/issues/592

the same applies to options -k and -K
to convert -z or -k you need an ESSID and a matching PMKID
please attach bettercap file, I'll take a look inside.

**Comment by donwildman** [comment]
Hi ZerBia, thanks for the reply.
I've tried -o, -z and -k... no difference.

Here's the output:
root@kali:~/Downloads/hcxtools-master# ./hcxpcaptool -o /media/root/NEW\ VOLUME/better.hccapx /media/root/NEW\ VOLUME/bettercap-wifi-handshakes.pcap 

reading from bettercap-wifi-handshakes.pcap
                                                
summary capture file:                           
---------------------
file name........................: bettercap-wifi-handshakes.pcap
file type........................: pcap 2.4
file hardware information........: unknown
file os information..............: unknown
file application information.....: unknown
network type.....................: DLT_IEEE802_11_RADIO (127)
endianness.......................: little endian
read errors......................: flawless
minimum time stamp...............: 19.08.2019 16:14:45 (GMT)
maximum time stamp...............: 20.08.2019 18:23:58 (GMT)
packets inside...................: 59
skipped packets (damaged)........: 0
packets with GPS data............: 0
packets with FCS.................: 59
EAPOL packets (total)............: 59
EAPOL packets (WPA2).............: 59
PMKIDs (total)...................: 11
PMKIDs (WPA2)....................: 59
PMKIDs from access points........: 11
best PMKIDs (total)..............: 11

root@kali:/media/root/NEW VOLUME# hcxpcaptool -k nowbetter.pmkid bettercap-wifi-handshakes.pcap 

reading from bettercap-wifi-handshakes.pcap
                                                
summary capture file:                           
---------------------
file name........................: bettercap-wifi-handshakes.pcap
file type........................: pcap 2.4
file hardware information........: unknown
file os information..............: unknown
file application information.....: unknown
network type.....................: DLT_IEEE802_11_RADIO (127)
endianness.......................: little endian
read errors......................: flawless
minimum time stamp...............: 19.08.2019 16:14:45 (GMT)
maximum time stamp...............: 20.08.2019 18:23:58 (GMT)
packets inside...................: 59
skipped packets (damaged)........: 0
packets with GPS data............: 0
packets with FCS.................: 59
EAPOL packets (total)............: 59
EAPOL packets (WPA2).............: 59
PMKIDs (total)...................: 11
PMKIDs (WPA2)....................: 59
PMKIDs from access points........: 11
best PMKIDs (total)..............: 11


root@kali:/media/root/NEW VOLUME# hcxpcaptool -z nowbetter.pmkid bettercap-wifi-handshakes.pcap 

reading from bettercap-wifi-handshakes.pcap
                                                
summary capture file:                           
---------------------
file name........................: bettercap-wifi-handshakes.pcap
file type........................: pcap 2.4
file hardware information........: unknown
file os information..............: unknown
file application information.....: unknown
network type.....................: DLT_IEEE802_11_RADIO (127)
endianness.......................: little endian
read errors......................: flawless
minimum time stamp...............: 19.08.2019 16:14:45 (GMT)
maximum time stamp...............: 20.08.2019 18:23:58 (GMT)
packets inside...................: 59
skipped packets (damaged)........: 0
packets with GPS data............: 0
packets with FCS.................: 59
EAPOL packets (total)............: 59
EAPOL packets (WPA2).............: 59
PMKIDs (total)...................: 11
PMKIDs (WPA2)....................: 59
PMKIDs from access points........: 11
best PMKIDs (total)..............: 11


root@kali:/media/root/NEW VOLUME# 

[bettercap-wifi-handshakes.zip](https://github.com/ZerBea/hcxtools/files/3522326/bettercap-wifi-handshakes.zip)

**Comment by donwildman** [comment]
Thanks for taking the time to help!
I will follow the recommendation from the other thread and use hcxpcaptool instead of bettercap and see if I can improve the results...

**Comment by ZerBea** [comment]
Downloaded the bettercap pcap file and run an analysis:

59 packets inside:
0 ESSID
59 EAPOL M1 frames

So there is nothing to convert running option -k (or other options than -K and -Z)
I tlooks llike bettercap failed. The attached pcap file is completely useless!
It's a good idea to make an issue report on bettercap git.

$ hcxpcaptool -k test.16800 bettercap-wifi-handshakes.pcap
reading from bettercap-wifi-handshakes.pcap
summary capture file:                           
file name........................: bettercap-wifi-handshakes.pcap
file type........................: pcap 2.4
file hardware information........: unknown
file os information..............: unknown
file application information.....: unknown
network type.....................: DLT_IEEE802_11_RADIO (127)
endianness.......................: little endian
read errors......................: flawless
minimum time stamp...............: 19.08.2019 16:14:45 (GMT)
maximum time stamp...............: 20.08.2019 18:23:58 (GMT)
packets inside...................: 59
skipped packets (damaged)........: 0
packets with GPS data............: 0
packets with FCS.................: 59
EAPOL packets (total)............: 59
EAPOL packets (WPA2).............: 59
PMKIDs (zeroed and useless)......: 19
PMKIDs (not zeroed - total)......: 11
PMKIDs (WPA2)....................: 59
PMKIDs from access points........: 11
best PMKIDs (total)..............: 11

**Comment by ZerBea** [comment]
I think we can close this issue here, because it is related to bettercap.
