### ISSUE TITLE
Issue Outputting Essid, Identity, PMKID File

### ISSUE THREAD

**Issue by LunarMinecraft** [ZerBea/hcxtools#112]
Hi ZerBea, thanks for making the great tools.

Just been trying to output the data using the following command:

"hcxpcaptool -E essidlist -I identitylist -U usernamelist -z homeoutputs.16800 home.pcapng"

Here is the summary of capture file: https://pastebin.com/smFMTse7

Oddly, when I execute the command to output the data, it appears with no error. I made sure that my home.pcapng file is within the same folder I am in. The home.pcapng file includes multiple networks with PMKID, handshake, etc...

It does not create any of the files in the directory, it creates a file "home.pcapng-0"

I ended up figuring out if I then did the same command again but changed for the new file like so:

hcxpcaptool -E essidlist -I identitylist -U usernamelist -z homeoutputs.16800 home.pcapng

Then it would output my "essidlist" and "homeoutputs.16800" files.

Although, the identitylist and usernamelist still are not outputting, any idea what is the cause for this and what I may be doing wrong?

Thanks for taking the time to read.

**Comment by ZerBea** [comment]
Summary looks like your home.pcapng is empty. Please attach it (zip compressed).

BTW:
If a pcapnag file with the same name exists, hcxdumptool append a  sequential number
home.pcapng
home.pcapng-1
home.pcapng-2
home.pcapng-3

**Comment by LunarMinecraft** [comment]
Thanks for the response. 

It is odd because it only appends the sequential number when I use hcxpcaptool command as shown above.

I attached a zip, in side is the home.pcapng generated from using hxcdumptool.

Also I attached "home.pcapng-0" which is generated from using hxcpcaptool on "home.pcapng"

Also I have included the output file "homeoutputs.16800" which is generated from using hxcpcaptool on "home.pcapng-0".

Hope this all makes sense to you, english is not my first language. Apologies if any mistakes in grammar.
[home.zip](https://github.com/ZerBea/hcxtools/files/3623598/home.zip)

**Comment by ZerBea** [comment]
home.pcapng is empty and contain no packets, but home.pcapng-0 looking good

$ hcxpcaptool -o test.hccapx -k test.16800 home.pcapng-0
reading from home.pcapng-0
summary capture file:                           
file name........................: home.pcapng-0
file type........................: pcapng 1.0
file hardware information........: x86_64
capture device vendor information: 00c0ca
file os information..............: Linux 5.2.0-kali2-amd64
file application information.....: hcxdumptool 5.2.2
network type.....................: DLT_IEEE802_11_RADIO (127)
endianness.......................: little endian
read errors......................: flawless
minimum time stamp...............: 17.09.2019 18:04:15 (GMT)
maximum time stamp...............: 17.09.2019 18:12:08 (GMT)
packets inside...................: 289
skipped damaged packets..........: 0
packets with GPS data............: 0
packets with FCS.................: 0
beacons (total)..................: 28
beacons (WPS info inside)........: 4
probe requests...................: 8
probe responses..................: 3
association requests.............: 31
association responses............: 26
reassociation requests...........: 1
reassociation responses..........: 1
authentications (OPEN SYSTEM)....: 40
authentications (BROADCOM).......: 39
authentications (NETGEAR)........: 1
EAPOL packets (total)............: 151
EAPOL packets (WPA2).............: 151
PMKIDs (not zeroed - total)......: 7
PMKIDs (WPA2)....................: 15
PMKIDs from access points........: 7
best handshakes (total)..........: 7 (ap-less: 7)
best PMKIDs (total)..............: 7

summary output file(s):
-----------------------
6 PMKID(s) written to test.16800
7 handshake(s) written to test.hccapx
message pair M12E2...............: 7

**Comment by LunarMinecraft** [comment]
Yes, this is what I noticed also when opening both files in wireshark to investigate the contents it appeared nothing with the first and the second one appeared. Very odd to me. 

Is there any reason that would cause this?

Here are the exact commands I used as follows:

`hcxdumptool -o home.pcapng -i wlan1 --enable_status 1
hcxpcaptool -E essidlist -I identitylist -U usernamelist -z homeoutputs.16800 home.pcapng`

// Here it should have made file homeoutputs.16800, along with others, but it did not. Instead it created home.pcapng-0

Next I do
`hcxpcaptool -E essidlist -I identitylist -U usernamelist -z homeoutputs.16800 home.pcapng-0`

Then it appears with 'essidlist' file and 'homeoutputs.16800' file. Does not make identitylist or usernamelist, and any reason why I have to do hxcpcaptool twice with different files? I tried following instructions but thought these commands were correct. Thanks!

**Comment by ZerBea** [comment]
Is there any reason that would cause this?
Yes, broken driver.
-I and -U lists are only filled, if the pcapng contain EAP or RADIUS data. If you didn't capture them, you will not get this lists.

**Comment by LunarMinecraft** [comment]
Oh this makes sense. I have  not installed any driver with my card. I plugged in and worked, could put  in monitor mode so I assumed everything was fine. Checked dkms status but no driver appeared. I will attempt to install driver and redo.

Thanks again for your help

**Comment by ZerBea** [comment]
No problem, you're welcome.

**Comment by ZerBea** [comment]
I took a closer look at the pcapng file and even though you run hcxpcaptool only for 8 minutes:
minimum time stamp...............: 17.09.2019 18:04:15 (GMT)
maximum time stamp...............: 17.09.2019 18:12:08 (GMT)
you captured a ten digit password:
packet 201 = ESSID
packet 202 = password
unfortunately you didn't capture a matching handshake, but the password is real and will open the network using this ESSID to which the client belongs.

**Comment by LunarMinecraft** [comment]
Wow I did not see that at all!

Thanks very much, this is surprising :D

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ZerBea** [comment]
Maybe not very surprising...
From README.md:
" hcxdumptool is able to capture passwords from the wlan traffic
  (use hcxpcaptool -E to save them to file, together with networknames)"

**Comment by LunarMinecraft** [comment]
I must have missed that part in the readme :D thanks, I tried this and it output the network names and what seems to be 1 of the passwords. How do you tell exactly which network is for which password? Each are on a new line so I am not sure.

Also some lines are "1F" or "77"

Which are not network names anywhere nearby, is that normal? Thanks!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ZerBea** [comment]
-T <file> : output management traffic information list
            format = mac_sta:mac_ap:essid
-X <file> : output client probelist
            format: mac_sta:probed ESSID (autohex enabled)

will do this for you in human readable format.
