### ISSUE TITLE
Feature Request: Log SSID with the captured hashes

### ISSUE THREAD

**Issue by Slad3G** [ZerBea/hcxtools#113]
First off, thanks for your hard work on such a great tool. I noticed that when I pull a cached key to crack there doesn't appear to be a way to keep the key associated with the correct ESSID or BSSID. Thus far, I have only used the demonstration in a lab environment however in a crowded Wi-Fi space I might be quessing which password goes with what network for quite awhile.

Thanks again,

SG

**Comment by ZerBea** [comment]
hashcat is doing this part for cracked networks:
hashcat.pot:
PMK:ESSID:PSK

hashcat -o
MAC_AP:MAC_STA:ESSID:PSK

while wlanhcxinfo is doing it for uncracked and/or cracked networks on hccapx files

and PMKID format is in ASCII:
PMKID:MAC_AP:MAC_STA:ESSID

Please give me an example (complete hashline) how the log should look like?

**Comment by Slad3G** [comment]
Thank you for such a quick response.  The captured PMKID line output from HCXPCAPTOOL is:
3690cf0758642982fb5b5b11255ef6d7*c03f0e6ee874*e0cb1de8c8e0*4353535f4c6162

I cracked my lab password with hashcat and the output in the potfile is as follows:

3690cf0758642982fb5b5b11255ef6d7*c03f0e6ee874*e0cb1de8c8e0*4353535f4c6162:Av1cular1st
 
How do I discern the SSID from the output I received?

Thanks again,

SG

**Comment by ZerBea** [comment]
The potfile isn't designed to be human readable. This will do -o option of hashcat for you.
Or use bash commands:
$ echo "4353535f4c6162" | perl -pe 's/(..)/chr(hex($1))/ge'
CSS_Lab
You can combine it with awk:
https://stackoverflow.com/questions/42828273/bash-hex-to-ascii-is-possible-without-xxd-or-perl

**Comment by Slad3G** [comment]
Thanks so much, this works perfect!

**Comment by ZerBea** [comment]
You can split the complete line running awk:
$ echo "3690cf0758642982fb5b5b11255ef6d7c03f0e6ee874e0cb1de8c8e0*4353535f4c6162:Av1cular1st" | awk 'BEGIN { FS = "*" } ; { print $2}' | awk 'BEGIN { FS = ":" } ; { print $1}' | perl -pe 's/(..)/chr(hex($1))/ge'
CSS_Lab

Ok, than we can close this request here.

**Comment by ZerBea** [comment]
hcxdumptool / hcxpcaptool received a nice new feature: weak_candidate
run hcxdumptool -i interface --o test.pcapng --enable_status=1 --weak_candidate=Av1cular1st
against your test router.

convert it:
$ hcxpcaptool -z test.16800 -W wordlist test.pcapng

run hashcat against it:
$ hashcat -m 16800 test.16800 wordlist
