### ISSUE TITLE
dosent want to install ;(

### ISSUE THREAD

**Issue by kattking16** [ZerBea/hcxtools#115]
root@LAPTOP:~/hcxtools$ make
gcc -O3 -Wall -Wextra -DDOACTIVE -o wlandump wlandump.c -lpcap
make: gcc: Command not found
Makefile:24: recipe for target 'build' failed
make: *** [build] Error 127

**Comment by ZerBea** [comment]
Make sure gcc compiler collection is installed.
wlandump is deprecated and was removed.
do a fresh git clone:
git clone https://github.com/ZerBea/hcxtools/
cd hcxtools
make
make install

This is not a hcxtools issue. so I close it, but you can still ask questions here.

**Comment by ZerBea** [comment]
I assume you're running KALI: https://pkg.kali.org/pkg/gcc-defaults
Learn how to install and use a development environment
https://www.cyberciti.biz/faq/debian-linux-install-gnu-gcc-compiler/
Don't forget to install all dependencies for hcxtools, too.
To install requirements on Kali use the following 'apt-get install libcurl4-openssl-dev libssl-dev zlib1g-dev'
