### ISSUE TITLE
Please help hcxtool

### ISSUE THREAD

**Issue by smileytermux** [ZerBea/hcxtools#118]
sorry about my english. Terminal give me error: Warning: Recommended app hcxpcaptool was not found . What I can do. And "enabling monitor mode on wlan0... failed
failed

 [!] Error: Cannot find any interfaces in Mode:Monitor

 [!] Full stack trace below

 [!]    Traceback (most recent call last):
 [!]    File "/root/wifite2/wifite/__main__.py", line 93, in entry_point
 [!]        wifite.start()
 [!]    File "/root/wifite2/wifite/__main__.py", line 53, in start
 [!]        Configuration.get_monitor_mode_interface()
 [!]    File "/root/wifite2/wifite/config.py", line 132, in get_monitor_mode_interface
 [!]        cls.interface = Airmon.ask()
 [!]    File "/root/wifite2/wifite/tools/airmon.py", line 319, in ask
 [!]        iface.interface = Airmon.start(iface)
 [!]    File "/root/wifite2/wifite/tools/airmon.py", line 190, in start
 [!]        raise Exception('Cannot find any interfaces in Mode:Monitor')
 [!]  Exception: Cannot find any interfaces in Mode:Monitor
"

What is it?

**Comment by ZerBea** [comment]
That is a wifite trace log, so you should ask your question here:
https://github.com/derv82/wifite2

Taking a closer look at the trace log, it looks like neither hcxtools nor hcxdumptool is  installed. You must install them both. Depending on your distribution you can do it by the package manager of your distribution or via git clone.
Also it looks like none of your interfaces support monitor mode and packet injection.

**Comment by ZerBea** [comment]
Read more here:
https://github.com/derv82/wifite2/issues/185

**Comment by ZerBea** [comment]
Closed, because it ins't hcxtools issue, but you can still ask your questions here.
