### ISSUE TITLE
hcxpcapngtool suggestions

### ISSUE THREAD

**Issue by jsteube** [ZerBea/hcxtools#119]
1. RC should be -1 if the command is invalid

```
$ ./hcxpcapngtool -o x
$ echo $?
0
```

2. Output file should not be created if the command is invalid

```
$ ls -l x
-rw-r--r-- 1 root root 0 Dec 17 14:26 x
```

**Comment by ZerBea** [comment]
fixed:
$ hcxpcapngtool -o x
no input file(s) selected

$ echo $?
1 (EXIT_FAILURE)
https://www.gnu.org/software/libc/manual/html_node/Exit-Status.html

$ ls -All
total 0
