### ISSUE TITLE
hcxhashcattool 22000 pot file format

### ISSUE THREAD

**Issue by benbuschmannBSP** [ZerBea/hcxtools#127]
As far as I can tell, the current potfile format from hashcat -m 22000 is (PMK*ESSID:PSK) not (PMK:ESSID:PSK)

https://github.com/hashcat/hashcat/commit/daaf5d365c0cc1ed1564cf41683cd66d45a4c07a#diff-2cdcbc3a6420df5727949c36fab2f87b

**Comment by ZerBea** [comment]
Thanks. Should be fixed by this commit:
https://github.com/ZerBea/hcxtools/commit/9ea20b96f98bc969c3fd30ba6d7816de1017d34b
Please test and close issue report, if it works.

BTW:
hcxhashcattool is deprecated. I'm going to remove it (and several old hcxtools, too) after release of hashcat 6.0.0.

**Comment by benbuschmannBSP** [comment]
I am getting:
`sperator doesn't match: 0eff19eeac2752b7252c95fe037b7637712b5bfaa467639aab6c4983731703be:64656d6f706f6f6c31:tryitout`

Is that potfile line not the "old" format

**Comment by ZerBea** [comment]
That is the new potfile format.
The old format is:
`MIC:MAC_AP:MAC_STA:ESSID:PSK`
or
`PMKID:MAC_AP:MAC_STA:ESSID : PSK`

Your potfile line is newer an can be converted by bash commands to the latest format:
`$ cat xx | sed 's/^\(.\{64\}\)./\1*/'
0eff19eeac2752b7252c95fe037b7637712b5bfaa467639aab6c4983731703be*64656d6f706f6f6c31:tryitout`

**Comment by benbuschmannBSP** [comment]
great thank you for the bash, that worked well

**Comment by ZerBea** [comment]
You're welcome.

BTW:
Running bash commands on the new hashline, is one of the major reasons to move from hccapx to HEX ASCII. The second major reason is the advantage of reuse of PBKDF2 over PMKID and EAPOL.
And the third major reason is the use of the potfile as rainbowtable on common ESSIDs (hashmode -m 22001).

**Comment by benbuschmannBSP** [comment]
I have seen anything about the use of the potfile as rainbowtable on common ESSIDs. Do you know of any posts giving examples of that technique?

**Comment by ZerBea** [comment]
The procedure is working if you have 2 or more different networks using the same ESSID (e.g. "home").
For this procedure, I suggest to run hcxpcapngtool --all on hcxdumptool pcapng file. It doesn't make sense to do this on hashes, converted from deadly cleaned cap files.
Also you need a good PMK data base!

Step 1: run hashcat on every new hashfile with potfile file and out file to collect data. Use this potfile only on mode 22000:
`hashcat -m 22000 --potfile-path="hashcat.pmk" -o "hashcat.psk" new.22000 wordlist`

Step 2: use results as reainbowtable:
```
cut -c -64 hashcat.pmk  | sort  l uniq > test.pmk
hashcat -m 22001 --logfile-disable  --nonce-error-corrections=8 --remove --potfile-disable -o confirmed.pmk new.22000 test.pmk
```

```
hashcat (v5.1.0-1669-gf85a0ea7) starting...

Session..........: hashcat
Status...........: Exhausted
Hash.Name........: WPA-PMK-PMKID+EAPOL
Hash.Target......: archive.22000
Time.Started.....: Wed Feb 12 08:40:45 2020 (13 mins, 11 secs)
Time.Estimated...: Wed Feb 12 08:53:56 2020 (0 secs)
Guess.Base.......: File (test.pmk)
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........: 26692.1 kH/s (0.00ms) @ Accel:64 Loops:1024 Thr:1024 Vec:1
Recovered........: 406456/419208 (96.96%) Digests, 123732/130296 (94.96%) Salts
Remaining........: 12752 (3.04%) Digests, 6564 (5.04%) Salts
Recovered/Time...: CUR:29332,N/A,N/A AVG:30840,1850416,44410003 (Min,Hour,Day)
Progress.........: 22675543176/22675543176 (100.00%)
Rejected.........: 0/22675543176 (0.00%)
Restore.Point....: 174031/174031 (100.00%)
Restore.Sub.#1...: Salt:130295 Amplifier:0-1 Iteration:0-1
Candidates.#1....: 0000000000000000000000000000000000000000000000000000000000000000 -> ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
Hardware.Mon.#1..: Temp: 69c Fan: 53% Util: 96% Core:1860MHz Mem:5005MHz Bus:16

```

On hashfiles converted from cap files with many bit errors you should increase NC up to 16
On hashfiles converted from hcxdumptool pcapng files you can decrease it to 4 or run automatic mode (no option --nonce-error-corrections).
Or take a look at status of hcxpcapngtool. It will show you the measured NC value.

Than compare PMKs from hashcat.pmk with confirmed.pmk to get the PSK for them. Can be done by bash commands.

Keep in mind:
It doesn't make sense, if you're hunting for a single network. But it makes sense if you're hunting for a weak point within the system! 

Explained in this thread, too:
https://hashcat.net/forum/thread-6661.html
