### ISSUE TITLE
hcxdumptools doesn´t work

### ISSUE THREAD

**Issue by zebiath** [ZerBea/hcxtools#129]
hi thanks zerbea for your awesome work and btw  im not a pro user, and i can´t make run the last version of hcxdumptool and hcxtools.
A few errors appears  when i install it and when i try to run it in wifislax. (same in kali)
This never happens to me last time i use it in the beginnings of 2019.
thanks for your time and sorry for my english

**Comment by ZerBea** [comment]
Most of the issues (nearly all) are related to is misconfigured distribution (broken installation, missing dependencies, driver that doesn't support monitor mode and full packet injection). 
To help you, I need the error logs from "make" and "make install". Also it is good to have the output of "uname -r and uname -s".
Also you write that you are not a "pro user". KALI is a distribution to be used by professional penetration testers. KALI must be configured to work as expected:
https://kali.training/lessons/5-configuring-kali-linux/

**Comment by ZerBea** [comment]
https://github.com/ZerBea/hcxdumptool/issues/101#issuecomment-598068155

**Comment by ZerBea** [comment]
closed due to too less information:
"A few errors appears" isn't enough
