### ISSUE TITLE
hcxpsktool Arris function error

### ISSUE THREAD

**Issue by StrongWind1** [ZerBea/hcxtools#133]
In hcxpsktool, when analyzing Arris essids the following return stops hcxpsktool from continuing to the next if statement for the three following 9+ length essids.

Simply removing this return fixes the issue
https://github.com/ZerBea/hcxtools/blob/3aa3be4552165fc339ea02dd2707bfc1f5daa865/hcxpsktool.c#L857
Alternatively you could switch the essidlen if statements around or remove both returns within both essidlen if statements as it seems they are unnecessary.

Also:
https://github.com/ZerBea/hcxtools/blob/3aa3be4552165fc339ea02dd2707bfc1f5daa865/hcxpsktool.c#L1279
This function is called twice within the prepareessid function.

**Comment by ZerBea** [comment]
Good investigation. Thanks.
Should be fixed by this commit, now:
https://github.com/ZerBea/hcxtools/commit/e6869462b1a5d1cb37d59abf33c4d8387a62131f
Please test and close issue if it is working for you.
