### ISSUE TITLE
(-k) PMKID Separator unmatched

### ISSUE THREAD

**Issue by dizcza** [ZerBea/hcxtools#134]
I'm using hcxdumptool-6.0.1 with hcxtools (master branch) and hashcat 5.1.0

I convert `hcxpcaptool -k bastion.pmkid output.pcapng` (not `-z`!)

Then I use `hashcat -m16800 --force bastion.pmkid /path/to/wordlist` I get the following error

```
Hashfile 'bastion.pmkid' on line 1 (adc63f...db9e2a893:574c414e2d445644464244): Separator unmatched
...
```

**Comment by ZerBea** [comment]
During the beta tests, we changed the delimiter several times from ":" to "*".
To be compatible with all version of hashcat and JtR we have 2 options:
```
-k <file> : output PMKID file (hashcat hashmode -m 16800 new format)
-z <file> : output PMKID file (hashcat hashmode -m 16800 old format and john)

```
The difference between them is the delimiter.

Option z should work with your version, but I recommend to update to latest git head of hashcat, and hcxtools to get full benefit of new hashmode 22000:
`hcxdumptool -> hcxpcapngtool -o test.22000 -> hascat -m 22000 test.22000
`
hcxpcapngtool is deprecated and will be replaced by hcxpcangtool.

**Comment by dizcza** [comment]
Ah, thank you.

I didn't realize that `-k` format is for hashcat _master_ while hashcat-5.1.0 is already _old_ (`-z`).

**Comment by ZerBea** [comment]
No problem. The move from : to * was necessary to be compatible with JtR:
https://github.com/hashcat/hashcat/issues/1816#issuecomment-567395688
Goal is to have only one hashline format, working on hashcat, JtR and hcxtools.
