### ISSUE TITLE
Missing dependency: curl

### ISSUE THREAD

**Issue by FabxBs** [ZerBea/hcxtools#140]
Fatal error: curl/curl.h: no such file or directory
19 | include <curl/curl.h>
compilation terminated
make: *** [Makefile:93: hcxhashtool]  Error 1

If is a missing depency of mine, wich one should i install on Kali?

**Comment by FabxBs** [comment]
Edit, i close the issue since i fixed, apologize for the misunderstanding

**Comment by ZerBea** [comment]
No problem, you're welcome.
The development files are not installed by default on Debian based distributions (like KALI). So you must install them.

**Comment by 0Jak0** [comment]
I am extremely bad at Linux at the moment and am running kali on a Raspberry Pi and cannot get libcurl-dev to install, how do I go about doing this?

**Comment by ZerBea** [comment]
That depend on your distribution and the supplied Linux Package Manager:
https://www.tecmint.com/linux-package-managers/
e.g.:
Arch Linux:
sudo pacman -S curl
https://www.archlinux.org/packages/core/x86_64/curl/

Debian (and its derivatives - that include KALI):
sudo apt-get install libcurl4-openssl-dev libssl-dev zlib1g-dev
https://packages.debian.org/de/jessie/libcurl-dev
If it doesn't work, you system is not updated and/or your package management system is broken.
In that case , you have to learn how do do this:
https://www.cbtnuggets.com/blog/certifications/security/a-beginners-guide-to-kali-linux-getting-started

Please note:
Running KALI Linux is not a good idea if you are a Linux newbie.
https://www.infoworld.com/article/3060814/should-beginners-install-kali-linux-on-their-computers.html

You can read more here.
https://forums.kali.org/
That is also the right place to ask KALI related basic questions like "how to install packages".

Please also note that the WiFi driver must support full monitor mode and full packet injection, by ioctl() system calls). That is not the case for the onboard WiFi chip of the Raspberry. In addition to that, there are only a few drivers which are able to handle this!
That means, you msut use a matching chipset/WiFi adapter.

**Comment by 0Jak0** [comment]
Thanks for the response, I'm not exactly a newbie at Linux as I've previously used other distros but am new to the things kali can do. I have tried the things that you told to do but am still having trouble with curl.h missing but I did not have this trouble when I installed it on a VM so I am wondering if it is the Kali for Pi installation issue? anyways I'll keep trying.

**Comment by ZerBea** [comment]
Ok, that could be a KALI for Pi issue - if they haven't added the src (deb-src) repository to the sources.list. It is also possible that they running an older version of the src.
Maybe you can find it out by comparing the list from the VM with the list from the RPI:
https://www.kali.org/docs/general-use/kali-linux-sources-list-repositories/

**Comment by 0Jak0** [comment]
i checked sources.list and they're identicle

**Comment by ZerBea** [comment]
If the file system isn't broken (that happens sometimes running a RPI on a sd-card), the packages should be installable:
https://pkg.kali.org/pkg/curl
Have you checked the file system of the sd-card?

What is the error message when running:
`$ apt-get install libcurl4-openssl-dev libssl-dev zlib1g-dev
`
and the version of KALI:
`$ uname -a`

**Comment by 0Jak0** [comment]
ok, so I have just tried re-burning a freshly downloaded kali .img and am having the same issue. when I run "sudo apt-get install libcurl-openssl-dev libssl-dev zlib1g-dev" i get 

#Reading package lists ... Done
#Building dependency tree
#Reading state information ... Done 
#E: Unable to locate package libcurl4-openssl-dev 

which is strange as I didn't have this issue on a VM or on a live USB of kali so it seems like its a Kali for Pi issue.

i did find that when I did this command

#kali@kali:~$ grep -v '#' /etc/apt/sources.list | sort -u
​on the VM is is 'deb http://http.kali.org/kali kali-rolling main non-free contrib'
on the the fresh install on the Pi 'deb http://kali.download/kali http://http.kali.org/kali main contrib non-free'

which is interesting as this wants the case on the old Pi install. I am extremely confused as I have seen videos on youtube of this issue and it is solved by doing 'apt-get install libcurl4-openssl-dev' but this does not work on my Pi.

**Comment by ZerBea** [comment]
According to this:
http://kali.download/kali/pool/main/c/curl/
it should be present.

According to this:
https://www.kali.org/docs/general-use/kali-linux-sources-list-repositories/
"Source Repositories" should be uncommented.

Please output of uname -a  for the RPI.
KALI is a rolling release and you have to update the sources, before trying to install a package.

**Comment by ZerBea** [comment]
Could be an issue related to KALI for RPI and RASPIAN on which it is based:
https://www.raspberrypi.org/forums/viewtopic.php?t=209295
caused by a versioning mismatch.

I never had this trouble, running Arch Linux.

**Comment by 0Jak0** [comment]
when I do 'uname -a' i get 'Linux Kali 4.19.118-Re4son-v8+ #1 SMP PREEMPT Wed May 6 12:44:21 UTC 2020 aarch64 GNU/Linux' when I do 'sudo apt update I get 
'

**Comment by 0Jak0** [comment]
I think I may have to wait until the next official release of kali to see if that solves the issue as I am not finding any way to fix this at the moment

**Comment by ZerBea** [comment]
For sure, that is strange and it looks like the package management is broken and you're running into a versioning issue.
In addition to this, your your kernel "Linux Kali 4.19.118" is outdated, too.
https://www.kernel.org/

It is not possible to upgrade/install packages from this old version.
If you really need KALI, here are the latest arm images:
https://www.offensive-security.com/kali-linux-arm-images/

**Comment by 0Jak0** [comment]
that's what makes it even stranger is that that's where I downloaded the .img file for it yesterday

**Comment by ZerBea** [comment]
For KALI, it isn't strange. I mentioned that in several comments:
If you are not a penetration tester and if you don't need all the penetration tools inside of KALI, don't use it.

**Comment by ZerBea** [comment]
Several years ago I moved from Debian to Arch. Arch is running on all systems (Desktop, Notebook, RPIs) without running into a dependency hell.
All systems are manual configured. Desktop and Notbook running XFCE while the RPIs don't use a GUI (they are controlled via SSH). No unnecessary programs are installed and no unnecessary services are running.
That isn't the case if you install UBUNTU, KALI or some other distributions.

When you've read all the issue reports, here, you will surely have noticed that most (nearly all) of the reported issues are related to KALI!

**Comment by 0Jak0** [comment]
Yes very true I have noticed that kali has a lot of issues with a lot of things and it is rather annoying. as I just want something that I don't have to install every piece of software separately and kali seemed like the perfect option but as I have experienced it is not. the Pi is supposed to be a machine that I can leave on sight plugged into a power bank or the wall in a hidden location so I can have a machine on the inside that can be remotely accessed.

**Comment by ZerBea** [comment]
Please don't misunderstand me. KALI is a good distribution for a penetration tester. All necessary penetration testing tools are installed and you can use them.  That include hcxtools:
https://pkg.kali.org/pkg/hcxtools
Unfortunately KALI is not designed to compile new tools (dependencies not installed by default) or to code and/or test new tools (missing dependencies).

**Comment by ZerBea** [comment]
BTW:
The same applies to hcxdumptool. Not every driver is suitable due to missing monitor mode and missing packet injection capabilities or NETLINK dependency.

**Comment by 0Jak0** [comment]
I know, I like KALI but this is rather annoying considering that its supposedly the latest release for arm. I wasn't having any issues putting the inbuilt wireless card into monitor mode so that's all fine. But I'll see how the next release turns out. thanks for your help any way.

**Comment by ZerBea** [comment]
Unfortunately I can't help here.
BTW:
The driver issues are mostly related to the user. Running Linux, it is mandatory to check out what chipset is build in and does the driver support monitor mode/packet injection, before(!) purchasing an adapter.

**Comment by ZerBea** [comment]
Looks like KALI package management is broken (again):
https://forum.aircrack-ng.org/index.php/topic,7725.msg14106.html#msg14106
