### ISSUE TITLE
[Feature] split 22000 by essid

### ISSUE THREAD

**Issue by dizcza** [ZerBea/hcxtools#150]
Hello ZerBea,

1. I'm switching my workflow to convert everything (.cap, .hccapx, and .pmkid) to 22000 format, because it's superior. But I cannot find grouping methods that work with 22000 as for example in `wlanhcx2ssid` for hccapx files. Also, `wlanhcxinfo` support for 22000 would be nice to have.

2. Are hcxmactool and the commands below deprecated? It's not clear from the table. If they are deprecated, consider creating a separate table and marking the commands listed as deprecated.

**Comment by ZerBea** [comment]
The workflow didn't change running new hash mode 22000:
hcxdumptool -> hcxpcapngtool -> hcxhashtool -> hashcat

hcxdumptool -> attack and dump
hcxpcapngtool -> convert to hash mode 22000
hcxhashtool -> filter hashes

hcxhashtool is designed to work on 22000 hash files and provide all filter options known from wlanhcx2ssid and wlanhcxinfo:
```
$ hcxhashtool -h
hcxhashtool 6.0.2-59-g233106b (C) 2020 ZeroBeat
usage:
hcxhashtool <options>

options:
-i <file>   : input PMKID/EAPOL hash file
-o <file>   : output PMKID/EAPOL hash file
-E <file>   : output ESSID list (autohex enabled)
-d          : download http://standards-oui.ieee.org/oui.txt
            : and save to ~/.hcxtools/oui.txt
            : internet connection required
-h          : show this help
-v          : show version

--essid-group                : convert to ESSID groups in working directory
                               full advantage of reuse of PBKDF2
                               not on old hash formats
--oui-group                  : convert to OUI groups in working directory
                               not on old hash formats
--mac-group-ap               : convert APs to MAC groups in working directory
                               not on old hash formats
--mac-group-client           : convert CLIENTs to MAC groups in working directory
                               not on old hash formats
--type                       : filter by hash type
                             : default PMKID (1) and EAPOL (2)
--essid-len                  : filter by ESSID length
                             : default ESSID length: 0...32
--essid-min                  : filter by ESSID minimum length
                             : default ESSID minimum length: 0
--essid-max                  : filter by ESSID maximum length
                             : default ESSID maximum length: 32
--essid=<ESSID>              : filter by ESSID
--essid-part=<part of ESSID> : filter by part of ESSID
--mac-ap=<MAC>               : filter AP by MAC
                             : format: 001122334455, 00:11:22:33:44:55, 00-11-22-33-44-55 (hex)
--mac-client=<MAC>           : filter CLIENT by MAC
                             : format: 001122334455, 00:11:22:33:44:55, 00-11-22-33-44-55 (hex)
--oui-ap=<OUI>               : filter AP by OUI
                             : format: 001122, 00:11:22, 00-11-22 (hex)
--oui-client=<OUI>           : filter CLIENT by OUI
                             : format: 001122, 00:11:22, 00-11-22 (hex)
--vendor=<VENDOR>            : filter by (part of) VENDOR name
--authorized                 : filter EAPOL pairs by status authorized
--notauthorized              : filter EAPOL pairs by status not authorized
--rc                         : filter EAPOL pairs by replaycount status checked
--apless                     : filter EAPOL pairs by status M1M2ROGUE (M2 requested from CLIENT)
--info=<file>                : output detailed information about content of hash file
--info=stdout                : stdout output detailed information about content of hash file
--vendorlist                 : stdout output VENDOR list sorted by OUI
--psk=<PSK>                  : pre-shared key to test
                             : due to PBKDF2 calculation this is a very slow process
                             : no nonce error corrections
--pmk=<PMK>                  : plain master key to test
                             : no nonce error corrections
--hccapx=<file>              : output to deprecated hccapx file
--hccap=<file>               : output to ancient hccap file
--hccap-single               : output to ancient hccap single files (MAC + count)
--john=<file>                : output to deprecated john file
--help                       : show this help
--version                    : show version
```
In addition to hcxhashtool all bash commands are working on the new hash format (grep, sort, awk, cat, head, sort).

This tools are deprecated and will become obsolete when hashcat and JtR moved to new PMKID/EAPOL hash line
| hcxmactool     | Various MAC based filter operations on HCCAPX and PMKID files - convert hccapx and/or PMKID to new hashline format     |
| hcxpcaptool    | Shows info of pcap/pcapng file and convert it to other hashformats accepted by hashcat and John the Ripper             |
| hcxpmkidtool   | CPU based tools to verfiy a PMKID                                                                                      |
| hcxessidtool   | Various ESSID based filter operations on HCCAPX and PMKID files                                                        |
| hcxhashcattool | Convert old hashcat (<= 5.1.0) separate potfile (2500 and/or 16800) to new potfile format                              |
| wlanwkp2hcx    | Converts wpk (ELMCOMSOFT EWSA projectfile) to hccapx                                                                   |
| wlanhcx2ssid   | Strips BSSID, ESSID, OUI                                                                                               |
| wlanhcxinfo    | Shows detailed info from contents of hccapxfile                                                                        |
| wlanhcxcat     | Simple password recovery tool for WPA/WPA2/WPA2 SHA256 AES-128-CMAC (hash-modes 2500, 2501)                            |
| wlanpmk2hcx    | Converts plainmasterkey and ESSID for use with hashcat hash-mode 12000 or john PBKDF2-HMAC-SHA1                        |
| wlanjohn2hcx   | Converts john wpapsk hashfiles for use with hashcat hash-modes 2500, 2501                                              |
| wlanhcx2john   | Converts hccapx to format expected by John the Ripper                                                                  |

**Comment by ZerBea** [comment]
By latest commit, the tool overview is divided into two parts: new tools, deprecated tools.

hcxhashtool examples can be found here:
https://hashcat.net/forum/thread-6661-post-48055.html#pid48055

**Comment by dizcza** [comment]
Right, I don't know how I missed `--essid-group`. Maybe I tried to run it in the same directory where the input filename matches the hex of essid and hence could not see any new files popping out. Now I see that it works when I tried to feed it a file with many APs.

Yes, providing grepping, cutting, and other text manipulation commands directly with hashes I find useful! This, I guess, allowed you to combine the most used command in one tool, `hcxhashtool`. I always felt dizzy trying to guess which command I need to perform a certain IO operation on a hccapx/pmkid file with old (deprecated) functionality.

Thank you.

**Comment by ZerBea** [comment]
I'm just waiting for hashcat and JtR moving to new hash format. Than I'm going to remove the old tools.

**Comment by dizcza** [comment]
Removing these tools immediately after the 6.0.0 release might be a little offhand. I've already switched to 22000, but many users might still be unaware of the new file format because it's not on the main page of hashcat. I didn't know about 22000 before you pointed me to it a few months ago.

**Comment by ZerBea** [comment]
Please do not worry. It will take a while until the tools will be removed. We decided to leave old and new format side by side for a while.
BTW:
Please notice, that potfile and outfile format changed too.

**Comment by dizcza** [comment]
Yes, I noticed the `hcxhashcattool` conversion tool.
The potfile format is changed but not the output key format (`--outfile`) ... strange.

**Comment by ZerBea** [comment]
Output format is described here:
https://github.com/hashcat/hashcat/issues/2290

New potfile format can be used as "rainbow table" for hashmode 22001:
$ cut -c -64 hashcat.potfile
