### ISSUE TITLE
waypoints in NMEA file generated by hcxpcapngtool are incorrect

### ISSUE THREAD

**Issue by dracode** [ZerBea/hcxtools#161]
Part of the latitude is being dropped when creating $GPWPL messages.

Expected: GPWPL would represent latitude as **ddmm.ffff**
Actual: GPWPL outputs only **m.ffff**

This is what i find in the .nmea file.  Actual coordinates and MAC removed for privacy:
```
$GPGGA,171639,ddmm.ffff,N,xxxxx.xxxx,W,1,4,1.420684212132504,89.5,M,,,,*06
$GPWPL,m.ffff,N,xxxxx.xxxx,W,1,4,,mmmmmmmmmmmm*44
```

**Comment by ZerBea** [comment]
Thanks for the issue report.
Tested hcxdumptool and noticed that it is broken, too.
Now I'm hunting for the issue.

**Comment by ZerBea** [comment]
Fixed hcxdumptool issue.
What version (hcxpcapngtool) are you running?
Please update to latest git head of hcxdumptool and hcxtools;
$ hcxdumptool -v
hcxdumptool 6.1.2-35-gf8a3f26 (C) 2020 ZeroBeat
]$ hcxpcapngtool -v
hcxpcapngtool 6.1.2-44-ge818238 (C) 2020 ZeroBeat

Then run a test:
$ hcxdumptool -i interface [--use_gpsd or --use_gps_device=your_device] -o test.pcapng
$ hcxpcapngtool --nmea=nmea.txt test.pcapng

My output looks like this, now:
```
$GPRMC,153437.00,A,xxxx.xx366,N,00xxx.xx632,E,0.131,,081020,,,A*75
$GPGGA,153437.00,xxxx.xx366,N,00xxx.xx632,E,1,08,1.04,483.4,M,47.0,M,,*54
$GPWPL,xxxxx.xx366,N,00xxx.xx632,E,544e45ade8d9*41
```

**Comment by ZerBea** [comment]
If you're running GPSD (--use_gpsd) instead of connecting to the device directly (--use_gps_device) make sure you're running at least v3.21 or higher:
$ gpsd --version
gpsd: 3.21 (revision 3.21)

**Comment by ZerBea** [comment]
edited
https://github.com/ZerBea/hcxtools/issues/161#issuecomment-705662800

**Comment by dracode** [comment]
I did a test today using the latest builds compiled straight from git:
```
hcxdumptool 6.1.3-1-ga9797d9 (C) 2020 ZeroBeat
hcxpcapngtool 6.1.3-1-gb10fb76 (C) 2020 ZeroBeat
```

The output is still incorrect for me.

It looks like one critical difference is in the timestamp field.  In yours, you have decimal fractions of a second: "153437.00", while in mine, there is no fractional second: "162317".  This means that for me, the interesting data begins at 14, not 17.

Other potential sources for error when using fixed length are the lat/long fields themselves.  The example [here](http://aprs.gids.nl/nmea/) includes 4 digits after the decimal, while the one [here](https://www.gpsinformation.org/dale/nmea.htm) only includes 3.  [This example](https://www.trimble.com/OEM_ReceiverHelp/V4.44/en/NMEA-0183messages_GGA.html) shows the timestamp with 1 digit after the decimal, and 8 digits following the decimal for lat/longs.

I think it would be better to partially parse the GPGGA/GPRMC sentences and split at the appropriate field delimiters, as there is no guarantee on the length of these fields.

**Comment by dracode** [comment]
Here is sample output from two different GPS devices from my own logs:

```
$GPGGA,203451,xxxx.xx2217,N,xxxxx.xx9090,W,2,09,1.1,120.0,M,-41.0,M,,*7D
$GPGGA,203452,xxxx.xx1137,N,xxxxx.xx8532,W,2,09,1.0,121.0,M,-41.0,M,,*70
$GPGGA,203453,xxxx.xx0138,N,xxxxx.xx8022,W,2,09,1.0,122.0,M,-41.0,M,,*78
```

```
$GPGGA,132947,xxxx.xx40,N,xxxxx.xx89,W,1,4,0.9595,85.5999,M,,,,*37
$GPGGA,132948,xxxx.xx48,N,xxxxx.xx80,W,1,4,0.9504,85.5999,M,,,,*30
$GPGGA,132949,xxxx.xx55,N,xxxxx.xx69,W,1,4,0.9384,85.5999,M,,,,*37
```

**Comment by ZerBea** [comment]
Thanks. Your example is good. It looks like we have different variants.
I'm running a Navilock NL-701US. Can you please tell me what devices you are using for the first and for the second sample?
Now I'm going to  rewrite the parser.

**Comment by ZerBea** [comment]
By latest commit
https://github.com/ZerBea/hcxtools/commit/342e10891b248f4ee8101d34a815a2803ab86019
I refactored the NMEA parser.
Now we count the delimiter ',' instead of using a fix position. Please test.

**Comment by ZerBea** [comment]
BTW:
output can be converted to gpx format accepted by Viking:
```
$ hcxpcapngtool --nmea=test.nmea test.pcapng
$ gpsbabel -i nmea -f "test.nmea" -o gpx,gpxver=1.1 -F "test.gpx"
```

**Comment by dracode** [comment]
This works perfectly.  Thanks!

I am amazed how quickly you respond.  I contrast this with the two crash-causing issues I opened in aircrack-ng where nobody has even bothered to respond in over two weeks.

**Comment by ZerBea** [comment]
Glad to hear that it works, now. I really thought that there is a kind of NMEA standard, but unfortunately that is not the case.

BTW1:
Mister-X- is very busy. Therefore, when he has time, he works on improvements. That applies for the whole aircrack-ng team, too. I'm sure, if they find some time, they'll work on a fix.

BTW2:
Running libnl isn't a good choice. I decided not to add this to hcxdumptool, because it will make us slow. I prefer ioctl() system calls and an AF_PACKET socket instead of NETLINK.
https://www.quora.com/What-are-the-differences-between-netlink-sockets-and-ioctl-calls
