### ISSUE TITLE
Weird $HEX hash

### ISSUE THREAD

**Issue by adrastee** [ZerBea/hcxtools#167]
Hi,
Using recent version of hcxpcapngtool, I get some weird 22000 hashes:

`WPA*02*XXX*YYY*ZZZ*XXX*ZZZ*0803017512020a2004006009000000fbbc8abfc24b39f44XXX$HEX[2020202020102021d0a4d070d482d0b01180]*`

`WPA*01*XXX*YYY*ZZZ*ZZZ*$HEX[0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20]*`

Why $HEX here?

**Comment by ZerBea** [comment]
Looks like an issue. Can I have the pcapng file, please.
If you don't want to add them here, you can send them via mail.
grep my addr from here:
https://api.github.com/users/ZerBea/events/public
How to is here:
https://www.sourcecon.com/how-to-find-almost-any-github-users-email-address/

**Comment by ZerBea** [comment]
Checked the source here:
PMKID out:
https://github.com/ZerBea/hcxtools/blob/master/hcxpcapngtool.c#L1864

EAPOL out:
https://github.com/ZerBea/hcxtools/blob/master/hcxpcapngtool.c#L1748

We don't print a string (%s) value which can cause the $HEX[] output.
I need the cap/pcap/pcapng file to reproduce it.
None of my pcapng files and the to wpa-sec submitted cap/pcap/pcapng files showing this issue, as well as your command line.
Do you run hcxpcapngtool within a script?

**Comment by adrastee** [comment]
Yes using a script.. you're right the problem is me :D
Will close thie issue. Thanks for quick help.

**Comment by ZerBea** [comment]
I'm glad to hear that you found the issue.
The new hash format has many, many advantages. But it has also a big disadvantage:
Due to speed reasons, Jens and I, we both, decided not ad add an integrity check or a versioning. If something destroyed the has file, it become unusable.

Only raw output/input will do a (simple)  CRC):
```
--raw-out=<file>                   : output frames in HEX ASCII
                                   : format: TIMESTAMP*LINKTYPE*FRAME*CHECKSUM
--raw-in=<file>                    : input frames in HEX ASCII
                                   : format: TIMESTAMP*LINKTYPE*FRAME*CHECKSUM
```

As well as NMEA output:
```
--nmea=<file>                      : output GPS data in NMEA format
                                     format: NMEA 0183 $GPGGA, $GPRMC, $GPWPL
                                     to convert it to gpx, use GPSBabel:
                                     gpsbabel -i nmea -f hcxdumptool.nmea -o gpx,gpxver=1.1 -F hcxdumptool.gpx
                                     to display the track, open file.gpx with viking
```

In both cases we have enough time to do this.
