### ISSUE TITLE
sudo make

### ISSUE THREAD

**Issue by osamahs7s** [ZerBea/hcxtools#176]
sudo make                                                                                                 2 ⨯
make: pkg-config: No such file or directory
make: pkg-config: No such file or directory
make: *** No rule to make target 'hcxdumptool', needed by 'build'.  Stop.

**Comment by ZerBea** [comment]
There are missing dependencies that you have to satisfy before compiling hcxtools/hcxdumptool.
Make told you that pkg-config is not installed:
`make: pkg-config: No such file or directory`

From README.md:
```
Requirements
--------------

* Linux (recommended Arch Linux, but other distros should work, too (no support for other distributions).

* gcc 10 recommended (deprecated versions are not supported: https://gcc.gnu.org/)

* libopenssl and openssl-dev installed

* librt and librt-dev installed (should be installed by default)

* zlib and zlib-dev installed (for gzip compressed cap/pcap/pcapng files)

* libcurl and curl-dev installed (used by whoismac and wlancap2wpasec)

* libpthread and pthread-dev installed (used by hcxhashcattool)

* pkg-config installed

To install requirements on Kali use the following 'apt-get install pkg-config libcurl4-openssl-dev libssl-dev zlib1g-dev'
```
Closed, because it isn't a hcxtools issue, but you can still ask your questions here.
