### ISSUE TITLE
I have get a issue like this, what can i do now?

### ISSUE THREAD

**Issue by UnknownHacker01** [ZerBea/hcxtools#178]
mkdir -p .deps
make: pkg-config: No such file or directory
make: pkg-config: No such file or directory
cc -O3 -Wall -Wextra -std=gnu99   -MMD -MF .deps/hcxdumptool.d -o hcxdumptool hcxdumptool.c   -DVERSION_TAG=\"6.1.4-41-gc41e29a\" -DVERSION_YEAR=\"2020\"
/usr/bin/ld: /tmp/ccLc0NVK.o: in function `globalclose':
hcxdumptool.c:(.text+0x1033): undefined reference to `SSL_free'
/usr/bin/ld: /tmp/ccLc0NVK.o: in function `detectweakwpa':
hcxdumptool.c:(.text+0x278c): undefined reference to `PKCS5_PBKDF2_HMAC_SHA1'
/usr/bin/ld: hcxdumptool.c:(.text+0x28e9): undefined reference to `EVP_sha256'
/usr/bin/ld: hcxdumptool.c:(.text+0x2913): undefined reference to `HMAC'
/usr/bin/ld: hcxdumptool.c:(.text+0x2926): undefined reference to `CMAC_CTX_new'
/usr/bin/ld: hcxdumptool.c:(.text+0x2939): undefined reference to `EVP_aes_128_cbc'
/usr/bin/ld: hcxdumptool.c:(.text+0x2957): undefined reference to `CMAC_Init'
/usr/bin/ld: hcxdumptool.c:(.text+0x298c): undefined reference to `CMAC_Update'
/usr/bin/ld: hcxdumptool.c:(.text+0x299c): undefined reference to `CMAC_CTX_free'
/usr/bin/ld: hcxdumptool.c:(.text+0x2b0e): undefined reference to `EVP_sha1'
/usr/bin/ld: hcxdumptool.c:(.text+0x2b3b): undefined reference to `HMAC'
/usr/bin/ld: hcxdumptool.c:(.text+0x2b75): undefined reference to `EVP_sha1'
/usr/bin/ld: hcxdumptool.c:(.text+0x2b9c): undefined reference to `HMAC'
/usr/bin/ld: hcxdumptool.c:(.text+0x2cf9): undefined reference to `EVP_md5'
/usr/bin/ld: hcxdumptool.c:(.text+0x2d1e): undefined reference to `CMAC_Final'
/usr/bin/ld: /tmp/ccLc0NVK.o: in function `globalinit':
hcxdumptool.c:(.text+0x3b33): undefined reference to `OpenSSL_version_num'
/usr/bin/ld: hcxdumptool.c:(.text+0x3fee): undefined reference to `OPENSSL_init_ssl'
/usr/bin/ld: hcxdumptool.c:(.text+0x3ff7): undefined reference to `OPENSSL_init_ssl'
/usr/bin/ld: hcxdumptool.c:(.text+0x3ffc): undefined reference to `TLS_server_method'
/usr/bin/ld: hcxdumptool.c:(.text+0x4004): undefined reference to `SSL_CTX_new'
/usr/bin/ld: hcxdumptool.c:(.text+0x4028): undefined reference to `SSL_CTX_use_certificate_file'
/usr/bin/ld: hcxdumptool.c:(.text+0x4048): undefined reference to `SSL_CTX_use_PrivateKey_file'
/usr/bin/ld: hcxdumptool.c:(.text+0x4084): undefined reference to `SSL_CTX_ctrl'
/usr/bin/ld: hcxdumptool.c:(.text+0x409c): undefined reference to `SSL_CTX_set_verify'
/usr/bin/ld: hcxdumptool.c:(.text+0x40b4): undefined reference to `SSL_CTX_ctrl'
/usr/bin/ld: hcxdumptool.c:(.text+0x40cc): undefined reference to `SSL_CTX_ctrl'
/usr/bin/ld: hcxdumptool.c:(.text+0x40da): undefined reference to `SSL_CTX_set_quiet_shutdown'
/usr/bin/ld: hcxdumptool.c:(.text+0x41e1): undefined reference to `ERR_print_errors_fp'
/usr/bin/ld: /tmp/ccLc0NVK.o: in function `printpmkid':
hcxdumptool.c:(.text+0x475f): undefined reference to `EVP_sha1'
/usr/bin/ld: hcxdumptool.c:(.text+0x478b): undefined reference to `HMAC'
/usr/bin/ld: hcxdumptool.c:(.text+0x490d): undefined reference to `PKCS5_PBKDF2_HMAC_SHA1'
/usr/bin/ld: hcxdumptool.c:(.text+0x4c37): undefined reference to `EVP_sha1'
/usr/bin/ld: hcxdumptool.c:(.text+0x4c61): undefined reference to `HMAC'
/usr/bin/ld: hcxdumptool.c:(.text+0x4d78): undefined reference to `PKCS5_PBKDF2_HMAC_SHA1'
/usr/bin/ld: /tmp/ccLc0NVK.o: in function `send_eap_tls_eap':
hcxdumptool.c:(.text+0x70e8): undefined reference to `SSL_write'
/usr/bin/ld: hcxdumptool.c:(.text+0x7107): undefined reference to `BIO_ctrl'
/usr/bin/ld: hcxdumptool.c:(.text+0x7132): undefined reference to `BIO_read'
/usr/bin/ld: hcxdumptool.c:(.text+0x7473): undefined reference to `BIO_read'
/usr/bin/ld: /tmp/ccLc0NVK.o: in function `send_eap_tls':
hcxdumptool.c:(.text+0x8381): undefined reference to `SSL_write'
/usr/bin/ld: hcxdumptool.c:(.text+0x83a0): undefined reference to `BIO_ctrl'
/usr/bin/ld: hcxdumptool.c:(.text+0x83e2): undefined reference to `BIO_read'
/usr/bin/ld: hcxdumptool.c:(.text+0x86dc): undefined reference to `BIO_read'
/usr/bin/ld: /tmp/ccLc0NVK.o: in function `process80211exteap_resp':
hcxdumptool.c:(.text+0xef23): undefined reference to `SSL_shutdown'
/usr/bin/ld: hcxdumptool.c:(.text+0xef42): undefined reference to `SSL_free'
/usr/bin/ld: /tmp/ccLc0NVK.o: in function `process80211exteap_resp_tls':
hcxdumptool.c:(.text+0x10696): undefined reference to `SSL_free'
/usr/bin/ld: hcxdumptool.c:(.text+0x106d7): undefined reference to `SSL_is_init_finished'
/usr/bin/ld: hcxdumptool.c:(.text+0x10729): undefined reference to `SSL_in_init'
/usr/bin/ld: hcxdumptool.c:(.text+0x107e6): undefined reference to `BIO_write'
/usr/bin/ld: hcxdumptool.c:(.text+0x10809): undefined reference to `SSL_get_shutdown'
/usr/bin/ld: hcxdumptool.c:(.text+0x10824): undefined reference to `SSL_is_init_finished'
/usr/bin/ld: hcxdumptool.c:(.text+0x10831): undefined reference to `ERR_clear_error'
/usr/bin/ld: hcxdumptool.c:(.text+0x10840): undefined reference to `SSL_accept'
/usr/bin/ld: hcxdumptool.c:(.text+0x10860): undefined reference to `SSL_get_error'
/usr/bin/ld: hcxdumptool.c:(.text+0x10878): undefined reference to `ERR_get_error'
/usr/bin/ld: hcxdumptool.c:(.text+0x108b7): undefined reference to `SSL_free'
/usr/bin/ld: hcxdumptool.c:(.text+0x10a74): undefined reference to `SSL_is_init_finished'
/usr/bin/ld: hcxdumptool.c:(.text+0x10a8b): undefined reference to `SSL_do_handshake'
/usr/bin/ld: hcxdumptool.c:(.text+0x10a9c): undefined reference to `SSL_new'
/usr/bin/ld: hcxdumptool.c:(.text+0x10aaf): undefined reference to `SSL_set_accept_state'
/usr/bin/ld: hcxdumptool.c:(.text+0x10ab4): undefined reference to `BIO_s_mem'
/usr/bin/ld: hcxdumptool.c:(.text+0x10ac3): undefined reference to `BIO_new'
/usr/bin/ld: hcxdumptool.c:(.text+0x10acc): undefined reference to `BIO_s_mem'
/usr/bin/ld: hcxdumptool.c:(.text+0x10adb): undefined reference to `BIO_new'
/usr/bin/ld: hcxdumptool.c:(.text+0x10b03): undefined reference to `SSL_set_bio'
/usr/bin/ld: hcxdumptool.c:(.text+0x10be1): undefined reference to `BIO_write'
/usr/bin/ld: hcxdumptool.c:(.text+0x10c2e): undefined reference to `SSL_shutdown'
/usr/bin/ld: hcxdumptool.c:(.text+0x10c47): undefined reference to `SSL_free'
/usr/bin/ld: hcxdumptool.c:(.text+0x10cab): undefined reference to `SSL_read'
/usr/bin/ld: hcxdumptool.c:(.text+0x10f92): undefined reference to `ERR_reason_error_string'
/usr/bin/ld: hcxdumptool.c:(.text+0x110e8): undefined reference to `SSL_shutdown'
/usr/bin/ld: hcxdumptool.c:(.text+0x111ed): undefined reference to `SSL_shutdown'
/usr/bin/ld: /tmp/ccLc0NVK.o: in function `process_fd':
hcxdumptool.c:(.text+0x15d9a): undefined reference to `SSL_shutdown'
/usr/bin/ld: hcxdumptool.c:(.text+0x15da9): undefined reference to `SSL_free'
collect2: error: ld returned 1 exit status
make: *** [Makefile:73: hcxdumptool] Error 1

**Comment by ZerBea** [comment]
First step is to take a look at README.md. You'll see requirements and to satisfy the dependencies:

```
Requirements
--------------
* Linux (recommended Arch Linux, but other distros should work, too (no support for other distributions).
* gcc 10 recommended (deprecated versions are not supported: https://gcc.gnu.org/)
* libopenssl and openssl-dev installed
* librt and librt-dev installed (should be installed by default)
* zlib and zlib-dev installed (for gzip compressed cap/pcap/pcapng files)
* libcurl and curl-dev installed (used by whoismac and wlancap2wpasec)
* libpthread and pthread-dev installed (used by hcxhashcattool)
* pkg-config installed
To install requirements on Kali use the following 'apt-get install pkg-config libcurl4-openssl-dev libssl-dev zlib1g-dev'
```

The error message showed you that pkg-config is not installed and you have to install it using your package manager.

Additional you can take a look at the changlog. You'll get the information, that now the whole make process use pkg-config. 
```
10.12.2020
==========
Makefile: make use of pkg-config
```
Closed, this report, because it is not an issue, but you can still ask your questions, here.
