### ISSUE TITLE
error decleration of parameter 

### ISSUE THREAD

**Issue by sai1122966** [ZerBea/hcxtools#181]
please help me i am getting the following errors 
    | 
make: *** No rule to make target 'hcxdumptool', needed by 'build'.  Stop.
and decleration of parameter and unused parameter

**Comment by sai1122966** [comment]
[](url)32 | typedef int  __kernel_ipc_pid_t;
      |              ^~~~~~~~~~~~~~~~~~
/usr/include/asm-generic/posix_types.h:28:14: error: declaration for parameter ‘__kernel_pid_t’ but no such parameter
   28 | typedef int  __kernel_pid_t;
      |              ^~~~~~~~~~~~~~
/usr/include/asm-generic/posix_types.h:24:22: error: declaration for parameter ‘__kernel_mode_t’ but no such parameter
   24 | typedef unsigned int __kernel_mode_t;
      |                      ^~~~~~~~~~~~~~~
/usr/include/asm-generic/posix_types.h:16:23: error: declaration for parameter ‘__kernel_ulong_t’ but no such parameter
   16 | typedef unsigned long __kernel_ulong_t;
      |                       ^~~~~~~~~~~~~~~~
/usr/include/asm-generic/posix_types.h:15:15: error: declaration for parameter ‘__kernel_long_t’ but no such parameter
   15 | typedef long  __kernel_long_t;
      |               ^~~~~~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/asm/posix_types.h:7,
                 from /usr/include/linux/posix_types.h:36,
                 from /usr/include/linux/types.h:9,
                 from /usr/include/linux/ethtool.h:18,
                 from hcxdumptool.c:18:
/usr/include/x86_64-linux-gnu/asm/posix_types_64.h:15:23: error: declaration for parameter ‘__kernel_old_dev_t’ but no such parameter
   15 | typedef unsigned long __kernel_old_dev_t;
      |                       ^~~~~~~~~~~~~~~~~~
/usr/include/x86_64-linux-gnu/asm/posix_types_64.h:12:24: error: declaration for parameter ‘__kernel_old_gid_t’ but no such parameter
   12 | typedef unsigned short __kernel_old_gid_t;
      |                        ^~~~~~~~~~~~~~~~~~
/usr/include/x86_64-linux-gnu/asm/posix_types_64.h:11:24: error: declaration for parameter ‘__kernel_old_uid_t’ but no such parameter
   11 | typedef unsigned short __kernel_old_uid_t;
      |                        ^~~~~~~~~~~~~~~~~~
In file included from /usr/include/linux/types.h:9,
                 from /usr/include/linux/ethtool.h:18,
                 from hcxdumptool.c:18:
/usr/include/linux/posix_types.h:34:13: error: declaration for parameter ‘__kernel_mqd_t’ but no such parameter
   34 | typedef int __kernel_mqd_t;
      |             ^~~~~~~~~~~~~~
/usr/include/linux/posix_types.h:33:13: error: declaration for parameter ‘__kernel_key_t’ but no such parameter
   33 | typedef int __kernel_key_t;
      |             ^~~~~~~~~~~~~~
/usr/include/linux/posix_types.h:30:16: error: declaration for parameter ‘__kernel_sighandler_t’ but no such parameter
   30 | typedef void (*__kernel_sighandler_t)(int);
      |                ^~~~~~~~~~~~~~~~~~~~~
/usr/include/linux/posix_types.h:27:3: error: declaration for parameter ‘__kernel_fd_set’ but no such parameter
   27 | } __kernel_fd_set;
      |   ^~~~~~~~~~~~~~~
In file included from /usr/include/asm-generic/types.h:7,
                 from /usr/include/x86_64-linux-gnu/asm/types.h:1,
                 from /usr/include/linux/types.h:5,
                 from /usr/include/linux/ethtool.h:18,
                 from hcxdumptool.c:18:
/usr/include/asm-generic/int-ll64.h:27:22: error: declaration for parameter ‘__u32’ but no such parameter
   27 | typedef unsigned int __u32;
      |                      ^~~~~
/usr/include/asm-generic/int-ll64.h:26:24: error: declaration for parameter ‘__s32’ but no such parameter
   26 | typedef __signed__ int __s32;
      |                        ^~~~~
/usr/include/asm-generic/int-ll64.h:24:24: error: declaration for parameter ‘__u16’ but no such parameter
   24 | typedef unsigned short __u16;
      |                        ^~~~~
/usr/include/asm-generic/int-ll64.h:23:26: error: declaration for parameter ‘__s16’ but no such parameter
   23 | typedef __signed__ short __s16;
      |                          ^~~~~
/usr/include/asm-generic/int-ll64.h:21:23: error: declaration for parameter ‘__u8’ but no such parameter
   21 | typedef unsigned char __u8;

**Comment by ZerBea** [comment]
That depend on your Linux distribution and the installed headers (build tools).
Are the kernel headers installed?
On several distributions, this headers are not installed by default.

Please comment output of:
$ uname -r
and
$ gcc --version

**Comment by sai1122966** [comment]
gcc (Debian 10.2.1-6) 10.2.1 20210110
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

5.10.0-kali2-amd64

**Comment by ZerBea** [comment]
Looking good, so far. Are the build essentials installed? 
If not:
$ sudo apt-get install build-essential

**Comment by sai1122966** [comment]
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.9).
The following packages were automatically installed and are no longer required:
  libpython-dev libpython2.7 libpython2.7-dev python2.7-dev
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
yes 
and this is comming 
make: *** No rule to make target 'hcxdumptool', needed by 'build'.  Stop.

**Comment by ZerBea** [comment]
Ok, looking good, too.
Now let's take a look at hcxdumptools surece path. It should be located in users home directory.
Please comment output of
$ pwd

It should look like sthis:
$ pwd
/home/xxxxx
where xxxxx is your username

**Comment by sai1122966** [comment]
/home/kali/

**Comment by ZerBea** [comment]
Ok.
now remove hcxdumptool folder
and do a fresh git clone:
$ git clone https://github.com/ZerBea/hcxdumptool

cd into hcxdumptool folder
cd /home/kali/hcxdumptool
and run
$ make

**Comment by ZerBea** [comment]
There is possible something wrong with your ENVIRONMENT and gcc doesn't find the required includes.

**Comment by sai1122966** [comment]
it is showinglike that

**Comment by ZerBea** [comment]
None of your includes is where we expect it. Are you running mingw?

**Comment by sai1122966** [comment]
iam running mingw64 and 32

**Comment by ZerBea** [comment]
That exactly is the problem. mingw is not supported, because hcxdumptool need direct access to the Linux kernel and the linix headers.

**Comment by sai1122966** [comment]
ok whatshould i  do know

**Comment by ZerBea** [comment]
Running hxcdumptool it is mandatory to compile and run it on a Linux system

If you run KALI - hcxdumptool should compile and run fine,(if the driver support monitor mode and packet injection)

If you KALI in a Windows VM - hcxdumptool should compile and run fine,(if the driver support monitor mode and packet injection) and the devices are looped through

If you run mingw on WIndows - no chance

**Comment by ZerBea** [comment]
Closed this issue, because it is related to mingw, but you can still ask your questions here.
