### ISSUE TITLE
radiotap header problem on mips24kc

### ISSUE THREAD

**Issue by turmsegler** [ZerBea/hcxtools#182]
Compiled for mips24kc (e.g. Pineapple Tetra MK6), hcxpcapngtool cannot extract any PSK/EAPOL information from a pcap file:

```
hcxpcapngtool --prefix=test hcxdump.pcapng
reading from hcxdump.pcapng...

summary capture file
--------------------
file name................................: hcxdump.pcapng
version (pcapng).........................: 1.0
operating system.........................: Linux 4.14.171
application..............................: hcxdumptool v19.07.3-124-gb08cd72ebc
interface name...........................: wlan1mon
interface vendor.........................: 001337
openSSL version..........................: 1.1
weak candidate...........................: 12345678
MAC ACCESS POINT.........................: 78f94496bc9b (incremented on every new client)
MAC CLIENT...............................: c022509c1fca
REPLAYCOUNT..............................: 17437374807225139200
ANONCE...................................: 5d10ca1d7e052c08b020079088057b5517730d3b8070adc7510b8cd7ecbf9fb9
SNONCE...................................: e39b4550506918b9718ea7b1639a4a201a5016278240f6b63c793274d957f604
timestamp minimum (GMT)..................: 23.12.2020 13:55:24
timestamp maximum (GMT)..................: 23.12.2020 13:55:42
used capture interfaces..................: 1
link layer header type...................: DLT_IEEE802_11_RADIO (127)
endianess (capture system)...............: little endian
packets inside...........................: 192
TACACS+ written..........................: 1
EAPOL ANONCE error corrections (NC)......: not detected
packet read error........................: 192
packet with damaged radiotap header......: 192

Warning: missing frames!
This dump file does not contain undirected proberequest frames.
An undirected proberequest may contain information about the PSK.
It always happens if the capture file was cleaned or
it could happen if filter options are used during capturing.
That makes it hard to recover the PSK.

Warning: missing frames!
This dump file does not contain important frames like
authentication, association or reassociation.
It always happens if the capture file was cleaned or
it could happen if filter options are used during capturing.
That makes it hard to recover the PSK.

Warning: missing frames!
This dump file does not contain enough EAPOL M1 frames.
It always happens if the capture file was cleaned or
it could happen if filter options are used during capturing.
That makes it impossible to calculate nonce-error-correction values.


session summary
---------------
processed pcapng files................: 1
```

I suspect an endianness problem, introduced with version 6.x.x

The error occurs with pcap files generated on the same device. Transferred to a Linux or macOS system the pcap can be read by hcxpcapngtool, and the hash information is exported into test.22000 as expected.

```
reading from hcxdump.pcapng...

summary capture file
--------------------
file name................................: hcxdump.pcapng
version (pcapng).........................: 1.0
operating system.........................: Linux 4.14.171
application..............................: hcxdumptool v19.07.2-86-g08002a1895
interface name...........................: wlan1mon
interface vendor.........................: 001337
weak candidate...........................: 12345678
MAC ACCESS POINT.........................: 00bb3ad75ca5 (incremented on every new client)
MAC CLIENT...............................: f0a2254b08e6
REPLAYCOUNT..............................: 62423
ANONCE...................................: da809f57467bb43b32610f6632a64b17e1e6ebaf336ada980713d1b48dd367b0
SNONCE...................................: 0b3d8d4d861c1d9be85124d43d0514b6f66ec2da322e22c24f5e71ea0d332012
timestamp minimum (GMT)..................: 22.12.2020 20:41:06
timestamp maximum (GMT)..................: 22.12.2020 21:41:19
used capture interfaces..................: 1
link layer header type...................: DLT_IEEE802_11_RADIO (127)
endianess (capture system)...............: big endian
packets inside...........................: 234
frames with correct FCS..................: 234
BEACON (total)...........................: 109
PROBEREQUEST.............................: 8
PROBEREQUEST (directed)..................: 3
PROBERESPONSE............................: 65
AUTHENTICATION (total)...................: 8
AUTHENTICATION (OPEN SYSTEM).............: 8
ASSOCIATIONREQUEST (total)...............: 3
ASSOCIATIONREQUEST (PSK).................: 3
REASSOCIATIONREQUEST (total).............: 1
REASSOCIATIONREQUEST (PSK)...............: 1
EAPOL messages (total)...................: 33
EAPOL RSN messages.......................: 33
ESSID (total unique).....................: 29
EAPOLTIME gap (measured maximum usec)....: 139779956
EAPOL ANONCE error corrections (NC)......: not detected
EAPOL M1 messages (total)................: 11
EAPOL M2 messages (total)................: 7
EAPOL M3 messages (total)................: 9
EAPOL M4 messages (total)................: 6
EAPOL pairs (total)......................: 21
EAPOL pairs (best).......................: 4
EAPOL pairs written to combi hash file...: 4 (RC checked)
EAPOL M32E2 (authorized).................: 4


session summary
---------------
processed pcapng files................: 1
```

**Comment by ZerBea** [comment]
You're right. That is an endianess issue and it could be related in radiatap header evaluation function.
I'll try to find the issue.

**Comment by ZerBea** [comment]
I pushed an update.
Can you please try latest git head.

**Comment by ZerBea** [comment]
There are some more endianess issues, but let's fix them step by step.

**Comment by turmsegler** [comment]
The pcap file is still recognised as captured from a LE system while in fact it comes from a BE system.

**Comment by ZerBea** [comment]
The next commit should fix the endianess error on REPLAYCOUNT.
wrong:
REPLAYCOUNT..............................: 17437374807225139200
correct:
REPLAYCOUNT..............................: 62423
Can you please test this, too:

**Comment by ZerBea** [comment]
psuhed another update. Is the capture system now detected correct?

**Comment by turmsegler** [comment]
Nope

reading from hcxdump.pcapng...

summary capture file
--------------------
file name................................: hcxdump.pcapng
version (pcapng).........................: 1.0
operating system.........................: Linux 4.14.171
application..............................: hcxdumptool v19.07.3-124-gb08cd72ebc
interface name...........................: wlan1mon
interface vendor.........................: 001337
openSSL version..........................: 1.1
weak candidate...........................: 12345678
MAC ACCESS POINT.........................: 78f94496bc9b (incremented on every new client)
MAC CLIENT...............................: c022509c1fca
REPLAYCOUNT..............................: 17437374807225139200
ANONCE...................................: 5d10ca1d7e052c08b020079088057b5517730d3b8070adc7510b8cd7ecbf9fb9
SNONCE...................................: e39b4550506918b9718ea7b1639a4a201a5016278240f6b63c793274d957f604
timestamp minimum (GMT)..................: 23.12.2020 13:55:24
timestamp maximum (GMT)..................: 23.12.2020 13:55:42
used capture interfaces..................: 1
link layer header type...................: DLT_IEEE802_11_RADIO (127)
endianess (capture system)...............: little endian
packets inside...........................: 192
TACACS+ written..........................: 1
EAPOL ANONCE error corrections (NC)......: not detected
packet read error........................: 192
packet with damaged radiotap header......: 192

Warning: missing frames!
This dump file does not contain undirected proberequest frames.
An undirected proberequest may contain information about the PSK.
It always happens if the capture file was cleaned or
it could happen if filter options are used during capturing.
That makes it hard to recover the PSK.

Warning: missing frames!
This dump file does not contain important frames like
authentication, association or reassociation.
It always happens if the capture file was cleaned or
it could happen if filter options are used during capturing.
That makes it hard to recover the PSK.

Warning: missing frames!
This dump file does not contain enough EAPOL M1 frames.
It always happens if the capture file was cleaned or
it could happen if filter options are used during capturing.
That makes it impossible to calculate nonce-error-correction values.


session summary
---------------
processed pcapng files................: 1

> On 4. Feb 2021, at 17:12, ZerBea <notifications@github.com> wrote:
> 
> 
> psuhed another update. Is the capture system now detected correct?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

_________________________________

Benjamin Stein
bjs@ivorix.com

**Comment by turmsegler** [comment]
Testing next commit ... The build cycles is rather slow ...

**Comment by ZerBea** [comment]
No problem. It will take some more steps until we find the exact issue.

**Comment by turmsegler** [comment]
Still same output

**Comment by ZerBea** [comment]
I discovered also an endianess issue in hcxdumptool and fixed it.

**Comment by turmsegler** [comment]
Can we test that seperately?

**Comment by ZerBea** [comment]
No, because both issues depend on each other.

**Comment by ZerBea** [comment]
Can you please send my an example cap file from the BE system?

**Comment by turmsegler** [comment]
Shouldn't we take that to private?

**Comment by ZerBea** [comment]
Yes, please send me an email, I can respond to.

**Comment by turmsegler** [comment]
Ping bjs@ivorix.com. I'll delete this later

**Comment by ZerBea** [comment]
Issue should be solved by latest commit:
https://github.com/ZerBea/hcxtools/commit/e775b0271aad52ceda70050ad3f89cb59b15c792
