### ISSUE TITLE
hcxtools 6.1.6 fails to build with libressl

### ISSUE THREAD

**Issue by buzzdeee** [ZerBea/hcxtools#184]
Hi,

I'm on a OpenBSD -current with libressl, wanted to update from 6.1.5 to 6.1.6. Now hcxtools fails to build:
```
cc -O2 -pipe -g -O0 -std=gnu99   -I/usr/local/include -MMD -MF .deps/hcxpcapngtool.d -o hcxpcapngtool hcxpcapngtool.c  -lssl -lcrypto  -lz -L/usr/local/lib -DVERSION_TAG=\"6.1.6\" -DVERSION_YEAR=\"2021\"
hcxpcapngtool.c:1983:9: warning: implicit declaration of function 'EVP_PKEY_new_CMAC_key' is invalid in C99 [-Wimplicit-function-declaration]
        pkey = EVP_PKEY_new_CMAC_key(NULL, testptk, 16, EVP_aes_128_cbc());
               ^
hcxpcapngtool.c:1983:7: warning: incompatible integer to pointer conversion assigning to 'EVP_PKEY *' (aka 'struct evp_pkey_st *') from 'int' [-Wint-conversion]
        pkey = EVP_PKEY_new_CMAC_key(NULL, testptk, 16, EVP_aes_128_cbc());
             ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 warnings generated.
ld: error: undefined symbol: EVP_PKEY_new_CMAC_key
>>> referenced by hcxpcapngtool.c:1983
>>>               /tmp/hcxpcapngtool-af12de.o:(testeapolpmk)
cc: error: linker command failed with exit code 1 (use -v to see invocation)
gmake: *** [Makefile:116: hcxpcapngtool] Error 1
*** Error 2 in . (/home/ports/infrastructure/mk/bsd.port.mk:2938 '/home/ports/pobj/amd64/hcxtools-6.1.6/.build_done': @cd /home/ports/pobj/a...)
*** Error 2 in /home/ports/security/hcxtools (/home/ports/infrastructure/mk/bsd.port.mk:2593 'all': @lock=hcxtools-6.1.6;  export _LOCKS_HEL...)

```

**Comment by ZerBea** [comment]
hcxdumptool and hcxtools moved to new OpenSSL API (>= v 1.1.1):
https://www.openssl.org/docs/manmaster/man3/EVP_PKEY_new.html
I recommend to create a feature request/issue report on libressl to add "EVP_PKEY_new_CMAC_key" function
https://github.com/libressl-portable/

**Comment by ZerBea** [comment]
Please notice:
OpenSSL is the standard crypto library on Arch Linux. It is required by 379 tools:
https://archlinux.org/packages/core/x86_64/openssl/

LibreSSL is not standard on Arch Linux. It is required by 2 tools, only:
https://archlinux.org/packages/community/x86_64/libressl/

**Comment by ZerBea** [comment]
I have a real good reason to recommend the use of OpenSSL:
```
Requirements
--------------
* Linux (recommended Arch Linux, but other distros should work, too (no support for other distributions).
* gcc 10 recommended (deprecated versions are not supported: https://gcc.gnu.org/)
* libopenssl and openssl-dev installed
* librt and librt-dev installed (should be installed by default)
* zlib and zlib-dev installed (for gzip compressed cap/pcap/pcapng files)
* libcurl and curl-dev installed (used by whoismac and wlancap2wpasec)
* libpthread and pthread-dev installed (used by hcxhashcattool)
* pkg-config installed
To install requirements on Kali use the following 'apt-get install pkg-config libcurl4-openssl-dev libssl-dev zlib1g-dev'
```

BTW:
I tested several crypto libraries. They are either too slow or they don't provide the mandatory functions, e.g:
https://github.com/ZerBea/hcxtools/issues/106#issuecomment-775822827
https://github.com/wolfSSL/wolfssl/issues/3790

**Comment by buzzdeee** [comment]
Hi,

I'm on OpenBSD, and libressl comes with the base installation. 
OpenSSL 1.11j is available as package, so I can make hcxtools dependent on that until the missing function(s) are available in libressl.

thanks,
Sebastian

**Comment by ZerBea** [comment]
That is a good solution, because I decide to add more crypto functions to hcxtools/hcxdumptool in the near future,
But I also recommend to add a feature request to LibreSSL, because the developer claim to be full compatible with OpenSSL.
 
I'm still looking for a small and fast crypto library - however I haven't found it, yet.

**Comment by buzzdeee** [comment]
sure will add a feature request to libressl.

however, just trying to build against openssl 1.1.1j seems to get me further, however, the 6.1.6 version of hcxtools also seem to use some GNU extensions in libc that is not available on all OS:

so it next fails to build this way:

```
cc -O2 -pipe -g -O0 -std=gnu99  -I/usr/local/include/eopenssl11 -I/usr/local/include -MMD -MF .deps/hcxpmktool.d -o hcxpmktool hcxpmktool.c  -lssl -lcrypto -L/usr/local/lib/eopenssl11 -L/usr/local/lib -DVERSION_TAG=\"6.1.6\" -DVERSION_YEAR=\"2021\"
hcxpmktool.c:440:16: warning: implicit declaration of function 'strdupa' is invalid in C99 [-Wimplicit-function-declaration]
hashlinedupa = strdupa(hashlinestring);
               ^
hcxpmktool.c:440:14: warning: incompatible integer to pointer conversion assigning to 'char *' from 'int' [-Wint-conversion]
hashlinedupa = strdupa(hashlinestring);
             ^ ~~~~~~~~~~~~~~~~~~~~~~~
2 warnings generated.
ld: error: undefined symbol: strdupa
>>> referenced by hcxpmktool.c:440
>>>               /tmp/hcxpmktool-e0950f.o:(gethashlinefields)
>>> did you mean: strdup
>>> defined in: /usr/bin/../lib/libc.so.96.0
cc: error: linker command failed with exit code 1 (use -v to see invocation)

```

**Comment by ZerBea** [comment]
Please give me some minutes to think about a fix.

**Comment by ZerBea** [comment]
Please try latest commit:
replaced strdupa() by strndup()

**Comment by buzzdeee** [comment]
thank you, now all builds fine with it

**Comment by ZerBea** [comment]
Glad to hear that.
Looks like I have to take a closer look into the crypto part (e.g. using MD5, SHA1 AES and HMAC functions from hashcat directly instead depending on a library). But that has no high priority.
Absolutely high priority is to identify a weak point within SAE (WPA3) AUTHENTICATION.

**Comment by buzzdeee** [comment]
I got a patch from libressl dev implemnting EVP_PKEY_new_CMAC_key
in order to test, I'd need some pcap for testing it, I think it would need a WPA2 key version 3

do you by any chance have test pcaps?

**Comment by ZerBea** [comment]
Please send me an EMAIL, I can reply to.
You can get my address via git API:
https://api.github.com/users/ZerBea/events/public
