### ISSUE TITLE
hcxhashtool filterlist -request

### ISSUE THREAD

**Issue by ChemicalNRG** [ZerBea/hcxtools#185]
Can you add a filter option for hcxhashtool with an PMKID / .22000 file as filter?
So for instance when i have done a whole PMKID file with Pegatron PMKID's [0-9] len9, the ones that are cracked are in the potfile and will be skipped, but after a new scan it could be that the ones that i allready tried are processed again.

So what i want to do is use the --left function from hashcat after the (first) Pegatron file is processed and somehow use that as a filter on a new Pegatron PMKID file after a new scan.

I understand this will complicate the meaning of filter in hcxhashtool because the other filters are for including hashes so maybe a better word for this particular goal is skiplist.
The same code could be used to make a filterlist for hcxdumptool with the hashcat potfile as input, or hashcat --show.

**Comment by ZerBea** [comment]
I don't understand this request, because hashcat will remove (hashcat --remove) all entries from a 22000 hash file of which a PSK is recovered.

Do do this by hand, you can use bash tools (e.g. diff):
```
diff $old.22000 $cleaned.22000 | grep '^>' | sed -e 's/> //' > remaining.22000
```
You can do this on every field of a 22000 hashline, hashcat outfile (-o) or hascat potfile using "awk".

Also please notice that PMKIDs are not unique for a NETWORK:
https://hashcat.net/forum/thread-9932-post-51925.html#pid51925
They depend on MAC_AP and MAC_CLIENT.
In case of hcxdumptool attack vector, both of them can be randomized. That will result in a new PMKID.

**Comment by ChemicalNRG** [comment]
Yes, only when they are recovered. The point is, by using --left i can make a list of PMKID's or MAC's as you point out, that have not a password with given keyspace.
So what i mean is, after cracking, the ones that are not recovered don't use the vendor keyspace.
I allready make a 22000 file to use that for other wordlists, so that could be perfect to substract mac adresses from as a skiplist for the next time i use --vendor=PEGATRON and that scan has some mac adresses that are allready known to not using the default password

**Comment by ZerBea** [comment]
Ok, that make it a little bit more clear.
Please give me a sample line of the skiplist:
2021-03-08_NO-VENDOR-PASS.22000

**Comment by ChemicalNRG** [comment]
that's correct.
2021-03-08_NO-VENDOR-PASS.22000 is just hashcat --left output, so basically the same as hcxhashtool output.

2021-03-08_NO-VENDOR-PASS-MACS.txt = 2021-03-08_NO-VENDOR-PASS.22000 | cut -d* -f4 | sort -u

**Comment by ZerBea** [comment]
Ok, let me think about how to add this....

**Comment by ZerBea** [comment]
Please test latest commit:
https://github.com/ZerBea/hcxtools/commit/75d50edd2cb8bd944acd695ecb5d2e1399952572

Added new option:
```
--mac-skiplist=<file>        : exclude MAC from file
                               format: 001122334455, 00:11:22:33:44:55, 00-11-22-33-44-55 (hex)
```

**Comment by rank1Seeker** [comment]
Flag '--mac-skiplist' doesn't work/is bugged or broken after commit with some other commit.
I've lost 5 hours on this meaning that I've been missing something very obvious.

`$ hcxhashtool -i A.hc22000 --info=stdout | grep $_SSID_TO_GET_RID_OF---AND_IT_RELATED_DATA`
    Returned 4 entries, each with different client's MAC

All above 4 entries have same AP's MAC, so:
`$ echo 009911b62003 > exclude_APs.txt`

`$ hcxhashtool -i A.hc22000 --info=stdout --mac-skiplist=exclude_APs.txt | grep $_SSID_TO_GET_RID_OF---AND_IT_RELATED_DATA`
    Returned SAME 4 entries, each with different client's MAC
    **Meaning '--mac-skiplist' doesn't work**

Even worse:
`$ hcxhashtool -i A.hc22000 --mac-skiplist=exclude_APs.txt -o B.hc22000`

Sizes:
    A.hc22000 is  4 KB
    B.hc22000 is 18 KB  ?!?!


PS: I've made it simpler by using only 1 AP's MAC, but I want to use 2.
After fix, document how should MACs be separated, delimited by which char(s).

**Comment by ZerBea** [comment]
`$ hcxhashtool -i A.hc22000 --info=stdout --mac-skiplist=exclude_APs.txt`
Please take a look at  --help:
```
--info=stdout                : stdout output detailed information about content of hash file
                               no filter options available
```
Main purpose of "--info=stdout " is to get an overview of the content of the entire hash file:

`$ hcxhashtool -i A.hc22000 --mac-skiplist=exclude_APs.txt -o B.hc22000`

Is a bug, I'll hunt for the cause.

**Comment by rank1Seeker** [comment]
While testing, I have never used `--info=stdout` **during filtering**.
Locally, I've used it on A file **before filtering** to see a status **and** afterwards on B file **after filtering** to see what it became, what was the output status.

Here I just wanted to show a point by being more verbose with `--info=stdout`,  but yes It mustn't be used with filter as it negates it.
Maybe to implement a warning for users using incompatible flags ...

**Comment by ZerBea** [comment]
Second one should be fixed by this commit:
https://github.com/ZerBea/hcxtools/commit/476c5c6ed9bb861c3da9c2ea4a2bf839d1fe545d
```
$ wc in.22000
  185   185 60354 in.22000

$ wc filter
 2  2 26 filter

$ hcxhashtool -i in.22000 --mac-skiplist=filter -o out.22000
78f9448fea3d 78f9448fea3d
ec84b47bb682 ec84b47bb682

OUI information file..........: /home/zerobeat/.hcxtools/oui.txt
OUI entries...................: 34539
total lines read..............: 185
valid hash lines..............: 185
PMKID hash lines..............: 45
EAPOL hash lines..............: 138
PMKID written.................: 46
EAPOL written.................: 137

$ wc out.22000
  183   183 59876 out.22000
```

**Comment by rank1Seeker** [comment]
Thank you for your effort!

### Build:
```
$ cd && git clone https://github.com/ZerBea/hcxtools.git && cd hcxtools
$ sudo apt install libssl-dev libcurl4-openssl-dev
$ make
```

### Use:
For simplicity set just 1 AP's MAC
`$ echo 009911b62003 > exclude_APs.txt`

```
$ ~/hcxtools/hcxhashtool -i A.hc22000 --mac-skiplist=exclude_APs.txt -o B.hc22000
$ ~/hcxtools/hcxhashtool -i B.hc22000 --info=stdout > FILTERED.txt
```
```
$ grep -i `cat exclude_APs.txt` FILTERED.txt
```

**Failure as output exists, meaning excluded AP is still in B.hc22000 and B.hc22000 is over 5 times bigger then A.hc22000**

**Comment by ZerBea** [comment]
I can't reproduce that:
```
$ rm  B.hc22000
$ echo 00b67167a181 > exclude_APs.txt
$ hcxhashtool -i A.hc22000 --mac-skiplist=exclude_APs.txt -o B.hc22000

OUI information file..........: /home/zerobeat/.hcxtools/oui.txt
OUI entries...................: 34539
total lines read..............: 185
valid hash lines..............: 185
PMKID hash lines..............: 46
EAPOL hash lines..............: 138
PMKID written.................: 46
EAPOL written.................: 138

$ wc A.hc22000
  185   185 60354 A.hc22000

$ wc B.hc22000
  184   184 60270 B.hc22000
```
Successful filtered out.


Please note:
All hcxtools append results to existing files:
```
$ hcxhashtool -i A.hc22000 --mac-skiplist=exclude_APs.txt -o B.hc22000

OUI information file..........: /home/zerobeat/.hcxtools/oui.txt
OUI entries...................: 34539
total lines read..............: 185
valid hash lines..............: 185
PMKID hash lines..............: 46
EAPOL hash lines..............: 138
PMKID written.................: 46
EAPOL written.................: 138

$ wc B.hc22000
   368    368 120540 B.hc22000
```
If you run hcxhashtool 5 time on the same output file it will grow up.

That is mentioned in README.md:
```
Notice
--------------
Most output files will be appended to existing files (with the exception of pcapng, pcap, cap files).
```

**Comment by rank1Seeker** [comment]
I've been running hcxhashtool for those 2 days on the same input and output files.

Using **rm** on **-o file** _fixed a thing._

However, I believe that this kind of behavior, **with filters is unacceptable.**
Let's say -i file contains APs: A, B, C, ..., F.
First time I remove A from -i file into -o file, which now has APs: B to F and is smaller in size then -i file.

And here any **additional filtering ends...**
Each subsequent desire to remove any additional APs from -i file, like previous A, and new B and C to -o file will fail in a way that:

1.  A remains absent
2. B and C won't be filtered, but just prevented from being duplicated
3. D to F will be duplicated

At least issue a warning that **-o file** exists.

**Comment by ZerBea** [comment]
I don't want to reinvent the wheel twice because hcxhashtool is a supplement to bash tools (comm, diff , sort, uniq) and to hashcat.
There is no need to do this in hcxhashtool.
```
hashcat removes duplicate entries
sort | uniq removes duplicate entries
```
To draw a conclusion. After the commit, the filter option is working as expected:
`First time I remove A from -i file into -o file, which now has APs: B to F and is smaller in size then -i file.`

Second time it doesn't work because because you have not cleaned your working directory.
That looks like a problem in your work flow.

`At least issue a warning that -o file exists.`
No, because that is a wanted behavior, which is mentioned in README.md: All hcxtools append output to existing files.
If that's undesirable it is mandatory to clean up the working directory.

**Comment by rank1Seeker** [comment]
Ok, thanks for your effort and future guidelines.

**Comment by ZerBea** [comment]
Mostly hcxtools are designed to be used by scripts in combination with bash tools and hashcat/JtR.
Once this has been done (e,g, build an environment that contain  scripts tailored to the task which run hcxtools in background), everything should be fine.
None of the tools should be an "every purpose" tool like an "egg-laying, milk-bearing woolly sow".
