### ISSUE TITLE
v6.1.6 build failure on macOS

### ISSUE THREAD

**Issue by carlocab** [ZerBea/hcxtools#186]
Building hcxtools 6.1.6 fails on macOS (10.14, 10.15, and 11.2), with the following error during `make install`:

```
Undefined symbols for architecture x86_64:
  "_strdupa", referenced from:
      _gethashlinefields in hcxpmktool-425d48.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

We use Clang (the system compiler) to build but using GCC doesn't help, and results in the same error. Build logs available at https://github.com/Homebrew/homebrew-core/actions/runs/681138907.

Related: https://github.com/Homebrew/homebrew-core/pull/73783

**Comment by ZerBea** [comment]
That issue was fixed by this commit 9 days ago:
https://github.com/ZerBea/hcxtools/commit/f592df4bd1bfcc4ade8e6396587fd27dc8f154f5

Please try latest git head.

**Comment by carlocab** [comment]
Thanks; that works. We only build off tagged releases, but I can apply the patch from that commit.

**Comment by ZerBea** [comment]
After a short test period (usually a month after the last release), I'll release the new version.

**Comment by ZerBea** [comment]
The test period is mandatory to make sure we got all show stoppers.
