### ISSUE TITLE
There is no Output file with hcxpcaptool?

### ISSUE THREAD

**Issue by k0uba** [ZerBea/hcxtools#187]
![IMG_20210419_230434.jpg](https://user-images.githubusercontent.com/81297161/115309267-ef169180-a163-11eb-9d09-f6e5a24d7f6a.jpg)

**Comment by ZerBea** [comment]
Three possibilities:
1. the dump file doesn't contain  a valid PMKID or EAPOL messagepair (so nothing will be written to a hash file)
2. your command line is wrong (nothing will be written to a hash file)
3. you're running an old version of the tool (update to latest version: 6.1.6)

To find out, what exactly went wrong, please add the commandline that you used.
Additional it would help if you add the pacapng file, too.

BTW:
I assume possibility 1 (no usefull PMKID and no EAPOL message pair inside your dumpfile)
and I assume possibility 3 (the shown status out belong to an old version).
The same applies to your version of hcxdumptool (6.0.5)

**Comment by ZerBea** [comment]
Please update to latest version 
$ hcxpcapngtool -v
hcxpcapngtool 6.1.6-7-g75d50ed (C) 2021 ZeroBeat
$ hcxdumptool -v
hcxdumptool 6.1.6-16-g9e79c3f (C) 2021 ZeroBeat
and reopen issue, if it still exist.

hcxpcaptool is deprecated and was removed by version 6.1.2:
```
04.09.2020
==========
removed deprecated hcxpcaptool - use hcxpcapngtool instead
```
