### ISSUE TITLE
How to use hcxpsktool

### ISSUE THREAD

**Issue by nxfxcom** [ZerBea/hcxtools#192]
Hello,

based on the -h options hcxpsktool seems like a ideal first step and I love the workflow outline. Are there any examples? Want to use it with hashcat! I feel like I am missing a link or something ;)

Thank you

**Comment by ZerBea** [comment]
hcxpsktool calculate PSKs based on selected options and/or content of hash file (BSSID and/or ESSID).
It should be the second step to recover a weak PSK.
Here are some examples:

$ hcxpsktool <options> -o psk.list
$ hashcat -m 22000 hash.22000 psk.list

or
$ hcxpsktool <options>  |  hashcat -m 22000 hash.22000

or
$ hcxpsktool -c  hash.22000 |  hashcat -m 22000 hash.22000

or every combination of this.

Depending on the options, hcxpsktool will calculate an entire possible key space.
If the PSK default algo is known, you can use RKG to recover the PSK:
https://github.com/routerkeygen/routerkeygenPC


But in every case, hcxpcapngtool -E option should be your first step:
$ hcxpcapngtool - E psk.list -o hash.22000 dumpfile.pcapng
$ hashcat -m 22000 hash.22000 psk.list

**Comment by ZerBea** [comment]
Closed, because it is not an issue.
