### ISSUE TITLE
[Feature Request] Better vendor filtering in hcxhashtool

### ISSUE THREAD

**Issue by Chick3nman** [ZerBea/hcxtools#195]
Currently, you can filter by vendor name for APs using --vendor= and a partial vendor name. There is not currently an easy way to filter by client vendor without selecting a single OUI. Being able to filter by AP and/or Client vendor would be helpful for filtering out devices like cellphones which could be AP(hotspot) or Client. 

On top of being able to filter by client, case insensitivity or possibly regex search would be amazing, but is definitely above and beyond. Some vendors have multiple different spellings or capitalization in the lookup table which can make filtering by that vendor a bit problematic.

If i get some time before anyone gets to this, i'll take a shot at adding it and submitting a PR. Haven't looked too closely at the code but i figure it it wouldn't be too hard to learn my way around  it.

**Comment by ZerBea** [comment]
By latest commit:
https://github.com/ZerBea/hcxtools/commit/bd5bf3ddc3c1e35b6e202bad149b760a5ba14724
we have some additional info options to retrieve VENDOR names from the hash file.
```
--info-vendor=<file>         : output detailed information about ACCESS POINT and CLIENT VENDORs
                               not in combination with --vendor, --vendor-ap or --vendor-client
--info-vendor-ap=<file>      : output detailed information about ACCESS POINT VENDORs
                               not in combination with --vendor, --vendor-ap or --vendor-client
--info-vendor-CLIENT=<file>  : output detailed information about ACCESS POINT VENDORs
                               not in combination with --vendor, --vendor-ap or --vendor-client
--info-vendor=stdout         : stdout output detailed information about ACCESS POINT and CLIENT VENDORs
                               not in combination with --vendor, --vendor-ap or --vendor-client
--info-vendor-ap=stdout      : stdout output detailed information about ACCESS POINT VENDORs
                               not in combination with --vendor, --vendor-ap or --vendor-client
--info-vendor-CLIENT=stdout  : stdout output detailed information about ACCESS POINT VENDORs
                               not in combination with --vendor, --vendor-ap or --vendor-client
```

**Comment by Chick3nman** [comment]
Awesome, that does everything i wanted, thanks :)

**Comment by ZerBea** [comment]
Glad to heart this. If you need more analysis options, please let me know.
