### ISSUE TITLE
convert from Bettercap pcap file to hashcat format 

### ISSUE THREAD

**Issue by slavadba** [ZerBea/hcxtools#205]
HI,
I have pcap file from Bettercap - but I cant convert it to hashcat format.

bettercap -version
bettercap v2.32.0 (built for linux amd64 with go1.15.15)

┌──(root💀kali)-[~]
└─#

hcxpcapngtool -o wpa_from_bettercap wpa.pcap
hcxpcapngtool 6.2.5-26-gb98b7ba reading from wpa.pcap...

summary capture file
file name................................: wpa.pcap
version (pcap/cap).......................: 2.4 (very basic format without any additional information)
timestamp minimum (GMT)..................: 05.03.2022 18:25:39
timestamp maximum (GMT)..................: 05.03.2022 18:25:39
used capture interfaces..................: 1
link layer header type...................: DLT_IEEE802_11_RADIO (127)
endianess (capture system)...............: little endian
packets inside...........................: 4
frames with correct FCS..................: 4
packets received on 2.4 GHz..............: 4
EAPOL messages (total)...................: 4
EAPOL RSN messages.......................: 4
EAPOLTIME gap (measured maximum usec)....: 2955
EAPOL ANONCE error corrections (NC)......: not detected
EAPOL M1 messages (total)................: 1
EAPOL M2 messages (total)................: 1
EAPOL M3 messages (total)................: 1
EAPOL M4 messages (total)................: 1
EAPOL pairs (total)......................: 2

Information: no hashes written to hash files

Information: limited dump file format detected!
This file format is a very basic format to save captured network data.
It is recommended to use PCAP Next Generation dump file format (or pcapng for short) instead.
The PCAP Next Generation dump file format is an attempt to overcome the limitations
of the currently widely used (but limited) libpcap (cap, pcap) format.
https://www.wireshark.org/docs/wsug_html_chunked/AppFiles.html#ChAppFilesCaptureFilesSection
https://github.com/pcapng/pcapng

Warning: missing frames!
This dump file does not contain undirected proberequest frames.
An undirected proberequest may contain information about the PSK.
It always happens if the capture file was cleaned or
it could happen if filter options are used during capturing.
That makes it hard to recover the PSK.

Warning: missing frames!
This dump file does not contain important frames like
authentication, association or reassociation.
It always happens if the capture file was cleaned or
it could happen if filter options are used during capturing.
That makes it hard to recover the PSK.

Warning: missing frames!
This dump file does not contain enough EAPOL M1 frames.
It always happens if the capture file was cleaned or
it could happen if filter options are used during capturing.
That makes it impossible to calculate nonce-error-correction values.

session summary
processed cap files...................: 1

┌──(root💀kali)-[~/DISTR/hcxdumptool]
└─#

Are there any ways to do this?

**Comment by ZerBea** [comment]
Can you please add the pcap file?

**Comment by ZerBea** [comment]
To convert a 4way handshake to a valid hash file accepted by hash cat, we need:
ESSID
EAPOL M1 replay counter value x
EAPOL M2 replay counter value x
EAPOL M3 replay counter value x +1
EAPOL M4 replay counter value x +1  (not mandatory)

The EAPOL messages must be transmitted within a defined time gap
default:
```
--eapoltimeout=<digit>             : set EAPOL TIMEOUT (milliseconds)
                                   : default: 5000 ms

```
https://community.cisco.com/t5/wireless-mobility-documents/eap-timers-on-wireless-lan-controllers/ta-p/3122477

If all is true, the 4way handshake will be converted.

Here is an example:
`$ tshark -r dumpfile.pcap -T fields -e frame.number -e _ws.col.Time -e wlan.ta -e wlan.sa -e wlan_rsna_eapol.keydes.msgnr -e eapol.keydes.replay_counter
3	10:20:27,782488	34:81:c4:2a:e4:37	34:81:c4:2a:e4:37	1	1
4	10:20:27,791488	b0:c0:90:a0:4f:13	b0:c0:90:a0:4f:13	2	1
5	10:20:27,794368	34:81:c4:2a:e4:37	34:81:c4:2a:e4:37	3	2
6	10:20:27,797487	b0:c0:90:a0:4f:13	b0:c0:90:a0:4f:13	4	2
`
EAPOL MESSAGE M1 replay counter 1
EAPOL MESSAGE M2 replay counter 1
EAPOL MESSAGE M3 replay counter 2
EAPOL MESSAGE M4 replay counter 2

EAPOL TIME < default eapoltimeout

hcxpcapngtool will convert this handshake!


The 4way handshake is explained here:
https://www.wifi-professionals.com/2019/01/4-way-handshake

**Comment by ZerBea** [comment]
I think, I found it:
Your pcap file contain 4 packets:
packets inside...........................: 4
This are the 4 EAPOL MESSAGES (M!, M2, M3, M4)
EAPOL M1 messages (total)................: 1
EAPOL M2 messages (total)................: 1
EAPOL M3 messages (total)................: 1
EAPOL M4 messages (total)................: 1

Unfortunately the ESSID information (mandatory for PBKDF2) is missing to calculate a PMK:
PMK = PBKDF2(HMAC−SHA1, PSK, ESSID, 4096, 256)
There is no BEACON, no PROBERESPONSE, no ASSOCIATIONREQUEST/REASSOCIATIONREQUEST packet inside your pcap file from which we can take the ESSID.

The conditions are not met to convert the file to a hash file.

We can close this here, because this it not related to hcxpcapngtool.

**Comment by ZerBea** [comment]
By latest commit:
https://github.com/ZerBea/hcxtools/commit/4d5cbd37c67e723a645182618152cb7ff693315b

I added an information if BEACON or PROBERESPONSE frames are missing:
```
$ git add hcxpcapngtool.c
fatal: Kein Git-Repository (oder irgendein Elternverzeichnis bis zum Einhängepunkt /)
Stoppe bei Dateisystemgrenze (GIT_DISCOVERY_ACROSS_FILESYSTEM nicht gesetzt).
[zerobeat@tux1 temp]$ hcxpcapngtool -o test.22000 test.pcap
hcxpcapngtool 6.2.5-34-g4d5cbd3 reading from test.pcap...

summary capture file
--------------------
file name................................: test.pcap
version (pcap/cap).......................: 2.4 (very basic format without any additional information)
timestamp minimum (GMT)..................: 18.07.2017 03:38:42
timestamp maximum (GMT)..................: 18.07.2017 03:38:42
used capture interfaces..................: 1
link layer header type...................: DLT_IEEE802_11 (105) very basic format without any additional information about the quality
endianess (capture system)...............: little endian
packets inside...........................: 4
EAPOL messages (total)...................: 4
EAPOL RSN messages.......................: 4
EAPOLTIME gap (measured maximum usec)....: 2039
EAPOL ANONCE error corrections (NC)......: not detected
EAPOL M1 messages (total)................: 1
EAPOL M2 messages (total)................: 1
EAPOL M3 messages (total)................: 1
EAPOL M4 messages (total)................: 1
EAPOL pairs (total)......................: 2

Information: no hashes written to hash files

Information: limited dump file format detected!
This file format is a very basic format to save captured network data.
It is recommended to use PCAP Next Generation dump file format (or pcapng for short) instead.
The PCAP Next Generation dump file format is an attempt to overcome the limitations
of the currently widely used (but limited) libpcap (cap, pcap) format.
https://www.wireshark.org/docs/wsug_html_chunked/AppFiles.html#ChAppFilesCaptureFilesSection
https://github.com/pcapng/pcapng

Information: radiotap header is missing!
Radiotap is a de facto standard for 802.11 frame injection and reception.
The radiotap header format is a mechanism to supply additional information about frames,
from the driver to userspace applications.
https://www.radiotap.org/

Information: missing frames!
This dump file does not contain BEACON or PROBERESPONSE frames.
This frames contain the ESSID which is mandatory to calculate a PMK.
It always happens if the capture file was cleaned or
it could happen if filter options are used during capturing.
That makes it impossibleto recover the PSK.

Information: missing frames!
This dump file does not contain undirected proberequest frames.
An undirected proberequest may contain information about the PSK.
It always happens if the capture file was cleaned or
it could happen if filter options are used during capturing.
That makes it hard to recover the PSK.

Information: missing frames!
This dump file does not contain important frames like
authentication, association or reassociation.
It always happens if the capture file was cleaned or
it could happen if filter options are used during capturing.
That makes it hard to recover the PSK.

Information: missing frames!
This dump file does not contain enough EAPOL M1 frames.
It always happens if the capture file was cleaned or
it could happen if filter options are used during capturing.
That makes it impossible to calculate nonce-error-correction values.


session summary
---------------
processed cap files...................: 1
```

**Comment by ZerBea** [comment]
To answer your question: "Are there any ways to do this?"
No, your pcap file is garbage!

**Comment by ZerBea** [comment]
To imagine what your dump file (pcap) is missing, this is the information collected by hcxdumptool:
```
$ hcxpcapngtool -o demo.hc22000 demo.pcapng
hcxpcapngtool 6.2.5-34-g4d5cbd3 reading from demo.pcapng...

summary capture file
--------------------
file name................................: demo.pcapng
version (pcapng).........................: 1.0
operating system.........................: Linux 5.10.83-1-rpi-legacy-ARCH
application..............................: hcxlabtool 1.0.0
interface name...........................: wlan0
interface vendor.........................: 74da38
openSSL version..........................: 1.1
weak candidate...........................: 12345678
MAC ACCESS POINT.........................: 78f9440d6ae2 (incremented on every new client)
MAC CLIENT...............................: c8aacc9c0d43
REPLAYCOUNT..............................: 65101
ANONCE...................................: ca3c997336d12663a8315ff35c9c2c242e087761ec9ee86b029c456c145664b7
SNONCE...................................: 5291161af17136d77f8a298a8435da7660477b2db21382919c6210210a41f992
timestamp minimum (GMT)..................: 23.02.2022 19:33:44
timestamp maximum (GMT)..................: 23.02.2022 23:44:58
used capture interfaces..................: 1
link layer header type...................: DLT_IEEE802_11_RADIO (127)
endianess (capture system)...............: little endian
packets inside...........................: 46605
packets received on 2.4 GHz..............: 42558
WIRELESS DISTRIBUTION SYSTEM.............: 82
ESSID (total unique).....................: 3446
BEACON (total)...........................: 2732
BEACON (detected on 2.4 GHz channel).....: 11 
BEACON (SSID wildcard/unset).............: 180
BEACON (SSID zeroed).....................: 52
ACTION (total)...........................: 117
ACTION (containing ESSID)................: 9
PROBEREQUEST.............................: 1486
PROBEREQUEST (directed)..................: 29
PROBERESPONSE (total)....................: 2726
PROBERESPONSE (SSID unset)...............: 11
PROBERESPONSE (SSID zeroed)..............: 110
AUTHENTICATION (total)...................: 933
AUTHENTICATION (OPEN SYSTEM).............: 933
ASSOCIATIONREQUEST (total)...............: 1807
ASSOCIATIONREQUEST (PSK).................: 1803
REASSOCIATIONREQUEST (total).............: 2306
REASSOCIATIONREQUEST (PSK)...............: 2302
EAP (total)..............................: 2
EAP CODE request.........................: 2
EAP ID...................................: 2
EAPOL messages (total)...................: 26379
EAPOL RSN messages.......................: 26364
EAPOL WPA messages.......................: 15
EAPOLTIME gap (measured maximum usec)....: 131966495
EAPOL ANONCE error corrections (NC)......: working
REPLAYCOUNT gap (suggested NC)...........: 65164
EAPOL M1 messages (total)................: 23110
EAPOL M2 messages (total)................: 2576
EAPOL M3 messages (total)................: 498
EAPOL M4 messages (total)................: 195
EAPOL pairs (total)......................: 3511
EAPOL (from zeroed PMK)..................: 11
EAPOL pairs (best).......................: 170
EAPOL ROGUE pairs........................: 108
EAPOL pairs written to 22000 hash file...: 170 (RC checked)
EAPOL M12E2 (challenge)..................: 129
EAPOL M32E2 (authorized).................: 39
EAPOL M34E4 (authorized).................: 2
PMKID (useless)..........................: 51
PMKID (total)............................: 1371
PMKID (from zeroed PMK)..................: 6
PMKID (best).............................: 54
PMKID ROGUE..............................: 45
PMKID written to 22000 hash file.........: 54


session summary
---------------
processed pcapng files................: 1
```

It contain much more useful information than your four packet pcap file.
