### ISSUE TITLE
pmkid on WPA3 NETWORKs not recognized

### ISSUE THREAD

**Issue by LLH-l** [ZerBea/hcxtools#218]
pmkid not recognized
it should contain pmkid

[pmkid not recognized.zip](https://github.com/ZerBea/hcxtools/files/9204933/pmkid.not.recognized.zip)

**Comment by ZerBea** [comment]
There is no PMKID inside hashcat, is able to crack - so no PMKID is converted.
The AP is running WPA2/WPA3 transition mode (so called mixed mode).
The CLIENTs connecting to the AP in WPA2 mode do not use a PMKID, while the CLIENTc connecting to the AP in WPA3 mode use a PMKID. This PMKID is not crackable by hashcat!!!!

Please take a look at packet 18405:
Client ac764ce7d2a3 ASSOCIATE with a AP and request WPA3 (SAE (SHA256)):
```
Tag: RSN Information
    Tag Number: RSN Information (48)
    Tag length: 26
    RSN Version: 1
    Group Cipher Suite: 00:0f:ac (Ieee 802.11) AES (CCM)
    Pairwise Cipher Suite Count: 1
    Pairwise Cipher Suite List 00:0f:ac (Ieee 802.11) AES (CCM)
    Auth Key Management (AKM) Suite Count: 1
    Auth Key Management (AKM) List 00:0f:ac (Ieee 802.11) SAE (SHA256)
    RSN Capabilities: 0x00c0
    PMKID Count: 0
    PMKID List
    Group Management Cipher Suite: 00:0f:ac (Ieee 802.11) BIP (128)
        Group Management Cipher Suite OUI: 00:0f:ac (Ieee 802.11)
        Group Management Cipher Suite type: BIP (128) (6)
```

The PMKID in packet 18420 is a WPA3 PMKID which is not crackable by hashcat.

hcxpcapngtool told you that it is a mixed NETWORK:
`EAPOL M1 messages (KDV:0 AKM defined)....: 3
`
This messages contain the WPA3 PMKIDs only.

BTW:
In case you have you have used aircrack-ng please read this:
https://github.com/aircrack-ng/aircrack-ng/issues/2197

**Comment by ZerBea** [comment]
BTW:
Do you have a password for this NETWORK? I'm working to break WPA3.

**Comment by ZerBea** [comment]
BTW:
It is very hard to detect the AKM that it is in use for the connection if some important frames (ASSOCIATIONREQUEST and REASSOCIATIONREQUEST) are missing in the dump file (e.g. due to a packet loss on reception).
The AP provide both modes (WPA2 and WPA3) and announced that in the RSN IE_TAG of the BEACON:
```
Tag: RSN Information
    Tag Number: RSN Information (48)
    Tag length: 24
    RSN Version: 1
    Group Cipher Suite: 00:0f:ac (Ieee 802.11) AES (CCM)
        Group Cipher Suite OUI: 00:0f:ac (Ieee 802.11)
        Group Cipher Suite type: AES (CCM) (4)
    Pairwise Cipher Suite Count: 1
    Pairwise Cipher Suite List 00:0f:ac (Ieee 802.11) AES (CCM)
        Pairwise Cipher Suite: 00:0f:ac (Ieee 802.11) AES (CCM)
            Pairwise Cipher Suite OUI: 00:0f:ac (Ieee 802.11)
            Pairwise Cipher Suite type: AES (CCM) (4)
    Auth Key Management (AKM) Suite Count: 2
    Auth Key Management (AKM) List 00:0f:ac (Ieee 802.11) PSK 00:0f:ac (Ieee 802.11) SAE (SHA256)
        Auth Key Management (AKM) Suite: 00:0f:ac (Ieee 802.11) PSK
            Auth Key Management (AKM) OUI: 00:0f:ac (Ieee 802.11)
            Auth Key Management (AKM) type: PSK (2)
        Auth Key Management (AKM) Suite: 00:0f:ac (Ieee 802.11) SAE (SHA256)
            Auth Key Management (AKM) OUI: 00:0f:ac (Ieee 802.11)
            Auth Key Management (AKM) type: SAE (SHA256) (8)
    RSN Capabilities: 0x008c
        .... .... .... ...0 = RSN Pre-Auth capabilities: Transmitter does not support pre-authentication
        .... .... .... ..0. = RSN No Pairwise capabilities: Transmitter can support WEP default key 0 simultaneously with Pairwise key
        .... .... .... 11.. = RSN PTKSA Replay Counter capabilities: 16 replay counters per PTKSA/GTKSA/STAKeySA (0x3)
        .... .... ..00 .... = RSN GTKSA Replay Counter capabilities: 1 replay counter per PTKSA/GTKSA/STAKeySA (0x0)
        .... .... .0.. .... = Management Frame Protection Required: False
        .... .... 1... .... = Management Frame Protection Capable: True
        .... ...0 .... .... = Joint Multi-band RSNA: False
        .... ..0. .... .... = PeerKey Enabled: False
        ..0. .... .... .... = Extended Key ID for Individually Addressed Frames: Not supported
```

Only the ASSOCIATION/REASSOCIATIONREQUEST frames contain the AKM which is really in use.
e,g, CLIENT 009ec8e7361c want to connect in WPA2 mode:
```
Tag: RSN Information
    Tag Number: RSN Information (48)
    Tag length: 20
    RSN Version: 1
    Group Cipher Suite: 00:0f:ac (Ieee 802.11) AES (CCM)
        Group Cipher Suite OUI: 00:0f:ac (Ieee 802.11)
        Group Cipher Suite type: AES (CCM) (4)
    Pairwise Cipher Suite Count: 1
    Pairwise Cipher Suite List 00:0f:ac (Ieee 802.11) AES (CCM)
        Pairwise Cipher Suite: 00:0f:ac (Ieee 802.11) AES (CCM)
            Pairwise Cipher Suite OUI: 00:0f:ac (Ieee 802.11)
            Pairwise Cipher Suite type: AES (CCM) (4)
    Auth Key Management (AKM) Suite Count: 1
    Auth Key Management (AKM) List 00:0f:ac (Ieee 802.11) PSK
        Auth Key Management (AKM) Suite: 00:0f:ac (Ieee 802.11) PSK
            Auth Key Management (AKM) OUI: 00:0f:ac (Ieee 802.11)
            Auth Key Management (AKM) type: PSK (2)
    RSN Capabilities: 0x0000
        .... .... .... ...0 = RSN Pre-Auth capabilities: Transmitter does not support pre-authentication
        .... .... .... ..0. = RSN No Pairwise capabilities: Transmitter can support WEP default key 0 simultaneously with Pairwise key
        .... .... .... 00.. = RSN PTKSA Replay Counter capabilities: 1 replay counter per PTKSA/GTKSA/STAKeySA (0x0)
        .... .... ..00 .... = RSN GTKSA Replay Counter capabilities: 1 replay counter per PTKSA/GTKSA/STAKeySA (0x0)
        .... .... .0.. .... = Management Frame Protection Required: False
        .... .... 0... .... = Management Frame Protection Capable: False
        .... ...0 .... .... = Joint Multi-band RSNA: False
        .... ..0. .... .... = PeerKey Enabled: False
        ..0. .... .... .... = Extended Key ID for Individually Addressed Frames: Not supported
```

e.g. CLIENT 24dfa79554e6 want to connect in WPA2 or WPA3 mode:
```
Tag: RSN Information
    Tag Number: RSN Information (48)
    Tag length: 24
    RSN Version: 1
    Group Cipher Suite: 00:0f:ac (Ieee 802.11) AES (CCM)
        Group Cipher Suite OUI: 00:0f:ac (Ieee 802.11)
        Group Cipher Suite type: AES (CCM) (4)
    Pairwise Cipher Suite Count: 1
    Pairwise Cipher Suite List 00:0f:ac (Ieee 802.11) AES (CCM)
        Pairwise Cipher Suite: 00:0f:ac (Ieee 802.11) AES (CCM)
            Pairwise Cipher Suite OUI: 00:0f:ac (Ieee 802.11)
            Pairwise Cipher Suite type: AES (CCM) (4)
    Auth Key Management (AKM) Suite Count: 2
    Auth Key Management (AKM) List 00:0f:ac (Ieee 802.11) PSK 00:0f:ac (Ieee 802.11) SAE (SHA256)
        Auth Key Management (AKM) Suite: 00:0f:ac (Ieee 802.11) PSK
            Auth Key Management (AKM) OUI: 00:0f:ac (Ieee 802.11)
            Auth Key Management (AKM) type: PSK (2)
        Auth Key Management (AKM) Suite: 00:0f:ac (Ieee 802.11) SAE (SHA256)
            Auth Key Management (AKM) OUI: 00:0f:ac (Ieee 802.11)
            Auth Key Management (AKM) type: SAE (SHA256) (8)
    RSN Capabilities: 0x000c
        .... .... .... ...0 = RSN Pre-Auth capabilities: Transmitter does not support pre-authentication
        .... .... .... ..0. = RSN No Pairwise capabilities: Transmitter can support WEP default key 0 simultaneously with Pairwise key
        .... .... .... 11.. = RSN PTKSA Replay Counter capabilities: 16 replay counters per PTKSA/GTKSA/STAKeySA (0x3)
        .... .... ..00 .... = RSN GTKSA Replay Counter capabilities: 1 replay counter per PTKSA/GTKSA/STAKeySA (0x0)
        .... .... .0.. .... = Management Frame Protection Required: False
        .... .... 0... .... = Management Frame Protection Capable: False
        .... ...0 .... .... = Joint Multi-band RSNA: False
        .... ..0. .... .... = PeerKey Enabled: False
        ..0. .... .... .... = Extended Key ID for Individually Addressed Frames: Not supported

```
In every case the AP will choose the mode with the highest encyprion security.

BTW:
Tools like wpaclean filter this frames out and the AKM information get lost fo ever. That is the reason why I recommend not to use them.

**Comment by ZerBea** [comment]
I recommend to use hcxdumptool/hcxlabtool series, because this tools interact with the target (CLIENT and AP) and try to downgrade the AKM to WPA2. In addition to that this tools detect a packet loss and request the missing frames.

**Comment by LLH-l** [comment]
> BTW: Do you have a password for this NETWORK? I'm working to break WPA3.

Unfortunately, I don't know the password, I stumbled across it from another place

But I will try  best to recover the password, and if the password recovery is successful, I will let you know immediately

**Comment by ZerBea** [comment]
Thanks.
I'm not sure if that is possible on the handshakes converted from this dump file:
hcxpcapngtool identified 3 possible EAPOL MESSAGEPAIRS from this three CLIENTs:
8cdef9d0b461 - 009ec8e7361c
8cdef9d0b461 - 286c071bdb3d
8cdef9d0b461 - ac764ce7d2a3

Due to packet loss during the reception it could be possible that at least one of them (8cdef9d0b461 - ac764ce7d2a3) is not recoverable (WPA3), because hcxpcapngtool conversion failed, too.

I think we can close this issue report, because there is nothing I can do.

**Comment by ZerBea** [comment]
BTW:
I took a closer look at the dump file and notice that all(!) injected DEAUTHENTICATION frames have had absolutely no effect (except useless jamming the channel) because MFP (Management Frame Protection) is activated.

**Comment by ZerBea** [comment]
By latest commit I added a counter on AKM defined PMKIDs.
Neither hashcat nor JtR is able to recover the PSK from this PMKIDs, but now we have an overview how many EAPOL M1 messages contain them:
`PMKID (AKM defined - not recoverable)....: 3
`

Example:
```
$ hcxpcapngtool *.* -o test
hcxpcapngtool 6.2.7-31-g1516c88 reading from pmkid not recognized.cap...
failed to read packet 20057

summary capture file
--------------------
file name................................: pmkid not recognized.cap
version (pcap/cap).......................: 2.4 (very basic format without any additional information)
timestamp minimum (GMT)..................: 27.07.2022 17:55:14
timestamp maximum (GMT)..................: 27.07.2022 18:01:35
used capture interfaces..................: 1
link layer header type...................: DLT_IEEE802_11 (105) very basic format without any additional information about the quality
endianess (capture system)...............: little endian
packets inside...........................: 20057
ESSID (total unique).....................: 1
BEACON (total)...........................: 1
BEACON on 2.4 GHz channel (from IE_TAG)..: 10 
ACTION (total)...........................: 55
ACTION (containing ESSID)................: 1
PROBEREQUEST (directed)..................: 128
PROBERESPONSE (total)....................: 877
DEAUTHENTICATION (total).................: 6153
DISASSOCIATION (total)...................: 29
AUTHENTICATION (total)...................: 343
AUTHENTICATION (OPEN SYSTEM).............: 327
AUTHENTICATION (SAE).....................: 16
ASSOCIATIONREQUEST (total)...............: 142
ASSOCIATIONREQUEST (PSK).................: 140
ASSOCIATIONREQUEST (SAE SHA256)..........: 2
WPA encrypted............................: 2549
EAPOL messages (total)...................: 26
EAPOL RSN messages.......................: 26
EAPOLTIME gap (measured maximum usec)....: 82418
EAPOL ANONCE error corrections (NC)......: not detected
EAPOL M1 messages (total)................: 11
EAPOL M1 messages (KDV:0 AKM defined)....: 3
EAPOL M2 messages (total)................: 4
EAPOL M3 messages (total)................: 10
EAPOL M3 messages (KDV:0 AKM defined)....: 3
EAPOL M4 messages (total)................: 1
EAPOL pairs (total)......................: 8
EAPOL pairs (best).......................: 3
EAPOL pairs written to 22000 hash file...: 3 (RC checked)
EAPOL M32E2 (authorized).................: 3
PMKID (AKM defined - not recoverable)....: 3
packet read error........................: 1

Information: limited dump file format detected!
This file format is a very basic format to save captured network data.
It is recommended to use PCAP Next Generation dump file format (or pcapng for short) instead.
The PCAP Next Generation dump file format is an attempt to overcome the limitations
of the currently widely used (but limited) libpcap (cap, pcap) format.
https://www.wireshark.org/docs/wsug_html_chunked/AppFiles.html#ChAppFilesCaptureFilesSection
https://github.com/pcapng/pcapng

Information: radiotap header is missing!
Radiotap is a de facto standard for 802.11 frame injection and reception.
The radiotap header format is a mechanism to supply additional information about frames,
from the driver to userspace applications.
https://www.radiotap.org/

Warning: out of sequence timestamps!
This dump file contains frames with out of sequence timestamps.
That is a bug of the capturing tool.

Warning: too many deauthentication/disassociation frames detected!
That can cause that an ACCESS POINT change channel, reset EAPOL TIMER,
renew ANONCE and set PMKID to zero.
This could prevent to calculate a valid EAPOL MESSAGE PAIR
or to get a valid PMKID.

Information: missing frames!
This dump file does not contain undirected proberequest frames.
An undirected proberequest may contain information about the PSK.
It always happens if the capture file was cleaned or
it could happen if filter options are used during capturing.
That makes it hard to recover the PSK.


session summary
---------------
processed cap files...................: 1
```

I guess, that will solve this issue report completely.

**Comment by LLH-l** [comment]
Hello,  ZerBea
I rechecked them
The captured client (ac:76:4c:e7:d2:a3) can confirm that it is not a WPA3 handshake

In fact, we can see its authentication type from message 2
Please see packets: 18299 and 18301  18303
The captured handshake confirms it is a WPA/WPA2 authentication type
  Because it is impossible for current tools to capture WPA3 authentication handshake packets
Then its PMKID is estimated to be a WPA/WPA2 type
![18299](https://user-images.githubusercontent.com/80609791/208814470-cb4df900-5f62-4b58-a5a8-91d878a5609a.png)
![183017](https://user-images.githubusercontent.com/80609791/208814474-0a1eb5d6-e817-48a3-958b-47054c3cca1e.png)
![1221113445](https://user-images.githubusercontent.com/80609791/208815086-77f2c635-c502-4971-b19d-5474a0e3c645.png)


As to whether the following PMKIDs are WPA/or WPA3 types, there is currently no reliable proof to prove it
(ac:76:4c:e7:d2:a3)
(24:df:a7:95:54:e6)
(36:ca:0b:23:c2:67)
(44:23:7c:dd:dd:0c)

**Comment by ZerBea** [comment]
No! There is absolutely no WPA2 PMKID in this dump file:

Packet 18299 from CLIENT does NOT contain a PMKID
[Message number: 2]
Replay Counter: 1
PMKID Count: 0

Packet 18290 is the matchin part from the ACCESSPOINT does not contain a PMKID:
[Message number: 1]
Replay Counter: 1
WPA Key Data Length: 0



Packet 16302 is the repeated packet 18299 (R flag is set) 
IEEE 802.11 QoS Data, Flags: ....R..T

Packet 18303 is the third part (M3 from AP) of the handshake.  WPA information is encrypted:
[Message number: 3]
Replay Counter: 2
WPA Key Data: 81ee6c7de2421504194b2239bb5fbf2f29f8e00c2cf16e8c30bcab7f889ae0936db55d6b…
 
But anyway, hcxpcapngtool detected that it is a WPA2 handshke and converted it to hc22000 file (format WPA*01):


The only PMKIDs inside this dump file are in
packet 16798
.... .... .... .000 = Key Descriptor Version: Unknown (0)
PMKID: e79facd57cd689518fee257182116142

and packet 18420
.... .... .... .000 = Key Descriptor Version: Unknown (0)
PMKID: 0e11497e8c3bf9c7445e5bf7f509d9bd

and packet 19945
.... .... .... .000 = Key Descriptor Version: Unknown (0)
PMKID: 101eff05f4eb01af363ac2c2cde2d867


Wireshark showing the Authentication Key Management defined (AKM) keydescriptor version 0 as unknown
kv 1 = WPA1 (MD5)
kv 2 = WPA2 (SHA1)
kv 3 = WPA2 key version 3 (SHA256)
kv 0 = AKM defined


BTW:
The relationship between EAPOL messages (M1, M2, M3, M4), replay counter, and Key Descriptor Version is really really hard core and very difficult to understand. Especially if the dump file contain data from WPA3 SAE transition mode:
https://mrncciew.com/2019/11/29/wpa3-sae-transition-mode/

**Comment by ZerBea** [comment]
Here is an example of a WPA2 PMKID:
```
[Message number: 1]
.... .... .... .010 = Key Descriptor Version: AES Cipher, HMAC-SHA1 MIC (2)
WPA Key Data: dd14000fac04101eff05f4eb01af363ac2c2cde2d867
    Tag: Vendor Specific: Ieee 802.11: RSN PMKID
        Tag Number: Vendor Specific (221)
        Tag length: 20
        OUI: 00:0f:ac (Ieee 802.11)
        Vendor Specific OUI Type: 4
        Data Type: PMKID KDE (4)
        PMKID: 101eff05f4eb01af363ac2c2cde2d867
```

You will not find such a WPA2 PMKID in the dump file attached above.

**Comment by LLH-l** [comment]
@ZerBea 
search
found a WPA3 handshake,  It also includes password
https://xiaopan.co/forums/threads/wpa3-handshake.62953

**Comment by ZerBea** [comment]
Thanks for the information.
Unfortunately I can't download the dump file on xiaopan, because I'm not a member there

**Comment by ZerBea** [comment]
This is very suspect.

According to the user who commented the handshake on xiaopan it is WPA3:
`WIFIPR software crack, password is correct`

According to WIFIPR web site, the tool is only able to recover WPA and WPA2:
`Wireless Password Recovery is a utility for analyzing the security of your wireless networks and recovering WPA / WPA2 passwords.`

**Comment by LLH-l** [comment]
> password is correct

He meaning  should be,  theis password can successfully connect to  AP

**Comment by LLH-l** [comment]
> Thanks for the information.
Unfortunately I can't download the dump file on xiaopan, because I'm not a member there

@ZerBea 
[666vip19710129.zip](https://github.com/ZerBea/hcxtools/files/11370727/666vip19710129.zip)

**Comment by LLH-l** [comment]
> According to the user who commented the handshake on xiaopan it is WPA3:

I checked the time, it seems not file earliest source web

**Comment by ZerBea** [comment]
The dump file contain a SAE PMK SHARED AUTHENTICATION and a WPA3 handshake, but I have doubts, that it was cracked by WIFIPR.
