### ISSUE TITLE
After Installing hcxtools on Kali Linux 2022 

### ISSUE THREAD

**Issue by chromeheartbeat** [ZerBea/hcxtools#226]
After successfully Installing hcxtools on Kali Linux 2022 and Open Root Terminal Emulator and run these commands in order.

apt-get update
apt-get install libcurl4-openssl-dev libssl-dev zlib1g-dev libpcap-dev

git clone [https://github.com/ZerBea/hcxdumptools.git
cd hcxdumptool/
sudo make && sudo make install

git clone [https://github.com/ZerBea/hcxtools.git
cd hcxtools/
sudo make && sudo make install

and then I reboot the VM

, I ran into this problem below.

Warning: Recommended app hcxpcaptool was not found. install @ https://github.com/ZerBea/hcxtools   
                                                  
 [+] Checking airmon-ng...                                                   
 [!] airmon-ng did not find any wireless interfaces
 [!] Make sure your wireless device is connected                             
 [!] See http://www.aircrack-ng.org/doku.php?id=airmon-ng for more info      

 [!] Error: airmon-ng did not find any wireless interfaces
                                                                             
 [!] Full stack trace below                                                  
                                                                             
 [!]    Traceback (most recent call last):                                   
 [!]    File "/usr/local/lib/python3.10/dist-packages/wifite/__main__.py", line 93, in entry_point
 [!]        wifite.start()
 [!]    File "/usr/local/lib/python3.10/dist-packages/wifite/__main__.py", line 53, in start
 [!]        Configuration.get_monitor_mode_interface()
 [!]    File "/usr/local/lib/python3.10/dist-packages/wifite/config.py", line 132, in get_monitor_mode_interface
 [!]        cls.interface = Airmon.ask()
 [!]    File "/usr/local/lib/python3.10/dist-packages/wifite/tools/airmon.py", line 299, in ask
 [!]        raise Exception('airmon-ng did not find any wireless interfaces')
 [!]  Exception: airmon-ng did not find any wireless interfaces              
                                                                             
 [!] Exiting 

Here is the Version of my Kali Linux:
$ cat /etc/os-release
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2022.3"
VERSION_ID="2022.3"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"

$uname -a
Linux Kali 5.18.0-kali5-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.5-1kali6 (2022-07-07) x86_64 GNU/Linux

**Comment by ZerBea** [comment]
First of all, this is not a hcxtools issue, because the tools are compiled and installed successfully.

Explanation:
hcxpcaptool was replaced by hcxpcapngtool -more than 2 years ago (see changelog):
https://github.com/ZerBea/hcxtools/releases/tag/6.1.2
```
04.09.2020
==========
removed deprecated hcxpcaptool - use hcxpcapngtool instead
```

This
`Warning: Recommended app hcxpcaptool was not found. install @ https://github.com/ZerBea/hcxtools
`
is a WiFite problem and It should be fixed in WiFite2 since 14 Dec 2020: 
https://github.com/kimocoder/wifite2/issues/54
It looks like you're running an old WiFite version. Ther latest git head is here:
https://github.com/kimocoder/wifite2


This
`[!] Error: airmon-ng did not find any wireless interfaces
`
is an aircrack-ng problem and you should get help here:
https://forum.aircrack-ng.org/
or report issues here:
https://github.com/aircrack-ng/aircrack-ng

Closed this issue, because WiFite and airmon-ng caused the problem.

**Comment by ZerBea** [comment]
You mentioned that you have installed hcxdumptool, too.
Regarding hcxdumptool, please read README.md sections "Requirements" and "Adapters".
Also read hcxdumptool --help:
```
do not set monitor mode by third party tools (iwconfig, iw, airmon-ng)
do not run hcxdumptool on logical (NETLINK) interfaces (monx, wlanxmon, prismx, ...) created by airmon-ng and iw
do not run hcxdumptool on virtual machines or emulators
do not run hcxdumptool in combination with tools (channel hopper), that take access to the interface (except: tshark, wireshark, tcpdump)
do not use tools like macchanger, because hcxdumptool runs its own MAC space and will ignore this changes
```

**Comment by chromeheartbeat** [comment]
Thanks ZerBea. 

That was Helpful

**Comment by chromeheartbeat** [comment]
Thanks ZerBea.

That was helpful

**Comment by ZerBea** [comment]
No problem, you're welcome.

BTW:
Major reason to switch from hcxpcaptool to hcxpcapngtool is pcapng format to store the packets.
The old cap/pcap  file format is a very basic format to save captured network data.
It is recommended to use PCAP Next Generation dump file format (or pcapng for short) instead.
The PCAP Next Generation dump file format is an attempt to overcome the limitations
of the currently widely used (but very limited) libpcap (cap, pcap) format.
https://www.wireshark.org/docs/wsug_html_chunked/AppFiles.html#ChAppFilesCaptureFilesSection
https://github.com/pcapng/pcapng
The major analysis tools (Wireshark/tshark) use pcapng as default.
