### ISSUE TITLE
cannot make or compile

### ISSUE THREAD

**Issue by bandrel** [ZerBea/hcxtools#228]
![image](https://user-images.githubusercontent.com/3598052/201739269-33516873-e972-422e-a0e1-d02c764a3cfd.png)
![image](https://user-images.githubusercontent.com/3598052/201739315-bbef5dd6-86c1-466e-8c19-b4ff3e32e89d.png)

**Comment by ZerBea** [comment]
Issue 1: Make sure, you have OpenSSL 3.0.x installed.
Issue 2: Remove entire hcxtools folder because your git clone is broken
Than do the following steps. Output should look like mentioned below.
```
$ git clone https://github.com/ZerBea/hcxtools

$ cd hcxtools

$ make
mkdir -p .deps
cc -O3 -Wall -Wextra    -MMD -MF .deps/hcxpcapngtool.d -o hcxpcapngtool hcxpcapngtool.c -lssl -lcrypto  -lz   -DVERSION_TAG=\"6.2.7-74-ge26e91d\" -DVERSION_YEAR=\"2022\" -DWANTZLIB
cc -O3 -Wall -Wextra    -MMD -MF .deps/hcxhashtool.d -o hcxhashtool hcxhashtool.c -lssl -lcrypto  -lcurl   -DVERSION_TAG=\"6.2.7-74-ge26e91d\" -DVERSION_YEAR=\"2022\" -DWANTZLIB
cc -O3 -Wall -Wextra   -MMD -MF .deps/hcxpsktool.d -o hcxpsktool hcxpsktool.c -lssl -lcrypto   -DVERSION_TAG=\"6.2.7-74-ge26e91d\" -DVERSION_YEAR=\"2022\" -DWANTZLIB
cc -O3 -Wall -Wextra   -MMD -MF .deps/hcxpmktool.d -o hcxpmktool hcxpmktool.c -lssl -lcrypto   -DVERSION_TAG=\"6.2.7-74-ge26e91d\" -DVERSION_YEAR=\"2022\" -DWANTZLIB
cc -O3 -Wall -Wextra   -MMD -MF .deps/hcxeiutool.d -o hcxeiutool hcxeiutool.c   -DVERSION_TAG=\"6.2.7-74-ge26e91d\" -DVERSION_YEAR=\"2022\" -DWANTZLIB
cc -O3 -Wall -Wextra   -MMD -MF .deps/hcxwltool.d -o hcxwltool hcxwltool.c   -DVERSION_TAG=\"6.2.7-74-ge26e91d\" -DVERSION_YEAR=\"2022\" -DWANTZLIB
cc -O3 -Wall -Wextra   -MMD -MF .deps/hcxhash2cap.d -o hcxhash2cap hcxhash2cap.c   -DVERSION_TAG=\"6.2.7-74-ge26e91d\" -DVERSION_YEAR=\"2022\" -DWANTZLIB
cc -O3 -Wall -Wextra    -MMD -MF .deps/wlancap2wpasec.d -o wlancap2wpasec wlancap2wpasec.c -lssl -lcrypto  -lcurl   -DVERSION_TAG=\"6.2.7-74-ge26e91d\" -DVERSION_YEAR=\"2022\" -DWANTZLIB
cc -O3 -Wall -Wextra    -MMD -MF .deps/whoismac.d -o whoismac whoismac.c -lssl -lcrypto  -lcurl   -DVERSION_TAG=\"6.2.7-74-ge26e91d\" -DVERSION_YEAR=\"2022\" -DWANTZLIB

$ sudo make install
install -D -m 0755 hcxpcapngtool /usr/bin/hcxpcapngtool
install -D -m 0755 hcxhashtool /usr/bin/hcxhashtool
install -D -m 0755 hcxpsktool /usr/bin/hcxpsktool
install -D -m 0755 hcxpmktool /usr/bin/hcxpmktool
install -D -m 0755 hcxeiutool /usr/bin/hcxeiutool
install -D -m 0755 hcxwltool /usr/bin/hcxwltool
install -D -m 0755 hcxhash2cap /usr/bin/hcxhash2cap
install -D -m 0755 wlancap2wpasec /usr/bin/wlancap2wpasec
install -D -m 0755 whoismac /usr/bin/whoismac

$ hcxpcapngtool -v
hcxpcapngtool 6.2.7-74-ge26e91d (C) 2022 ZeroBeat

```

**Comment by xfaith** [comment]
Was just about to post here, having same issue looks like on pi4.   Following the directions, cloned git, and tried make --  EVP

**Comment by xfaith** [comment]
openssl is already the newest version (1.1.1n-0+deb10u3).  - This is on Pi4.

**Comment by ZerBea** [comment]
I started to move to the new EVP API of OpenSSL 3.0 (now mandatory) as mentioned in README.md.
https://wiki.openssl.org/index.php/OpenSSL_3.0
Much faster an easier to maintain. 

Should be present in latest updates of main distributions:
$ pacman -Q | grep openssl
openssl 3.0.7-2

https://packages.debian.org/search?keywords=OpenSSL&searchon=names&suite=all&section=all
I

**Comment by ZerBea** [comment]
@xfaith Which distribution? I'm running Debian Bookworm on my Zero's.

**Comment by ZerBea** [comment]
openssl (3.0.7-1) 
https://packages.debian.org/bookworm/openssl

**Comment by ZerBea** [comment]
Arch Linux is running 3.0.7 as default and I got several warning about deprecated functions:
https://archlinux.org/packages/core/x86_64/openssl/
To get rid of this warnings I moved to v3.0

**Comment by ZerBea** [comment]
To get benefit of the latest improvements (hcxpmktool) it is mandatory to have OpenSSL 3.0 installed:
https://github.com/ZerBea/hcxtools/issues/227#issuecomment-1314184490

**Comment by xfaith** [comment]
I am using a pwnagotchi which i think is : 5.15.44-Re4son-v7l+ #1 SMP Debian kali-pi (2022-07-03) armv7l GNU/Linux

**Comment by bandrel** [comment]
Ubuntu 20.04 which has gcc-9 and not 11. Not sure if thats the issue

**Comment by bandrel** [comment]
Confirmed installing openssl3 fixed it. thank you!

**Comment by ZerBea** [comment]
@bandrel , could be gcc or make

My environment:
$ pacman -Q | grep gcc
gcc 12.2.0-1

$ pacman -Q | grep make
make 4.3-5

**Comment by bandrel** [comment]
new errors :) which i do think are now gcc/make related.

**Comment by ZerBea** [comment]
OpenSSL 3.0 is a huge step forward. 
OpenSSL 1.1 = 100 lines of code - OpenSSL 3.0 only 5 lines of code
That simplify everthing.

**Comment by ZerBea** [comment]
Arch is a rolling release distribution (as well as Debian testing) and I get benefit of latest changes and improvements. That make live much easier.

**Comment by ZerBea** [comment]
https://packages.debian.org/bookworm/gcc
also on gcc (4:12.2.0-1)

https://packages.debian.org/bookworm/make
also on make (4.3-4.1)

that may explain why I don't have any problems.

**Comment by ZerBea** [comment]
I'm a a big fan of the "rolling release" principle and from this point of view
Debian stable is old:
Debian 11 (Bullseye) was released on 14 August 2021. It is based on the Linux 5.10 LTS kernel.
https://en.wikipedia.org/wiki/Debian_version_history#Debian_11_(Bullseye)

The same applies to Ubunt 20.04
Ubuntu 20.04 LTS, codenamed Focal Fossa, is a long-term support release and was released on 23 April 2020
https://en.wikipedia.org/wiki/Ubuntu_version_history

Unfortunately I can't support all old versions/distributions. To do this I would have to install all old versions and to add their functions to hcxtools. That would make the code completely illegible.

**Comment by LLH-l** [comment]
![2](https://user-images.githubusercontent.com/80609791/202888430-8cc7668d-22af-4d3b-a801-7908d7854694.png)

**Comment by ZerBea** [comment]
Missing openssl/conf.h is part of the openssl development files. YOu must install tehm, too.
