### ISSUE TITLE
cygwin make

### ISSUE THREAD

**Issue by LLH-l** [ZerBea/hcxtools#229]
Unable to compile into exe program in cygwin environment

But the old version can be compiled successfully

already installed
cygwin Base
cygwin-devel Devel
gcc-core Devel
zlib-devel Devel
libcurl-devel Devel，Libs，Net
libssl-devel Devel
Make Devel
git Devel

What else do I need to install to compile successfully?

`$cd hcxtools-master

 $make
fatal: not a git repository (or any of the parent directories): .git
mkdir -p .deps
cc -O3 -Wall -Wextra    -MMD -MF .deps/hcxpcapngtool.d -o hcxpcapngtool hcxpcapngtool.c -lssl -lcrypto  -lz   -DVERSION_TAG=\"6.2.7\" -DVERSION_YEAR=\"2022\" -DWANTZLIB
hcxpcapngtool.c:87:8: error: unknown type name ‘EVP_MAC’
   87 | static EVP_MAC *hmac;
      |        ^~~~~~~
hcxpcapngtool.c:88:8: error: unknown type name ‘EVP_MAC’
   88 | static EVP_MAC *cmac;
      |        ^~~~~~~
hcxpcapngtool.c:89:8: error: unknown type name ‘EVP_MAC_CTX’
   89 | static EVP_MAC_CTX *ctxhmac;
      |        ^~~~~~~~~~~
hcxpcapngtool.c:90:8: error: unknown type name ‘EVP_MAC_CTX’
   90 | static EVP_MAC_CTX *ctxcmac;
      |        ^~~~~~~~~~~
hcxpcapngtool.c:91:8: error: unknown type name ‘OSSL_PARAM’
   91 | static OSSL_PARAM paramsmd5[3];
      |        ^~~~~~~~~~
hcxpcapngtool.c:92:8: error: unknown type name ‘OSSL_PARAM’
   92 | static OSSL_PARAM paramssha1[3];
      |        ^~~~~~~~~~
hcxpcapngtool.c:93:8: error: unknown type name ‘OSSL_PARAM’
   93 | static OSSL_PARAM paramssha256[3];
      |        ^~~~~~~~~~
hcxpcapngtool.c:94:8: error: unknown type name ‘OSSL_PARAM’
   94 | static OSSL_PARAM paramsaes128[3];
      |        ^~~~~~~~~~
hcxpcapngtool.c: In function ‘testpmkid’:
hcxpcapngtool.c:1881:5: warning: implicit declaration of function ‘EVP_MAC_init’; did you mean ‘EVP_MD_CTX_init’? [-Wimplicit-function-declaration]
 1881 | if(!EVP_MAC_init(ctxhmac, testpmk, 32, paramssha1)) return false;
      |     ^~~~~~~~~~~~
      |     EVP_MD_CTX_init
hcxpcapngtool.c:1882:5: warning: implicit declaration of function ‘EVP_MAC_update’; did you mean ‘HMAC_Update’? [-Wimplicit-function-declaration]
 1882 | if(!EVP_MAC_update(ctxhmac, pmkidcalc, 20)) return false;
      |     ^~~~~~~~~~~~~~
      |     HMAC_Update
hcxpcapngtool.c:1883:5: warning: implicit declaration of function ‘EVP_MAC_final’; did you mean ‘HMAC_Final’? [-Wimplicit-function-declaration]
 1883 | if(!EVP_MAC_final(ctxhmac, pmkidcalc, NULL, 20)) return false;
      |     ^~~~~~~~~~~~~
      |     HMAC_Final
hcxpcapngtool.c: In function ‘evpdeinitwpa’:
hcxpcapngtool.c:5578:9: warning: implicit declaration of function ‘EVP_MAC_CTX_free’; did you mean ‘EVP_MD_CTX_free’? [-Wimplicit-function-declaration]
 5578 |         EVP_MAC_CTX_free(ctxhmac);
      |         ^~~~~~~~~~~~~~~~
      |         EVP_MD_CTX_free
hcxpcapngtool.c:5579:9: warning: implicit declaration of function ‘EVP_MAC_free’; did you mean ‘EVP_PKEY_free’? [-Wimplicit-function-declaration]
 5579 |         EVP_MAC_free(hmac);
      |         ^~~~~~~~~~~~
      |         EVP_PKEY_free
hcxpcapngtool.c: In function ‘evpinitwpa’:
hcxpcapngtool.c:5610:8: warning: implicit declaration of function ‘EVP_MAC_fetch’ [-Wimplicit-function-declaration]
 5610 | hmac = EVP_MAC_fetch(NULL, "hmac", NULL);
      |        ^~~~~~~~~~~~~
hcxpcapngtool.c:5610:6: warning: assignment to ‘int *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
 5610 | hmac = EVP_MAC_fetch(NULL, "hmac", NULL);
      |      ^
hcxpcapngtool.c:5612:6: warning: assignment to ‘int *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
 5612 | cmac = EVP_MAC_fetch(NULL, "cmac", NULL);
      |      ^
hcxpcapngtool.c:5615:16: warning: implicit declaration of function ‘OSSL_PARAM_construct_utf8_string’ [-Wimplicit-function-declaration]
 5615 | paramsmd5[0] = OSSL_PARAM_construct_utf8_string("digest", "md5", 0);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
hcxpcapngtool.c:5616:16: warning: implicit declaration of function ‘OSSL_PARAM_construct_end’ [-Wimplicit-function-declaration]
 5616 | paramsmd5[1] = OSSL_PARAM_construct_end();
      |                ^~~~~~~~~~~~~~~~~~~~~~~~
hcxpcapngtool.c:5627:11: warning: implicit declaration of function ‘EVP_MAC_CTX_new’; did you mean ‘EVP_MD_CTX_new’? [-Wimplicit-function-declaration]
 5627 | ctxhmac = EVP_MAC_CTX_new(hmac);
      |           ^~~~~~~~~~~~~~~
      |           EVP_MD_CTX_new
hcxpcapngtool.c:5627:9: warning: assignment to ‘int *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
 5627 | ctxhmac = EVP_MAC_CTX_new(hmac);
      |         ^
hcxpcapngtool.c:5629:9: warning: assignment to ‘int *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
 5629 | ctxcmac = EVP_MAC_CTX_new(cmac);
      |         ^
make: *** [Makefile:96: hcxpcapngtool] Error 1
`

**Comment by ZerBea** [comment]
EVP API changed and Arch Linux moved to OpenSSL 3.0.7:
https://archlinux.org/packages/core/x86_64/openssl/
as well as Debian Bookworm:
https://packages.debian.org/bookworm/openssl

From now on it is mandatory that OpenSSL >= 3.0 is installed.
https://wiki.openssl.org/index.php/OpenSSL_3.0

That is mentioned in changelog:
```
12.11.2022
==========
start moving to OpenSSL 3.0 EVP API
this is a huge step forward an will break backward compatibility
https://wiki.openssl.org/index.php/OpenSSL_3.0
```
and README.md
`* libopenssl (>= v3.0) and openssl-dev installed
`

The version supplied by cygwin is ancient:
https://cygwin.com/cgi-bin2/package-grep.cgi?grep=libopenssl&arch=x86_64

Some more information is here:
https://github.com/ZerBea/hcxtools/issues/228

Please notice:
As well as Arch Linux
https://wiki.archlinux.org/title/Arch_Linux
I'm a friend of the "rolling release" principle
https://en.wikipedia.org/wiki/Rolling_release

This means no support for old software.

I think we can close this report, because it is related to ancient version of the crypto library.

**Comment by LLH-l** [comment]
@ZerBea 
How can compile into (*. exe) programs in the cygwin environment?
