### ISSUE TITLE
make is failing

### ISSUE THREAD

**Issue by 64-nickel** [ZerBea/hcxtools#235]
I had the same issue as described in https://githubplus.com/ZerBea/hcxdumptool/issues/232.  My prereqs were already installed (apt-get install libcurl4-openssl-dev libssl-dev zlib1g-dev).  That led me to https://githubplus.com/ZerBea/hcxdumptool/issues/233 that in turn led me to https://github.com/ZerBea/hcxtools/commit/5937d2ad9d021f3b5e2edd55d79439b8485d3222.

The solution appeared to be to install OpenSSL 3.0. So I installed newest OpenSSL from here: git clone https://github.com/openssl/openssl and ran:

./Configure
make
make test
sudo make install

All seemed to run without any issues.

I then rm -rf'd the entire ~/tmp/hcxdumptool folder and git clone'd it again from scratch. When I ran the make again, I got a different error for which I cannot find any references to remedy it.  Below are the first few lines of the new error.

~/tmp/hcxdumptool$ make
mkdir -p .deps
cc -O3 -Wall -Wextra -std=gnu99   -MMD -MF .deps/hcxdumptool.d -o hcxdumptool hcxdumptool.c -lssl -lcrypto  -DVERSION_TAG=\"6.2.7-28-g615b7b7\" -DVERSION_YEAR=\"2022\"
hcxdumptool.c: In function ‘process_fd’:
hcxdumptool.c:5963:36: warning: ‘
SNONCE....................:.’ directive output may be truncated writing 29 bytes into a region of size between 27 and 834 [-Wformat-truncation=]
 5963 | snprintf(servermsg, SERVERMSG_MAX, "\e[?25l\nstart capturing (stop with ctrl+c)\n"
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
hcxdumptool.c:5989:159: note: format string is defined here
 5989 |  "ANONCE....................: %02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x\n"
      |                                                                                                                                                               ^~~
 5990 |  "SNONCE....................: %02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x\n"
      |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                 
hcxdumptool.c:5963:36: note: directive argument in the range [0, 255]
 5963 | snprintf(servermsg, SERVERMSG_MAX, "\e[?25l\nstart capturing (stop with ctrl+c)\n"
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
hcxdumptool.c:5963:36: note: directive argument in the range [0, 255]
hcxdumptool.c:5963:36: note: directive argument in the range [0, 255]
hcxdumptool.c:5963:36: note: directive argument in the range [0, 255]
hcxdumptool.c:5963:36: note: directive argument in the range [0, 255]
hcxdumptool.c:5963:36: note: directive argument in the range [0, 255]
...snipped here for brevity...

**Comment by 64-nickel** [comment]
I just realized this should have been posted in the issues for hcxdumptool.  Just opened the issue there, but can't delete this one here.  Feel free to kill/delete/close, whatever you feel appropriate.

**Comment by ZerBea** [comment]
Ok, closed here
