### ISSUE TITLE
Hcxtools installation problem on raspberry pi 

### ISSUE THREAD

**Issue by PRADEEPDHIBAR** [ZerBea/hcxtools#249]
Last login: Fri Mar 31 04:00:24 2023

SSH is enabled and the default password for the 'pi' user has not been changed.
This is a security risk - please login as the 'pi' user and type 'passwd' to set a new password.

pi@pwnagotchi:~ $ ls
pi@pwnagotchi:~ $ sudo su
root@pwnagotchi:/home/pi# cd /opt                     root@pwnagotchi:/opt# cd hcxtools
root@pwnagotchi:/opt/hcxtools# make
cc -O3 -Wall -Wextra    -MMD -MF .deps/hcxpcapngtool.d -o hcxpcapngtool hcxpcapngtool.c -lssl -lcrypto -lz  -DVERSION_TAG=\"6.2.9\" -DVERSION_YEAR=\"2023\" -DWANTZLIB
hcxpcapngtool.c:87:8: error: unknown type name ‘EVP_MAC’
 static EVP_MAC *hmac;
        ^~~~~~~
hcxpcapngtool.c:88:8: error: unknown type name ‘EVP_MAC’
 static EVP_MAC *cmac;
        ^~~~~~~
hcxpcapngtool.c:89:8: error: unknown type name ‘EVP_MAC_CTX’
 static EVP_MAC_CTX *ctxhmac;
        ^~~~~~~~~~~
hcxpcapngtool.c:90:8: error: unknown type name ‘EVP_MAC_CTX’
 static EVP_MAC_CTX *ctxcmac;
        ^~~~~~~~~~~
hcxpcapngtool.c:91:8: error: unknown type name ‘OSSL_PARAM’
 static OSSL_PARAM paramsmd5[3];
        ^~~~~~~~~~
hcxpcapngtool.c:92:8: error: unknown type name ‘OSSL_PARAM’
 static OSSL_PARAM paramssha1[3];
        ^~~~~~~~~~
hcxpcapngtool.c:93:8: error: unknown type name ‘OSSL_PARAM’
 static OSSL_PARAM paramssha256[3];
        ^~~~~~~~~~
hcxpcapngtool.c:94:8: error: unknown type name ‘OSSL_PARAM’
 static OSSL_PARAM paramsaes128[3];
        ^~~~~~~~~~
hcxpcapngtool.c: In function ‘testpmkid’:
hcxpcapngtool.c:1937:5: warning: implicit declaration of function ‘EVP_MAC_init’; did you mean ‘EVP_MD_nid’? [-Wimplicit-function-declaration]
 if(!EVP_MAC_init(ctxhmac, testpmk, 32, paramssha1)) return false;
     ^~~~~~~~~~~~
     EVP_MD_nid
hcxpcapngtool.c:1938:5: warning: implicit declaration of function ‘EVP_MAC_update’; did you mean ‘HMAC_Update’? [-Wimplicit-function-declaration]
 if(!EVP_MAC_update(ctxhmac, pmkidcalc, 20)) return false;
     ^~~~~~~~~~~~~~
     HMAC_Update
hcxpcapngtool.c:1939:5: warning: implicit declaration of function ‘EVP_MAC_final’; did you mean ‘HMAC_Final’? [-Wimplicit-function-declaration]
 if(!EVP_MAC_final(ctxhmac, pmkidcalc, NULL, 20)) return false;
     ^~~~~~~~~~~~~
     HMAC_Final
hcxpcapngtool.c: In function ‘evpdeinitwpa’:
hcxpcapngtool.c:5638:2: warning: implicit declaration of function ‘EVP_MAC_CTX_free’; did you mean ‘EVP_MD_CTX_free’? [-Wimplicit-function-declaration]
  EVP_MAC_CTX_free(ctxhmac);
  ^~~~~~~~~~~~~~~~
  EVP_MD_CTX_free
hcxpcapngtool.c:5639:2: warning: implicit declaration of function ‘EVP_MAC_free’; did you mean ‘EVP_PKEY_free’? [-Wimplicit-function-declaration]
  EVP_MAC_free(hmac);
  ^~~~~~~~~~~~
  EVP_PKEY_free
hcxpcapngtool.c: In function ‘evpinitwpa’:
hcxpcapngtool.c:5670:8: warning: implicit declaration of function ‘EVP_MAC_fetch’; did you mean ‘EVP_PBE_ge ’? [-Wimplicit-function-declaration]
 hmac = EVP_MAC_fetch(NULL, "hmac", NULL);
        ^~~~~~~~~~~~~
        EVP_PBE_get
hcxpcapngtool.c:5670:6: warning: assignment to ‘int *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
 hmac = EVP_MAC_fetch(NULL, "hmac", NULL);
      ^
hcxpcapngtool.c:5672:6: warning: assignment to ‘int *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
 cmac = EVP_MAC_fetch(NULL, "cmac", NULL);
      ^
hcxpcapngtool.c:5675:16: warning: implicit declaration of function ‘OSSL_PARAM_construct_utf8_string’ [-Wimplicit-function-declaration]
 paramsmd5[0] = OSSL_PARAM_construct_utf8_string("digest", "md5", 0);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
hcxpcapngtool.c:5676:16: warning: implicit declaration of function ‘OSSL_PARAM_construct_end’ [-Wimplicit-function-declaration]
 paramsmd5[1] = OSSL_PARAM_construct_end();
                ^~~~~~~~~~~~~~~~~~~~~~~~
hcxpcapngtool.c:5687:11: warning: implicit declaration of function ‘EVP_MAC_CTX_new’; did you mean ‘EVP_MD_CTX_new’? [-Wimplicit-function-declaration]
 ctxhmac = EVP_MAC_CTX_new(hmac);
           ^~~~~~~~~~~~~~~
           EVP_MD_CTX_new
hcxpcapngtool.c:5687:9: warning: assignment to ‘int *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
 ctxhmac = EVP_MAC_CTX_new(hmac);
         ^
hcxpcapngtool.c:5689:9: warning: assignment to ‘int *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
 ctxcmac = EVP_MAC_CTX_new(cmac);
         ^
make: *** No rule to make target 'hcxpcapngtool', needed by 'build'.  Stop.

**Comment by ZerBea** [comment]
OpenSSL >= 3.0 is mandatory and you must update to this version:

That is mentioned in README.md section "Requirements":
```
libopenssl (>= 3.0) and openssl-dev installed"
and
Debian (e.g. Kali, Ubuntu) release requirements >= bookworm (testing/Debian 12)
```
and it is mentioned in changelog, too:
```
10.03.2023
==========
release v6.2.8
move to EVP API 3.0 (from now on OpenSSL >= 3.0 is mandatory)
hcxpcapngtool: handle nsec timestamps 

...

12.11.2022
==========
start moving to OpenSSL 3.0 EVP API
this is a huge step forward an will break backward compatibility
https://wiki.openssl.org/index.php/OpenSSL_3.0
```

The same applies to hcxdumptool while hcxlabtool doesn't use OpenSSL.

Looks like you Raspberry is still running on old version of OpenSSL. You have to update it.

The new version is default an latest distributions and available in all repositories, e.g.: in Arch, Debian and Debian clones lie Raspbian and Ubuntu):
https://archlinux.org/packages/core/x86_64/openssl/
https://packages.debian.org/bookworm/openssl
https://packages.ubuntu.com/kinetic/openssl

Closed, because missing dependencies is not hcxtools bug. But you still can ask your questions here.
