### ISSUE TITLE
When M1M3 NONCE is different

### ISSUE THREAD

**Issue by LLH-l** [ZerBea/hcxtools#281]
[18359.zip](https://github.com/ZerBea/hcxtools/files/11504054/18359.zip)

```
18332	Nov  9, 2021 15:32:53.314387000 	1	1	86dcd79644644767e2dd867924ea4a45ffa9c786171545f26303ed8ea4d8237b
18355	Nov  9, 2021 15:32:54.319506000 	2	2	6307b2ff8d7da4a6013918ae243be5cd49e1654e28cd8199e2d998f79c3d9fa6
18357	Nov  9, 2021 15:32:54.319506000 	3	3	68dbb0762c271e65e3e682ab60f0b324371e6f7cec61f748089ee6491faa5b5f
```
When using - all
Generate only one M2M3
Ok, In this case, it may not  happened unexpectedly

But,
Let's assume another scenario
If   using - all
```
18332	Nov  9, 2021 15:32:54.314387000 	1	1	86dcd79644644767e2dd867924ea4a45ffa9c786171545f26303ed8ea4d8237b	d4:61:9d:1f:ff:42
18355	Nov  9, 2021 15:32:54.319506000 	2	2	6307b2ff8d7da4a6013918ae243be5cd49e1654e28cd8199e2d998f79c3d9fa6	24:4e:7b:5d:a7:6e
18357	Nov  9, 2021 15:32:55.319506000 	3	3	68dbb0762c271e65e3e682ab60f0b324371e6f7cec61f748089ee6491faa5b5f	d4:61:9d:1f:ff:42
```

If only one M1M2 is generated
Have ever thought that M2M3 is correct 
I think when M1M3 NONCE is different necessary to force  generation  M1M2 and M2M3

**Comment by ZerBea** [comment]
Please take a look at this warning of hcxpcapngtool:
```
Warning: out of sequence timestamps!
This dump file contains frames with out of sequence timestamps.
That is a bug of the capturing tool.
```
and this warning:
```
Warning: wrong timestamps!
This dump file contains frames with wrong timestamps.
It prevent calculation of EAPOL TIMEOUT values.
That is a bug of the capturing tool.
```

M2 and M3 have the same timestamp and that is impossible:
```
18355	Nov  9, 2021 15:32:54.319506000
18357	Nov  9, 2021 15:32:55.319506000
```
and 
`15:32:53.314387000 `
is more than a minute ago.

Analyzing this would require AI and that is far beyond of the scope of hcxpcapngtool.

To answer your questions:
`Have ever thought that M2M3 is correct?`
Yes

`I think when M1M3 NONCE is different necessary to force generation M1M2 and M2M3?`
No, due to wrong time stamps.
M2 M3 have the the timestamp and that is impossible.
``

**Comment by ZerBea** [comment]
I'll do some more analysis on the pcap to figure out if it is worth it to handle such a bugged dump file.

**Comment by ZerBea** [comment]
Ok, there is no need to do some code changes:
If you set nc to a high value:
`$ hcxpcapngtool --all --nonce-error-corrections=1024`

M1M2 and M2M3 are converted:
```
EAPOL pairs written to 22000 hash file...: 1 (RC checked)
EAPOL pairs written to 22000 hash file...: 1 (RC not checked)
```

and you get both MESSAGE PAIRs:
```
WPA*02*efc80611e186878bf020e8a79a7f8ebf*244e7b5da76e*d4619d1fff42*31373037*68dbb0762c271e65e3e682ab60f0b324371e6f7cec61f748089ee6491faa5b5f*0103007502010a000000000000000000026307b2ff8d7da4a6013918ae243be5cd49e1654e28cd8199e2d998f79c3d9fa6000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001630140100000fac020100000fac040100000fac020800*82
WPA*02*efc80611e186878bf020e8a79a7f8ebf*244e7b5da76e*d4619d1fff42*31373037*86dcd79644644767e2dd867924ea4a45ffa9c786171545f26303ed8ea4d8237b*0103007502010a000000000000000000026307b2ff8d7da4a6013918ae243be5cd49e1654e28cd8199e2d998f79c3d9fa6000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001630140100000fac020100000fac040100000fac020800*80
```

I think we can close this issue report, because hcxpcapngtool convert all hashes as requested by options.

**Comment by ZerBea** [comment]
I added more and more code and options to handle bugged dump files.
Now we have reached the limit; we can do no more.
The next and final step is to educate the user not to use bugged dump tools.

**Comment by LLH-l** [comment]
> I added more and more code and options to handle bugged dump files.
Now we have reached the limit; we can do no more.
The next and final step is to educate the user not to use bugged dump tools.

Well thanks, no worries.  no problem
You already done very good

**Comment by ZerBea** [comment]
Just edited the last comment.
We really reached a point where it doesn't make sense to handle/convert MESSAGE PAIRS.
