### ISSUE TITLE
Nothing find with EWSA when converts hash file hccapx to cap with hcxhash2cap.

### ISSUE THREAD

**Issue by lab37** [ZerBea/hcxtools#299]
EWSA version 7.12
EWSA work well when import  hccapx file .
hcxhash2cap work well when use it convert hccapx to cap.
EWSA can't find any handshak when import  cap that generate in up step.
I test many  hccapx files,   the  result  is  all  same.

Maybe the problem is about EWSA.
Maybe  hcxhash2cap need to add more things to  outfile  when  it  making convert.

**Comment by ZerBea** [comment]
Please notice:
A conversion from pcapng to pcap or cap is always lossy.
A conversion from pcapng, pcap or cap to hccap, hccapx or hc22000 is always lossy.
A conversion from hccap, hccapx or hc22000 to cap cannot recover the lost information!

**Comment by lab37** [comment]
Thanks.
Problem is about EWSA.
Maybe It refused to work because there were only the M1 and M2.

**Comment by ZerBea** [comment]
As I mentioned here:
https://github.com/ZerBea/hcxtools/issues/299#issuecomment-1640969512
Due to limited hash format, the conversion is not loss less
https://hashcat.net/wiki/doku.php?id=hccapx

BTW:
The same applies to cleaned dup files.
