### ISSUE TITLE
 fatal error: openssl/core.h: No such file or directory

### ISSUE THREAD

**Issue by do-ki** [ZerBea/hcxtools#302]
got this error when compiling in Debian buster dependencies has been installed. 

```
pi@raspberry:/opt/hcxtools $ sudo make
cc -O3 -Wall -Wextra -Wpedantic -std=gnu99    -MMD -MF .deps/hcxpcapngtool.d -o hcxpcapngtool hcxpcapngtool.c -lssl -lcrypto -lz  -DVERSION_TAG=\"6.3.1-53-g747e304\" -DVERSION_YEAR=\"2023\" -DWANTZLIB
hcxpcapngtool.c:27:10: fatal error: openssl/core.h: No such file or directory
 #include <openssl/core.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:96: hcxpcapngtool] Error 1

```

**Comment by do-ki** [comment]
the lastest version does not support older OS.

**Comment by ZerBea** [comment]
Correct.
But it shouldn't be a problem, because the current version (Bookworm) uses OpenSSL 3.0 and hcxtools compile fine.
https://packages.debian.org/bookworm/openssl

**Comment by Salty-Coder** [comment]
Im having this same issue...
![image](https://github.com/ZerBea/hcxtools/assets/59771980/97a9fea3-d8fc-44a9-8f52-4591cf96a1ba)

Using Raspberry Pi Zero W Rev 1.1

**Comment by ZerBea** [comment]
hcxtools moved to OpenSSL 3.0. From now on it is mandatory that libopenssl >= 3.0 and openssl-dev >= 3.0 is installed.
This is not the case on your system and make told you that the header file core.h is missing on your system.
You have to update to latest OpenSSL.

That is mentioned in README.md (section requirements), too:
`* libopenssl (>= 3.0) and openssl-dev installed
`
Additional it is mentioned in changelog:
```
10.03.2023
==========
release v6.2.8
moved to EVP API 3.0 (from now on OpenSSL >= 3.0 is mandatory)
```

**Comment by Salty-Coder** [comment]
> hcxtools moved to OpenSSL 3.0. From now on it is mandatory that libopenssl >= 3.0 and openssl-dev >= 3.0 is installed.
> 
> This is not the case on your system and make told you that the header file core.h is missing on your system.
> 
> You have to update to latest OpenSSL.
> 
> 
> 
> That is mentioned in README.md (section requirements), too:
> 
> `* libopenssl (>= 3.0) and openssl-dev installed
> 
> `
> 
> Additional it is mentioned in changelog:
> 
> ```
> 
> 10.03.2023
> 
> ==========
> 
> release v6.2.8
> 
> moved to EVP API 3.0 (from now on OpenSSL >= 3.0 is mandatory)
> 
> ```
> 
> 

I did actually install both of those packages. When trying to repeat install, it says it's already installed, but when running the commands you mentioned in another issue to find OpenSSL files, it doesn't find anything.

**Comment by ZerBea** [comment]
If update to openssl 3.x was successful the header file should be located here:
```
$ locate openssl/core.h
/usr/include/openssl/core.h
```
