### ISSUE TITLE
Windows/MSYS Make support

### ISSUE THREAD

**Issue by fantesykikachu** [ZerBea/hcxtools#311]
@neheb, when you added basic windows I assume you were using meson however if you add linking to winsock2 (-lws2_32) then Make works as well.

**Comment by neheb** [comment]
I'm not interested in Makefile unfortunately.

**Comment by ZerBea** [comment]
As mentioned in README.md, Windows is unsupported, because I don't use proprietary commercial operating systems. 
`Unsupported: Windows OS, macOS, Android, emulators or wrappers!
`

Closed this, because it isn't a bug.
