### ISSUE TITLE
TACACS+ Listing Version Vs. Type

### ISSUE THREAD

**Issue by lakiw** [ZerBea/hcxtools#347]
This is a continuation of the closed issue #230 

I want to start by saying I'm not an expect, so if my read on the situation is wrong, my apologies.

**Describe the bug**
Currently hcxtools doesn't have support for TACACS+ version 2 and 3. Looking through the hcxtools code though, it looks like it uses the "type" field to make the software version determination. For example line 1330 in hcxpcapngtool.c

https://github.com/ZerBea/hcxtools/blob/b034a863a1ec42a933c7676867b70ec39f52b4eb/hcxpcapngtool.c#L1330

This was further confirmed by looking at the tacacsp frame definition in ieee80211.h

https://github.com/ZerBea/hcxtools/blob/b034a863a1ec42a933c7676867b70ec39f52b4eb/include/ieee80211.h#L936

Going into Wireshark, that type does not reference the version of TACACS+ but the packet type which can be authentication, authorization, and, accounting. This can be further seen in the TACACS+ RFC: https://datatracker.ietf.org/doc/html/rfc8907

> type
>
>This is the packet type.
>
>Options are:
>TAC_PLUS_AUTHEN := 0x01 (Authentication)
>TAC_PLUS_AUTHOR := 0x02 (Authorization)
>TAC_PLUS_ACCT := 0x03 (Accounting)

**Expected behavior**
I don't think the different "versions" of TACACS+ that hcxtools is seeing/processing are actually different versions of TACACS+. That also explains why it's been so hard to support authentication token/hash extraction from them. If this data is still helpful to display to users, maybe reclassify the packet types (Authentication/Authorization/Accounting) instead?

**Comment by ZerBea** [comment]
Can you pleas attach an example dump file.

**Comment by ZerBea** [comment]
Should be fixed by latest commit:

```
$ hcxpcapngtool --tacacs-plus=tacacs.16100 tacacs-plus_key-1234.pcap
hcxpcapngtool 6.3.5-12-gfade3e0 reading from tacacs-plus_key-1234.pcap...

summary capture file
--------------------
file name................................: tacacs-plus_key-1234.pcap
version (pcap/cap).......................: 2.4 (very basic format without any additional information)
timestamp minimum (timestamp)............: 04.03.2015 12:57:54 (1425473874)
timestamp maximum (timestamp)............: 04.03.2015 12:57:58 (1425473878)
duration of the dump tool (seconds)......: 3
used capture interfaces..................: 1
link layer header type...................: DLT_EN10MB (1)
endianness (capture system)..............: little endian
packets inside...........................: 16
IPv4 (total).............................: 16
TCP (total)..............................: 16
TACACS+ v1...............................: 6
TACACS+ AUTHEN...........................: 6
TACACS+ written..........................: 6
EAPOL ANONCE error corrections (NC)......: not detected

Information: limited dump file format detected!
This file format is a very basic format to save captured network data.
It is recommended to use PCAP Next Generation dump file format (or pcapng for short) instead. The PCAP Next Generation dump file format is an attempt to overcome the limitations of the currently widely used (but very limited) libpcap (cap, pcap) format.
https://www.wireshark.org/docs/wsug_html_chunked/AppFiles.html#ChAppFilesCaptureFilesSection
https://github.com/pcapng/pcapng


session summary
---------------
processed cap files...................: 1
```

**Comment by ZerBea** [comment]
Maybe there is something different between the configuration files.
Attached my diff.
`./scripts/diffconfig.sh > diffconfig`
[diffconfig.zip](https://github.com/user-attachments/files/18218214/diffconfig.zip)

**Comment by lakiw** [comment]
My apologies. This came up on the hashcat discord channel.  Based on your comment I doublechecked and I was viewing an old branch of hcxpcapngtool.c and you are 100% right that you had already fixed this problem. I really should have checked that I was on the Master branch and I apologize for wasting your time on this. Thank you very much for your kind response though!. I'm closing this issue since it's not an issue anymore.
