### ISSUE TITLE
not able to install 

### ISSUE THREAD

**Issue by patkszen** [ZerBea/hcxtools#35]
not able to perform make, trying on the below:
Linux version 4.14.0-kali3-amd64 (devel@kali.org) (gcc version 7.2.0 (Debian 7.2.0-18)) #1 SMP Debian 4.14.12-2kali1 (2018-01-08)

result: 

`~/Desktop/WIFI/Hashcat/hcxtools# make
gcc -std=gnu99 -O3 -Wall -Wextra -o wlandump-ng wlandump-ng.c -lpcap -lrt 
wlandump-ng.c:23:10: fatal error: pcap.h: No such file or directory
 #include <pcap.h>
          ^~~~~~~~
compilation terminated.
Makefile:34: recipe for target 'build' failed
make: *** [build] Error 1
`

**Comment by ZerBea** [comment]
Consider also to install hcxdumptool from here:
https://github.com/ZerBea/hcxdumptool
hcxdumptool doesn't require libpcap and is the successor of wlandump-ng.
Please close issue, if everything's working and if the installation was successful,

**Comment by Aspect9** [comment]
[](url) - cant seem to initiate hcxtools gui thingy - mmmm - ?

**Comment by ZerBea** [comment]
That is correct, because hcxtools are commandline tools.
There is no GUI.

**Comment by Mohammadkhalil92** [comment]
i have also this problem to install hcxtools
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/hcxpcaptool.d -o hcxpcaptool hcxpcaptool.c -lz -lcrypto 
In file included from hcxpcaptool.c:35:
include/gzops.c:1:10: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
          ^~~~~~~~
compilation terminated.
make: *** [Makefile:81: hcxpcaptool] Error 1

**Comment by ZerBea** [comment]
You must install zlib devel.
https://stackoverflow.com/questions/36374267/how-to-fix-fatal-error-zlib-h-no-such-file-or-directory?rq=1
and from the README.md:
To install requirements on Kali use the following 'apt-get install libcurl4-openssl-dev libssl-dev zlib1g-dev libpcap-dev'

**Comment by InterCeptor0748** [comment]
Ehhhh, i had sorta the same problem. I was trying to broadcast my school's network, to view all connected devices. I was using wifite to try and capture the packet with the password, or, pmkid, and i needed these tools - i tried to use " git clone" yet the repository wasn't found... i also tried sudo apt-get install hcxpcaptool and things alike.

**Comment by ZerBea** [comment]
git clone https://github.com/ZerBea/hcxtools
git clone https://github.com/ZerBea/hcxdumptool

Read more how to use git here:
https://git-scm.com/docs/git-clone


sudo apt-get .... is dependent on distribution. Please ask the maintainer of your distribution.

**Comment by OnyxM** [comment]
Hi. I've an error while trying to do "make" on hcxtools:
**include/gzops.c:1:10: fatal error: zlib.h: Aucun fichier ou dossier de ce type
#include <zlib.h>**
Need some help please. I'm using 4.18.0-kali3-amd64

**Comment by chawwk53** [comment]
If you install all the libraries everything will work fine.... I just did it

**Comment by chawwk53** [comment]
I used WiFi tell to crack a password... if pixiedust doesn't do it it goes next to pmkid attack... And uses a default dict..or wordlist

**Comment by Samir7885** [comment]
I had the same problem but, here's the solution. Use command : 
  apt-get install libcurl4-openssl-dev libssl-dev zlib1g-dev libpcap-dev

And the "make install"

**Comment by ZerBea** [comment]
As of todays update (v 5.1.1), libpcap-dev is no longer needed. I got rid of that dependency.
From new README.md:
Requirements
* Linux (recommended Arch Linux, but other distros should work, too (no support for other distributions).
* libopenssl and openssl-dev installed
* librt and librt-dev installed (should be installed by default)
* zlib and zlib-dev installed (for gzip compressed cap/pcap/pcapng files)
* libcurl and curl-dev installed (used by whoismac and wlancap2wpasec)
* libpthread and pthread-dev installed (used by hcxhashcattool)
To install requirements on Kali use the following 'apt-get install libcurl4-openssl-dev libssl-dev zlib1g-dev'

**Comment by Emirdeg** [comment]
It cant localise the packages when I try to download the requirements

**Comment by Emirdeg** [comment]
I changed the source list from which kali dowwnloads from to kali-rolling then it worked. Here is how to do it:

https://www.youtube.com/watch?v=jcFqvze2xJU

**Comment by laxuz** [comment]
apakah hcxtools hanya berjalan di kali linux saja?

**Comment by shash95wat** [comment]
> sudo apt install libpcap-dev

it is showing unabel to locate package
k

**Comment by ZerBea** [comment]
libpcap-dev is no longer needed!

**Comment by buddhimariner** [comment]
my operating system details 
Static hostname: kali
         Icon name: computer-laptop
           Chassis: laptop
        Machine ID: 17db5868fefe4c2096b430af45dc642f
           Boot ID: fd1db360ad824801b4fe6932e70b132a
  Operating System: Kali GNU/Linux Rolling
            Kernel: Linux 4.18.0-kali2-amd64
      Architecture: x86-64
Every one please help me I tried to install hcxpcaptool its not installing.It shows this error,please help me solve this error
root@kali:~# git clone https://github.com/ZerBea/hcxtools.git
fatal: destination path 'hcxtools' already exists and is not an empty directory.
root@kali:~# cd hcxtools
root@kali:~/hcxtools# make
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/hcxpcaptool.d -o hcxpcaptool hcxpcaptool.c -lz -lcrypto 
hcxpcaptool.c:16:10: fatal error: openssl/sha.h: No such file or directory
 #include <openssl/sha.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:79: hcxpcaptool] Error 1
root@kali:~/hcxtools# sudo make install
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/hcxpcaptool.d -o hcxpcaptool hcxpcaptool.c -lz -lcrypto 
hcxpcaptool.c:16:10: fatal error: openssl/sha.h: No such file or directory
 #include <openssl/sha.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:79: hcxpcaptool] Error 1

**Comment by ZerBea** [comment]
Probably you are missing the openssl header files. Depending on your distribution (KALI) this package might have a different name, mostly it's something like openssl-dev or libcurl4-openssl-dev. After you installed the openssl header files, the compiler should be able to find openssl/sha.h.

Get more information about KALI packages here:
https://pkg.kali.org/pkg/openssl

**Comment by buddhimariner** [comment]
Sir I`m new to kali linux and need your help please guide me how to install openssl files
apt-get install openssl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
openssl is already the newest version (1.1.0h-4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

 I tried to update and install openssl header files it was unsucessful

**Comment by ZerBea** [comment]
apt-get install openssl
is not enough.
You must install the corespondending header files, too. Usually they have an extension like -dev.
for example:
apt-get install libssl-dev
or what ever the package name is in KALI....
I don't use KALI.

**Comment by wdccomhckr84** [comment]
root@atrophy:~/hcxtools# make
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/hcxpcaptool.d -o hcxpcaptool hcxpcaptool.c -lz -lcrypto 
hcxpcaptool.c:16:10: fatal error: openssl/sha.h: No existe el fichero o el directorio
 #include <openssl/sha.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:79: hcxpcaptool] Error 1

**Comment by wdccomhckr84** [comment]
tengo problema para instalar este software

**Comment by ZerBea** [comment]
Cual sistema operativo? KALI?

**Comment by kartik2502** [comment]
root@Rosen:~# cd hcxtools
root@Rosen:~/hcxtools# make
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/hcxpcaptool.d -o hcxpcaptool hcxpcaptool.c -lz -lcrypto 
hcxpcaptool.c:16:10: fatal error: openssl/sha.h: Tidak ada berkas atau direktori seperti itu
 #include <openssl/sha.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:79: hcxpcaptool] Error 1
root@Rosen:~/hcxtools# 
??
help me please

**Comment by ZerBea** [comment]
Missing dependency. You must(!) install the dev files to compile hcxtools:
* libopenssl and openssl-dev installed
* librt and librt-dev installed (should be installed by default)
* zlib and zlib-dev installed (for gzip compressed cap/pcap/pcapng files)
* libcurl and curl-dev installed (used by whoismac and wlancap2wpasec)
* libpthread and pthread-dev installed (used by hcxhashcattool)
To install requirements on Kali use the following 'apt-get install libcurl4-openssl-dev libssl-dev zlib1g-dev'

**Comment by Goldleman** [comment]
I'm having the same problem.

Help me

![Screenshot from 2020-05-19 10-07-19](https://user-images.githubusercontent.com/62600857/82366995-05274980-9a0b-11ea-8148-3bf500e55b92.png)

**Comment by strasharo** [comment]
install zlib-dev

**Comment by ZerBea** [comment]
As @strasharo mentioned: Solve the dependencies - in your case install zlib development files.

From README.md:
```
Requirements
--------------
* Linux (recommended Arch Linux, but other distros should work, too (no support for other distributions).
* libopenssl and openssl-dev installed
* librt and librt-dev installed (should be installed by default)
* zlib and zlib-dev installed (for gzip compressed cap/pcap/pcapng files)
* libcurl and curl-dev installed (used by whoismac and wlancap2wpasec)
* libpthread and pthread-dev installed (used by hcxhashcattool)
```
Use your  package manager (depending on your distribution: apt, synaptic, yum, ... - or what ever) to solve the dependencies.
zlib should be an integral part of every distribution:
https://www.zlib.net/ 

BTW:
I never understood, why some distributions need to install the development files separately. Unfortunately, it looks like you're running one of this distributions.

**Comment by Goldleman** [comment]
Make Install Error
![IMG_055](https://user-images.githubusercontent.com/62600857/82443508-875e4f00-9a99-11ea-97a1-fc97bca9d823.png)

**Comment by ZerBea** [comment]
As a normal user, you don't have the permission to install files.
sudo should do the trick:
Do the following steps:
$ make
$ sudo make install

From README.md:
```
make
make install (as super user)
```

**Comment by jhonnycalmurself** [comment]
unable to install hcxtools in kali linux

please help me.

┌──(kali㉿kali)-[~]
└─$ sudo su
[sudo] password for kali: 
┌──(root💀kali)-[/home/kali]
└─# git clone https://github.com/ZerBea/hcxtools.git                       
fatal: destination path 'hcxtools' already exists and is not an empty directory.
                                                                            
┌──(root💀kali)-[/home/kali]
└─# cd hcxtools                                                       128 ⨯
                                                                            
┌──(root💀kali)-[/home/kali/hcxtools]
└─# sudo make && sudo make install
make: pkg-config: No such file or directory
make: pkg-config: No such file or directory
make: pkg-config: No such file or directory
make: pkg-config: No such file or directory
cc -O3 -Wall -Wextra -std=gnu99    -MMD -MF .deps/hcxpcapngtool.d -o hcxpcapngtool hcxpcapngtool.c    -DVERSION_TAG=\"6.1.4-16-gcc3bff5\" -DVERSION_YEAR=\"2020\"
/usr/bin/ld: /tmp/ccO0B8GT.o: in function `getpmkid':
hcxpcapngtool.c:(.text+0x1ab7): undefined reference to `PKCS5_PBKDF2_HMAC_SHA1'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x1b0d): undefined reference to `EVP_sha1'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x1b37): undefined reference to `HMAC'
/usr/bin/ld: /tmp/ccO0B8GT.o: in function `initlists':
hcxpcapngtool.c:(.text+0x2e25): undefined reference to `OpenSSL_version_num'
/usr/bin/ld: /tmp/ccO0B8GT.o: in function `outputeapmschapv2hashlist':
hcxpcapngtool.c:(.text+0x4755): undefined reference to `SHA1_Init'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x476a): undefined reference to `SHA1_Update'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x477f): undefined reference to `SHA1_Update'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x4795): undefined reference to `SHA1_Update'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x47a8): undefined reference to `SHA1_Final'
/usr/bin/ld: /tmp/ccO0B8GT.o: in function `addpmkid':
hcxpcapngtool.c:(.text+0x4c11): undefined reference to `EVP_sha1'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x4c3f): undefined reference to `HMAC'
/usr/bin/ld: /tmp/ccO0B8GT.o: in function `decompressgz':
hcxpcapngtool.c:(.text+0x61f0): undefined reference to `inflateInit2_'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x62b4): undefined reference to `inflate'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x62c6): undefined reference to `inflateEnd'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x6304): undefined reference to `inflateEnd'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x6339): undefined reference to `inflateEnd'
/usr/bin/ld: /tmp/ccO0B8GT.o: in function `omac1_aes_128_vector':
hcxpcapngtool.c:(.text+0x64b8): undefined reference to `CMAC_CTX_new'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x64cd): undefined reference to `EVP_aes_128_cbc'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x64e7): undefined reference to `CMAC_Init'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x6530): undefined reference to `CMAC_Update'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x6540): undefined reference to `CMAC_CTX_free'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x656a): undefined reference to `CMAC_Final'
/usr/bin/ld: /tmp/ccO0B8GT.o: in function `testeapolpmk':
hcxpcapngtool.c:(.text+0x678f): undefined reference to `EVP_sha1'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x67bb): undefined reference to `HMAC'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x67e1): undefined reference to `EVP_sha1'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x680c): undefined reference to `HMAC'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x69cb): undefined reference to `EVP_sha256'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x69f5): undefined reference to `HMAC'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x6a71): undefined reference to `EVP_md5'
/usr/bin/ld: /tmp/ccO0B8GT.o: in function `gethandshake':
hcxpcapngtool.c:(.text+0x82ae): undefined reference to `PKCS5_PBKDF2_HMAC_SHA1'
collect2: error: ld returned 1 exit status
make: *** No rule to make target 'hcxpcapngtool', needed by 'build'.  Stop.

**Comment by ZerBea** [comment]
Please comment output of
$ uname -a
to see what version you are using.
Make sure, your system is updated to latest version.
Read more here:
https://linuxconfig.org/how-to-update-kali-linux
If that doesn't work, your KALI is broken and you have to install it again.  I assume your system is broken!

Now Clean up your folders:
rm -r hcxtools
rm -r hcxdumptool

Than do a fresh git clone:
git clone https://github.com/ZerBea/hcxtools
git clone https://github.com/ZerBea/hcxdumptool

Install dependencies as mentioned in README.md
$ apt-get install libcurl4-openssl-dev libssl-dev zlib1g-dev

Now you're ready to compile the tools:
cd hcxtools
$ sudo make
$ sudo make install
$ cd ../hcxdumptool
$ sudo make
$ sudo make install
$ cd ..

After this, you are ready to use hcxtools.

**Comment by jhonnycalmurself** [comment]
┌──(kali㉿kali)-[~]
└─$ uname -a                                                          127 ⨯
Linux kali 5.9.0-kali1-amd64 #1 SMP Debian 5.9.1-1kali2 (2020-10-29) x86_64 GNU/Linux

**Comment by jhonnycalmurself** [comment]
now I tried with different command
                                                                                                                                                           
┌──(root💀kali)-[/home/kali]
└─# cat /etc/apt/sources.list
# See https://www.kali.org/docs/general-use/kali-linux-sources-list-repositories/
deb http://http.kali.org/kali kali-rolling main contrib non-free

# Additional line for source packages
# deb-src http://http.kali.org/kali kali-rolling main contrib non-free
                                                                                                                                                           
┌──(root💀kali)-[/home/kali]
└─# sudo apt uptdate
E: Invalid operation uptdate

**Comment by ZerBea** [comment]
As assumed, your KALI installation is broken.

**Comment by ZerBea** [comment]
That is typical for KALI:
https://kalitut.com/how-to-update-kali-linux-and-fix-update/

**Comment by ZerBea** [comment]
Running a not broken KALI, installation is working fine:
Dependencies not installed:
https://www.youtube.com/watch?v=qwqaLLY07tI

Dependencies already installed:
https://www.youtube.com/watch?v=ntDnnOG1K78

**Comment by RedTeamMagic** [comment]
I am running into some issues installing...
Any idea what I might be missing? I believe all dependencies are installed.

uname -a
Linux 08012061 4.15.0-64-generic #73~16.04.1-Ubuntu SMP Fri Sep 13 09:56:18 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

/hcxtools# make
cc -O3 -Wall -Wextra -std=gnu99    -MMD -MF .deps/hcxpcapngtool.d -o hcxpcapngtool hcxpcapngtool.c -lssl -lcrypto -lz  -DVERSION_TAG=\"6.1.4-16-gcc3bff5\" -DVERSION_YEAR=\"2020\"
hcxpcapngtool.c: In function ‘initlists’:
hcxpcapngtool.c:366:18: warning: implicit declaration of function ‘OpenSSL_version_num’ [-Wimplicit-function-declaration]
 opensslversion = OpenSSL_version_num();
                  ^
/tmp/ccbahBSu.o: In function `initlists':
hcxpcapngtool.c:(.text+0x3dbc): undefined reference to `OpenSSL_version_num'
collect2: error: ld returned 1 exit status
make: *** No rule to make target 'hcxpcapngtool', needed by 'build'.  Stop.


hcxdumptool# make install
cc -O3 -Wall -Wextra -std=gnu99  -o hcxpioff hcxpioff.c  -DVERSION_TAG=\"6.1.4-1-g9c03887\" -DVERSION_YEAR=\"2020\"
cc -O3 -Wall -Wextra -std=gnu99  -o hcxdumptool hcxdumptool.c  -lcrypto -lssl -DVERSION_TAG=\"6.1.4-1-g9c03887\" -DVERSION_YEAR=\"2020\"
hcxdumptool.c: In function ‘globalinit’:
hcxdumptool.c:6936:18: warning: implicit declaration of function ‘OpenSSL_version_num’ [-Wimplicit-function-declaration]
 opensslversion = OpenSSL_version_num();
                  ^
/tmp/ccFVUsAe.o: In function `globalinit':
hcxdumptool.c:(.text+0x43be): undefined reference to `OpenSSL_version_num'
collect2: error: ld returned 1 exit status
Makefile:31: recipe for target 'build' failed
make: *** [build] Error 1

**Comment by ZerBea** [comment]
You are running an ancient Linux kernel. The kernel (4.15.0-64-) is EOL and no longer supported:
https://www.kernel.org/
Additional, Ubuntu 16.04. will reach EOL in a few month. 
https://phoenixnap.com/kb/ubuntu-16-04-end-of-life

I recommend to update your system.

**Comment by ZerBea** [comment]
BTW:
Have you installed OpenSSL as described in README.md?
`$ sudo apt-get install libcurl4-openssl-dev libssl-dev zlib1g-dev
`

I assume, your OpenSSL version is ancient, too.
Please comment output of
`$ openssl version
`
This is the latest version:
```
$ openssl version
OpenSSL 1.1.1h  22 Sep 2020
```

**Comment by RedTeamMagic** [comment]
Thank you for your response. Openssl was definitely the issue for hxctools
I updated manually and the install worked

openssl version
OpenSSL 1.1.1h  22 Sep 2020

**However, hcsdumptool is still having some issues with the OpenSSL version.**
Do you see anything I might be missing here?

hcxdumptool# make install
cc -O3 -Wall -Wextra -std=gnu99  -o hcxpioff hcxpioff.c  -DVERSION_TAG=\"6.1.4-1-g9c03887\" -DVERSION_YEAR=\"2020\"
cc -O3 -Wall -Wextra -std=gnu99  -o hcxdumptool hcxdumptool.c  -lcrypto -lssl -DVERSION_TAG=\"6.1.4-1-g9c03887\" -DVERSION_YEAR=\"2020\"
/tmp/ccLk2Z9y.o: In function `globalinit':
hcxdumptool.c:(.text+0x43b7): undefined reference to `OpenSSL_version_num'
hcxdumptool.c:(.text+0x4843): undefined reference to `OPENSSL_init_ssl'
hcxdumptool.c:(.text+0x484c): undefined reference to `OPENSSL_init_ssl'
hcxdumptool.c:(.text+0x4851): undefined reference to `TLS_server_method'
/tmp/ccLk2Z9y.o: In function `process80211eap':
hcxdumptool.c:(.text.unlikely+0x2c76): undefined reference to `SSL_is_init_finished'
hcxdumptool.c:(.text.unlikely+0x2db6): undefined reference to `SSL_in_init'
hcxdumptool.c:(.text.unlikely+0x2dc9): undefined reference to `SSL_is_init_finished'
hcxdumptool.c:(.text.unlikely+0x2fc8): undefined reference to `SSL_is_init_finished'
collect2: error: ld returned 1 exit status
Makefile:31: recipe for target 'build' failed
make: *** [build] Error 1

**Comment by ZerBea** [comment]
Correct, you are missing the development files (includes).. You have to install them ,too.

**Comment by ZerBea** [comment]
gcc told you that the header files are missing by this error message:
`undefined reference to ...`

**Comment by RedTeamMagic** [comment]
Thanks again for your response.

So I do have the development headers installed, but it looks like they are the wrong version (1.0.2g) which might be the issue?

sudo apt -y install libssl-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libssl-dev is already the newest version (1.0.2g-1ubuntu4.18).
The following packages were automatically installed and are no longer required:
  libevent-core-2.0-5 libgoogle-perftools4 libtcmalloc-minimal4
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.

Even though I manually installed openssl 1.1.1h, the development headers didn't update?
Do you know what else I might be doing wrong?
I appreciate your support.

**Comment by RedTeamMagic** [comment]
ldd $(which openssl)
	linux-vdso.so.1 =>  (0x00007ffd810f4000)
	libssl.so.1.1 => /usr/local/lib/libssl.so.1.1 (0x00007f7e28dd8000)
	libcrypto.so.1.1 => /usr/local/lib/libcrypto.so.1.1 (0x00007f7e288e5000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7e286c8000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7e282fe000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f7e280fa000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7e2906c000)

**Comment by ZerBea** [comment]
You're running into a versioning conflict, by installing libraries manually and that will end up in a dependency hell!
16.04. doesn't provide the new dev files (that is UBUNTU policy) and you have to install them manually, too.
I can't recommend this, because it will destroy the package system, sooner or later.
Even if you are able to manage this, you'll run into the next dependency. This time it will be gcc:
$ gcc --version
gcc (GCC) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.

**Comment by RedTeamMagic** [comment]
gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


Unfortunately, starting fresh with a new version of Ubuntu is not an option, as the device I'm trying to run hcxdumptool on is physical at a remote location.
What's weird is that hxctools was getting the same error, but updating openssl to v1.1.1h fixed it. For some reason, hcxdumptool is not working the same

**Comment by ZerBea** [comment]
hcxdumptool doesn't use pkg-config. Maybe this could be the problem.

**Comment by ZerBea** [comment]
Give me some minutes to try something.

**Comment by ZerBea** [comment]
Pushed an update of hcxdumptool. Now we're using pkg-config, too. Please try.

**Comment by RedTeamMagic** [comment]
Dude, you're incredible!
Thanks for being so responsive!!
I owe you big time

make
mkdir -p .deps
cc -O3 -Wall -Wextra -std=gnu99 -I/usr/local/include  -MMD -MF .deps/hcxdumptool.d -o hcxdumptool hcxdumptool.c -L/usr/local/lib -lssl -lcrypto  -DVERSION_TAG=\"6.1.4-3-g55b5135\" -DVERSION_YEAR=\"2020\"
cc -O3 -Wall -Wextra -std=gnu99   -MMD -MF .deps/hcxpioff.d -o hcxpioff hcxpioff.c   -DVERSION_TAG=\"6.1.4-3-g55b5135\" -DVERSION_YEAR=\"2020\"

make install
install  -D -m 0755 hcxdumptool /usr/local/bin/hcxdumptool
install  -D -m 0755 hcxpioff /usr/local/bin/hcxpioff

hcxdumptool --help
hcxdumptool 6.1.4-3-g55b5135  (C) 2020 ZeroBeat
usage  : hcxdumptool <options>

**Comment by ZerBea** [comment]
Glad to hear that it is working, now. Moving to pkgconf did the trick.

**Comment by MorphinesSupreme** [comment]
Hello I'm relatively new to KALI but I've been having what I think could be a similar issue? I'm not very sure but I've installed and updated all required dependencies and still get this issue.


└─$ sudo uname -a               
Linux KALIMK2 5.9.0-kali4-amd64 #1 SMP Debian 5.9.11-1kali1 (2020-12-01) x86_64 GNU/Linux
                                                                                                                                                                                                                                           
└─$ sudo rm -r hcxdumptool
                                                                                                                                                                                                                                           
└─$ sudo rm -r hcxtools   
                                                                                                                                                                                                                                           
└─$ sudo git clone https://github.com/ZerBea/hcxdumptool.git
Cloning into 'hcxdumptool'...
remote: Enumerating objects: 32, done.
remote: Counting objects: 100% (32/32), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 2932 (delta 16), reused 24 (delta 9), pack-reused 2900
Receiving objects: 100% (2932/2932), 1.04 MiB | 1.78 MiB/s, done.
Resolving deltas: 100% (1996/1996), done.
 
└─$ sudo git clone https://github.com/ZerBea/hcxtools.git 
Cloning into 'hcxtools'...
remote: Enumerating objects: 62, done.
remote: Counting objects: 100% (62/62), done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 7511 (delta 32), reused 41 (delta 21), pack-reused 7449
Receiving objects: 100% (7511/7511), 2.30 MiB | 2.65 MiB/s, done.
Resolving deltas: 100% (5216/5216), done.
                                                                                                                                                                                                                                           
└─$ sudo apt-get install libcurl4-openssl-dev libssl-dev zlib1g-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libcurl4-openssl-dev is already the newest version (7.72.0-1).
libssl-dev is already the newest version (1.1.1h-1).
zlib1g-dev is already the newest version (1:1.2.11.dfsg-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
                                                                                                                                                                                                                                           
└─$ cd hcxtools
                                                                                                                                                                                                                                           
└─$ sudo make                                                      
mkdir -p .deps
make: pkg-config: No such file or directory
make: pkg-config: No such file or directory
make: pkg-config: No such file or directory
make: pkg-config: No such file or directory
cc -O3 -Wall -Wextra -std=gnu99    -MMD -MF .deps/hcxpcapngtool.d -o hcxpcapngtool hcxpcapngtool.c    -DVERSION_TAG=\"6.1.4-17-g4a09689\" -DVERSION_YEAR=\"2020\"
/usr/bin/ld: /tmp/ccIK485K.o: in function `getpmkid':
hcxpcapngtool.c:(.text+0x1ab7): undefined reference to `PKCS5_PBKDF2_HMAC_SHA1'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x1b0d): undefined reference to `EVP_sha1'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x1b37): undefined reference to `HMAC'
/usr/bin/ld: /tmp/ccIK485K.o: in function `initlists':
hcxpcapngtool.c:(.text+0x2e25): undefined reference to `OpenSSL_version_num'
/usr/bin/ld: /tmp/ccIK485K.o: in function `outputeapmschapv2hashlist':
hcxpcapngtool.c:(.text+0x4755): undefined reference to `SHA1_Init'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x476a): undefined reference to `SHA1_Update'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x477f): undefined reference to `SHA1_Update'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x4795): undefined reference to `SHA1_Update'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x47a8): undefined reference to `SHA1_Final'
/usr/bin/ld: /tmp/ccIK485K.o: in function `addpmkid':
hcxpcapngtool.c:(.text+0x4c11): undefined reference to `EVP_sha1'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x4c3f): undefined reference to `HMAC'
/usr/bin/ld: /tmp/ccIK485K.o: in function `decompressgz':
hcxpcapngtool.c:(.text+0x61f0): undefined reference to `inflateInit2_'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x62b4): undefined reference to `inflate'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x62c6): undefined reference to `inflateEnd'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x6304): undefined reference to `inflateEnd'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x6339): undefined reference to `inflateEnd'
/usr/bin/ld: /tmp/ccIK485K.o: in function `omac1_aes_128_vector':
hcxpcapngtool.c:(.text+0x64b8): undefined reference to `CMAC_CTX_new'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x64cd): undefined reference to `EVP_aes_128_cbc'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x64e7): undefined reference to `CMAC_Init'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x6530): undefined reference to `CMAC_Update'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x6540): undefined reference to `CMAC_CTX_free'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x656a): undefined reference to `CMAC_Final'
/usr/bin/ld: /tmp/ccIK485K.o: in function `testeapolpmk':
hcxpcapngtool.c:(.text+0x678f): undefined reference to `EVP_sha1'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x67bb): undefined reference to `HMAC'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x67e1): undefined reference to `EVP_sha1'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x680c): undefined reference to `HMAC'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x69cb): undefined reference to `EVP_sha256'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x69f5): undefined reference to `HMAC'
/usr/bin/ld: hcxpcapngtool.c:(.text+0x6a71): undefined reference to `EVP_md5'
/usr/bin/ld: /tmp/ccIK485K.o: in function `gethandshake':
hcxpcapngtool.c:(.text+0x82ae): undefined reference to `PKCS5_PBKDF2_HMAC_SHA1'
collect2: error: ld returned 1 exit status
make: *** [Makefile:113: hcxpcapngtool] Error 1

Any help or insight would be greatly appreciated.

**Comment by ZerBea** [comment]
Using pkg-config makes compiling process a little bit more easy. So I decided to use it for both (hcxtools and hcxdumptool). I'll add a small note to README.md.

**Comment by MorphinesSupreme** [comment]
Thank you very much. You are an absolute legend for being this responsive.

**Comment by ZerBea** [comment]
No problem, you're welcome.
