### ISSUE TITLE
hcxpcaptool - 

### ISSUE THREAD

**Issue by adrastee** [ZerBea/hcxtools#45]
Hello, I've got this problem on Debian:
```
$ ./hcxpcaptool -h
./hcxpcaptool: error while loading shared libraries: libcrypto.so.1.1:
cannot open shared object file: No such file or directory

```

```
$ which openssl
/usr/bin/openssl
```

```
$ ldd /usr/bin/openssl
        linux-vdso.so.1 (0x00007ffecb54a000)
        libssl.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f7ec1fc0000)
        libcrypto.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f7ec1bc3000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f7ec19bf000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7ec1614000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f7ec2221000)
```

Is version **1.1** of libcrypto mandatory ? Or **1.0.0** can work ? If yes, how to configure the makefile ?
Thank you.

**Comment by ZerBea** [comment]
Is version 1.1 of libcrypto mandatory?
No
Or 1.0.0 can work ?
Yes
The issue is related to you environment and not to hcxtools

Arch Linux:
$ which openssl
/usr/bin/openssl
$ ldd /usr/bin/openssl
	linux-vdso.so.1 (0x00007ffcb17eb000)
	libssl.so.1.1 => /usr/lib/libssl.so.1.1 (0x00007f2ed8d87000)
	libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1 (0x00007f2ed890a000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f2ed86ec000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f2ed8330000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f2ed812c000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f2ed928f000)

The lib is expected to find in  /usr/lib and not in /usr/lib/x86_64-linux-gnu/
https://github.com/openssl/openssl/issues/4824

**Comment by adrastee** [comment]
Thanks, alright, it founds libcrypto now, but a new error raise:
```
gcc -std=gnu99 -O3 -Wall -Wextra -o hcxpcaptool hcxpcaptool.c -lz -L/usr/lib/x86_64-linux-gnu -I/usr/include/openssl
hcxpcaptool.c:16:25: fatal error: openssl/sha.h: No such file or directory

```
But this file exists:
```
$ file /usr/include/openssl/sha*
/usr/include/openssl/sha.h: C source, ASCII text
```

**Comment by ZerBea** [comment]
It seems, your openssl installation is completely broken:
Please reinstall libssl-dev
https://unix.stackexchange.com/questions/87458/make-fatal-error-openssl-sha-h-no-such-file-or-directory

**Comment by adrastee** [comment]
Yes it seems so I install arch linux in a VM and compiled hcxpcaptool with "-static" gcc flag for it to be 'portable'.
Do you see any issue with this?
It seems to work great on my Debian so far!

**Comment by ZerBea** [comment]
Debian is ok so far (and other distro's, like UBUNTU, too). First try to fix your broken environment.

**Comment by adrastee** [comment]
Thanks for all!
