### ISSUE TITLE
Performance bottleneck in addapstaessid

### ISSUE THREAD

**Issue by ChrisLundquist** [ZerBea/hcxtools#46]
The algorithm here is accidentally N^2 with respect to pcap length and gets "slower and slower" as it continues to run.

```
-rw-r--r-- 1 clundquist clundquist  44G Aug  4 12:36 Kismet-20180709-18-35-12-1.pcapdump
```

```
start reading from /srv/wifi/Kismet-20180709-18-35-12-1.pcapdump
28100000 packets processed - be patient!
45900000 packets processed - be patient!
51500000 packets processed - be patient!
56300000 packets processed - be patient!
69700000 packets processed - be patient!
75700000 packets processed - be patient!
111000000 packets processed - be patient!
122000000 packets processed - be patient!
156200000 packets processed - be patient!
163500000 packets processed - be patient!
164600000 packets processed - be patient!
```

```
# top
29419 clundqu+  20   0   50412  35880   2436 R 100.0  0.1  68:48.60 hcxpcaptool                                                                                                                            
```  

```
# sudo perf top
92.85%  hcxpcaptool              [.] addapstaessid                                                                                                                                                       
```

```
  4.68 │ 50:   lea    0x1(%rbp),%rax                                                                                                                                                                       ▒
  2.52 │       add    $0x36,%rbx                                                                                                                                                                           ▒
  3.62 │       cmp    %r12,%rax                                                                                                                                                                            ▒
       │     ↓ je     d0                                                                                                                                                                                   ▒
  5.79 │       mov    %rax,%rbp                                                                                                                                                                            ▒
  4.53 │ 60:   cmp    %r13b,0x15(%rbx)                                                                                                                                                                     ▒
 64.78 │     ↑ jne    50                                                                                                                                                                                   ▒
 12.21 │       mov    0x9(%rbx),%edi                                                                                                                                                                       ▒
  0.05 │       cmp    %edi,(%r8)                                                                                                                                                                           ▒
  1.39 │     ↑ jne    50   
```

The above disassembler appears to be this hot code path (I haven't recompiled with debug symbols to verify since I want to let the run finish).
```
2487   zeiger = apstaessidliste;
2488   for (c = 0; c < apstaessidcount; c++) {
2489     if ((essidlen == zeiger->essidlen) &&
2490         (memcmp(mac_ap, zeiger->mac_ap, 6) == 0) &&
2491         (memcmp(mac_sta, zeiger->mac_sta, 6) == 0) &&
2492         (memcmp(essid, zeiger->essid, zeiger->essidlen) == 0)) {
2493       zeiger->status |= status;
2494       return;
2495     }
2496     zeiger++;
2497   }
```

The algorithm here is roughly:
* Check if our global list is allocated
  * if it isn't allocated, make it now
* Check if the given node is our our list (linear search)
* If we didn't find it in our list realloc our list to 1 size bigger to make room (expensive as our list grows)
* Assign our newest node at the end of the list

This boils down to "Find or Create".

We should update this algorithm to something closer to:

* On start allocate our collection (to remove the branch from a hot code path)
* use `bsearch` for the node
  * If we find the node, we're done
* Check if the collection has room (size == capacity)
  * If we don't have room, allocate more slots, grow by perhaps `max(8, capacity / 4)`, update our capacity
* If we don't find the node append it (ideally we would want an insertion sort)
* qsort (ideally insertion would be better) the collection so that bsearch works next call

Alternatively we could use a tree `tsearch` and friends, but iterating gets a little more complicated.

**Comment by ZerBea** [comment]
You're absolute right, we must fix this.
Unfortunately that isn't the only bottleneck.
We have to run through  the whole file on every M2, every M3, every M4.
Then we have to find all ESSIDs for all handshakes.
And if you use -O option (all handshakes), speed drop on big cap files is really ugly.
BTW:
running hcxpcaptool on merged cap files can be lead to unwanted results if
-ESSID is damaged (and we have seen thousands of them in wpa-sec database)
-ESSID change (we have also seen thousands of them in wpa-sec database)

Also we could be faster if all caps will include a valid timestamp. Unfortunately there is a really ugly tool
(wpaclean) which prevent this. But we must take care about that dinosour. Many submitted caps are cleanded deadly.

Nevertheless, every idea/help ist welcome.

**Comment by ChrisLundquist** [comment]
I took a stab at the idea here:
https://github.com/ChrisLundquist/hcxtools/blob/clundquist/speedup/hcxpcaptool.c#L2468-L2554

It simplified the code but didn't speed it up.
Using the qsort approach made things worse because of our read/write ratio.
So, we really need O(log(n)) insertion time.

Since we access this list in a number of places (and expect to iterate it in a contiguous for loop), I think we'd want to build an index and maintain it in the function. We could do this with a tree or hash (`tsearch` and `hsearch` before `lsearch`) using the 4 fields we care about.

The index would map our unique key to a pointer into our existing list.

As another note, `clang-format` really helped me on my branch to try this out. I would encourage you to find a style you like and run it on your files. One thing that got me is it wants to sort our includes by default. It looks like we're including `.c` files which are order dependent, so you'll have to disable that.

**Comment by ZerBea** [comment]
Thanks. I sent you a mail.
"It simplified the code but didn't speed it up"
Unfortunately your solution is slower.

**Comment by ZerBea** [comment]
Doing speed improvements:
old:
real	0m35,652s
user	0m35,365s
sys	0m0,246s

new:
real	0m9,393s
user	0m9,214s
sys	0m0,173s

The price we have to pay for that: twice memory consumption.

**Comment by ChrisLundquist** [comment]
Right, I said it was still slower. The slowdown comes from factoring `compare_stations` into a function call.
There will be a speedup if we add an index into the data like I suggest.

**Comment by ChrisLundquist** [comment]
It looks like https://github.com/ZerBea/hcxtools/commit/a1333d1939d73ce53a5a5234a19f1e65585b9ed8
implements `uniq` which is a little confusing because the cold code (the for loop) would only add it if we didn't find a match.

We can cut down on the memory usage by using an index of pointers, and even skip the `qsort` call.

**Comment by ZerBea** [comment]
We can give "tree a try", if it will be much faster and not complexer.

**Comment by ZerBea** [comment]
But it's not on top of my priority list. As I wrote in my mail:
A good dumper should be able to use some simple packet filters.
hcxdumptool does this and we can can expect it from state of the art tools.

cap files like this one are horrible: 1 beacon, 11522 deauthentications for only 2 handshakes
summary:                                        
file name....................: test.cap
file type....................: pcap 2.4
file hardware information....: unknown
file os information..........: unknown
file application information.: unknown
network type.................: DLT_IEEE802_11 (105)
endianess....................: little endian
read errors..................: flawless
packets inside...............: 61661
skipped packets..............: 0
packets with FCS.............: 0
beacons (with ESSID inside)..: 1
probe responses..............: 285
association requests.........: 1
association responses........: 2
authentications (OPEN SYSTEM): 5
authentications (BROADCOM)...: 5
deauthentications............: 11522
action packets...............: 9
EAPOL packets................: 8
EAPOL PMKIDs.................: 2
best handshakes..............: 2 (ap-less: 0)

or that one:
summary:                                        
file name....................: test1.cap
file type....................: pcap 2.4
file hardware information....: unknown
file os information..........: unknown
file application information.: unknown
network type.................: DLT_IEEE802_11 (105)
endianess....................: little endian
read errors..................: flawless
packets inside...............: 3
skipped packets..............: 0
packets with FCS.............: 0
warning......................: zero value timestamps detected
beacons (with ESSID inside)..: 1
EAPOL packets................: 2
best handshakes..............: 1 (ap-less: 0)

or this one
summary: 
file name....................: test2.cap
file type....................: pcap 2.4
file hardware information....: unknown
file os information..........: unknown
file application information.: unknown
network type.................: DLT_IEEE802_11 (105)
endianess....................: little endian
read errors..................: yes
packets inside...............: 14276
skipped packets..............: 0
packets with FCS.............: 0
beacons (with ESSID inside)..: 1
probe requests...............: 17
probe responses..............: 123
association requests.........: 1
association responses........: 3
authentications (OPEN SYSTEM): 15
deauthentications............: 6414
action packets...............: 65
EAPOL packets................: 49
IPv4 packets.................: 12
IPv6 packets.................: 106
ICMPv6 packets...............: 31
best handshakes..............: 1 (ap-less: 0)

**Comment by ChrisLundquist** [comment]
`master` is much improved today, nice work!

https://github.com/ChrisLundquist/hcxtools/blob/clundquist/speedup/hcxpcaptool.c#L2468-L2556
Is now the same speed as the latest master.

When I opened the issue my test took around 90 seconds. Now my branch and `master` both take about 20 seconds.

Even on super large pcaps like the 44G one did when I opened this issue takes ~5 minutes on both branches today, when yesterday on master they took an hour.

If you have an index, you'll need to rebuild it if you alter `apstaessidliste` with `qsort` or `realloc`

The good news is, we can use these techniques *together*. If I understand your latest commit for `cleanapstaessid` it removes unneeded data. Having less data will always be faster. Using a O(Log(n)) search on less data is even better than a O(N) search.

I bet if we put these two approaches together we could make things even faster.

```
$ time  ./hcxpcaptool -z speed-test.16800 /srv/wifi/home-01.pcapdump
start reading from /srv/wifi/home-01.pcapdump
                                                
summary:                                        
--------
file name....................: home-01.pcapdump
file type....................: pcap 2.4
file hardware information....: unknown
file os information..........: unknown
file application information.: unknown
network type.................: DLT_IEEE802_11 (105)
endianess....................: little endian
read errors..................: flawless
packets inside...............: 11246612
skipped packets..............: 0
packets with FCS.............: 0
WDS packets..................: 13987
beacons (with ESSID inside)..: 460
probe requests...............: 186988
probe responses..............: 1452736
association requests.........: 49
association responses........: 267
reassociation requests.......: 13
reassociation responses......: 37
authentications (OPEN SYSTEM): 940
authentications (BROADCOM)...: 221
authentications (APPLE)......: 27
deauthentications............: 7228
disassociations..............: 356
action packets...............: 76933
EAPOL packets................: 1481
EAPOL PMKIDs.................: 42
EAP packets..................: 7
WEP packets..................: 4
IPv4 packets.................: 1399
IPv6 packets.................: 146
TCP packets..................: 809
UDP packets..................: 390
ICMPv4 packets...............: 55
ICMPv6 packets...............: 39
DHCP packets.................: 19
found........................: EAP type ID
found........................: EAP-TLS Authentication
found........................: PEAP Authentication
best handshakes..............: 19 (ap-less: 0)

42 PMKID(s) written to speed-test.16800

real	0m20.918s
user	0m13.141s
sys	0m7.777s
```

So from a "crack this handshake" perspective, yeah. If you cut down the data set to only handshakes, it goes faster.
However, if you want to *decrypt* the data, you want the original unfiltered capture.

```
summary:                                        
--------
file name....................: Kismet-20180709-18-38-41-1.pcapdump
file type....................: pcap 2.4
file hardware information....: unknown
file os information..........: unknown
file application information.: unknown
network type.................: DLT_PPI (192)
endianess....................: little endian
read errors..................: yes
packets inside...............: 194554171
skipped packets..............: 0
packets with FCS.............: 192270165
WDS packets..................: 125762
beacons (with ESSID inside)..: 53887524
probe requests...............: 1168195
probe responses..............: 7596249
association requests.........: 1241
association responses........: 3321
reassociation requests.......: 97
reassociation responses......: 689
authentications (OPEN SYSTEM): 11637
authentications (SAE)........: 224
authentications (BROADCOM)...: 4027
authentications (APPLE)......: 182
deauthentications............: 279278
disassociations..............: 1798
action packets...............: 964517
EAPOL packets................: 10638
EAPOL PMKIDs.................: 145
EAP packets..................: 736
EAP START packets............: 2008
WEP packets..................: 101425
IPv4 packets.................: 24606
IPv6 packets.................: 750
TCP packets..................: 17035
UDP packets..................: 4706
ICMPv4 packets...............: 334
ICMPv6 packets...............: 223
DHCP packets.................: 220
DHCPv6 packets...............: 11
found........................: EAP type ID
found........................: MD5-Challenge
found........................: EAP-TLS Authentication
found........................: PEAP Authentication
found........................: WPS Authentication
best handshakes..............: 109 (ap-less: 0)

148 PMKID(s) written to speed-test.16800

real	5m19.675s
user	3m6.705s
sys	2m12.472s
```

```
-rw-r--r-- 1 clundquist clundquist  43G Aug  6 10:42 Kismet-20180709-18-38-41-1.pcapdump
```
Again, I'm just happy that today this file takes ~5 minutes when it took an hour yesterday :)

**Comment by ChrisLundquist** [comment]
One last thought, it is worth noting that *because* I kept the original pcaps. I was able to crack additional networks with your approach here https://hashcat.net/forum/thread-7717.html

Grabbing the PMKID from these old caps gave me `148` PMKIDs when I only had `109` handshakes, which is pretty cool!

**Comment by ChrisLundquist** [comment]
The next big win appears to be when we check the fcscrc32.

We spend about half our time there now instead of searching our data :)

```
  46.93%  hcxpcaptool      hcxpcaptool               [.] processpacket.part.29     
```        

```
       │             crc = crc32table[(crc ^buffer[p]) & 0xff] ^(crc >> 8);
  0.01 │ e0:   movzbl (%rcx),%esi
  0.01 │       add    $0x1,%rcx
 12.48 │       xor    %eax,%esi
  2.71 │       shr    $0x8,%eax
 11.16 │       movzbl %sil,%esi
 73.29 │       xor    (%rdx,%rsi,4),%eax
```
