### ISSUE TITLE
[Install] wlanhcx2cap.c:18:10: fatal error: curl/curl.h: No such file or directory

### ISSUE THREAD

**Issue by CoffeeFou** [ZerBea/hcxtools#48]
Hello, I have a little problem to install the tool on Parrot ( debian buster based)

`sudo make
cc -std=gnu99 -O3 -Wall -Wextra -o hcxpcaptool hcxpcaptool.c -lz -lcrypto 
cc -std=gnu99 -O3 -Wall -Wextra -o hcxhashcattool hcxhashcattool.c -lcrypto -lpthread  
cc -std=gnu99 -O3 -Wall -Wextra -o wlanhc2hcx wlanhc2hcx.c 
cc -std=gnu99 -O3 -Wall -Wextra -o wlanwkp2hcx wlanwkp2hcx.c 
cc -std=gnu99 -O3 -Wall -Wextra -o wlanhcxinfo wlanhcxinfo.c 
cc -std=gnu99 -O3 -Wall -Wextra -o wlanhcx2cap wlanhcx2cap.c -lpcap 
wlanhcx2cap.c:18:10: fatal error: curl/curl.h: No such file or directory
 #include <curl/curl.h>
          ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:27: build] Error 1`

Hope you can fix it soon : )

**Comment by ZerBea** [comment]
That is a missing dependency:
Please install curl and libcurl-dev

**Comment by CoffeeFou** [comment]
Oh ok, I checked for curl (v7.6) but it needed libcurl4-gnutls-dev to work.

Thank's :+1:

**Comment by CoffeeFou** [comment]
Oh ok, I checked for curl (v7.6) but it needed libcurl4-gnutls-dev to work.

Thank's :+1:
