### ISSUE TITLE
Feature request -  hcxpcaptool output to PMK : ESSID?

### ISSUE THREAD

**Issue by adrastee** [ZerBea/hcxtools#50]
Feature request?

_hcxpcaptool_ exports PMK list thanks to -P option, while _wlanpmk2hcx_ tool requires as input a combo list PMK:ESSID
`i <file>  : input combilist (pmk:essid)`

Any chance _hcxpcaptool_ could output as PMK : ESSID?

Final goal: cap -> PMK extract -> sha1 hash (mode 12000)

**Comment by ZerBea** [comment]
No. That doesn't make sense:
If we receive a PMK we do not know to which ESSID the PMK belongs.
But you can do this with simple bash scripts.
use combinator from hashcat-utils to calculate an ESSID:PMK list on -E elist -P list output of hcxpcaptool
create a seperatorfile: sep with only one ":" inside.
then run
combinator3 elist sep plist

**Comment by adrastee** [comment]
Makes sense. Thanks for the combinator3 trick :)
