### ISSUE TITLE
how fixed

### ISSUE THREAD

**Issue by Kalimon12** [ZerBea/hcxtools#54]
root@kali:~/hcxtools# make
cc -O3 -Wall -Wextra -std=gnu99  -o hcxpcaptool hcxpcaptool.c -lz -lcrypto 
cc -O3 -Wall -Wextra -std=gnu99  -o hcxhashcattool hcxhashcattool.c -lcrypto -lpthread  
cc -O3 -Wall -Wextra -std=gnu99  -o wlanhc2hcx wlanhc2hcx.c 
cc -O3 -Wall -Wextra -std=gnu99  -o wlanwkp2hcx wlanwkp2hcx.c 
cc -O3 -Wall -Wextra -std=gnu99  -o wlanhcxinfo wlanhcxinfo.c 
cc -O3 -Wall -Wextra -std=gnu99  -o wlanhcx2cap wlanhcx2cap.c -lpcap 
wlanhcx2cap.c:19:10: fatal error: curl/curl.h: No such file or directory
 #include <curl/curl.h>
          ^~~~~~~~~~~~~
compilation terminated.
Makefile:23: recipe for target 'build' failed
make: *** [build] Error 1

**Comment by strasharo** [comment]
https://github.com/ZerBea/hcxtools/issues/48

**Comment by ZerBea** [comment]
Closed, since it isn't an issue.
