### ISSUE TITLE
openssl/sha.h: No such file or directory

### ISSUE THREAD

**Issue by AissaouiD** [ZerBea/hcxtools#55]
![screenshot from 2018-08-09 10-44-55](https://user-images.githubusercontent.com/32780400/43891498-582c1204-9bc1-11e8-86bb-a64a1241f368.png)

**Comment by ojaschauhan44** [comment]
same problem for me too..? any solutions

**Comment by AissaouiD** [comment]
try this 
it worked for me
 apt-get install libssl-ocaml-dev

**Comment by Pyrra0** [comment]
save problem for me. any solution pls

**Comment by zeddyemy** [comment]
same problem here can someone please help

**Comment by zeddyemy** [comment]
> try this
> it worked for me
> apt-get install libssl-ocaml-dev

this didn't work for me

**Comment by ZerBea** [comment]
1. identify your distribution (the name of the package depends on your distribution)
2. search for the package / dev package
3. install the package / dev package using your package manager

For example Arch:
https://www.archlinux.org/packages/
usually pacman -S openssl

For example Debian:
https://wiki.debian.org/PackageManagement/Searching

For example Ubuntu:
https://askubuntu.com/questions/481/how-do-i-find-the-package-that-provides-a-file
https://packages.ubuntu.com/

For example Kali:
https://pkg.kali.org/
https://www.kali.org/tutorials/finding-packages-for-kali-linux/

Read more here:
https://stackoverflow.com/questions/3368683/how-to-compile-c-file-with-openssl-includes
https://unix.stackexchange.com/questions/87458/make-fatal-error-openssl-sha-h-no-such-file-or-directory
https://tutel.me/c/unix/questions/87458/make+fatal+error+opensslshah+no+such+file+or+directory
or here:
https://www.youtube.com/watch?v=KzSd703ZdRQ

**Comment by KaziMuktadirAhmed** [comment]
is there any solution for i386

**Comment by ZerBea** [comment]
Solution depend on your distribution.
Install openssl (and open ssl dev files) via packet manager of your distribution.
That's all.
