### ISSUE TITLE
Make ?

### ISSUE THREAD

**Issue by yildirimserkan** [ZerBea/hcxtools#56]
I tried make and make install but i got this error

cc -O3 -Wall -Wextra -std=gnu99  -o hcxpcaptool hcxpcaptool.c -lz -lcrypto 
hcxpcaptool.c:16:10: fatal error: openssl/sha.h: No such file or directory
 #include <openssl/sha.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:23: build] Error 1

**Comment by ZerBea** [comment]
Not an issue. Missing dependency:
https://github.com/ZerBea/hcxtools/issues/55
and from README.md:
* libopenssl and openssl-dev installed
* librt and librt-dev installed (should be installed by default)
* zlib and zlib-dev installed (for gzip compressed cap/pcap/pcapng files)
* libcurl and curl-dev installed (used by whoismac and wlancap2wpasec)
* libpthread and pthread-dev installed (used by hcxhashcattool)
To install requirements on Kali use the following 'apt-get install libcurl4-openssl-dev libssl-dev zlib1g-dev libpcap-dev'

**Comment by tensigh** [comment]
Yeah, I read the readme here on Github. Didn't list all of the dependent libraries. That would have helped. Having an executable that could be run would be helpful, too. 

Thanks for making open source software so appealing, strasharo! I can't imagine why Microsoft stays in business with such warm attitudes towards users! (Sorry, after 2 hours of not being able to install and run this I'm a little cranky)

**Comment by ZerBea** [comment]
For sure, it lists all dependencies! libpcap-dev is for pcap.h

**Comment by tensigh** [comment]
You're right, my bad. My apologies.

**Comment by ZerBea** [comment]
No problem. 
I'll drop that dependency as soon as I have some more time.

**Comment by nubbix** [comment]
Cannot install dependencies as it cannot be found. Using latest version of Kali Linux

Ref. 

> root@kali:~# apt install librt
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> E: Unable to locate package librt
> root@kali:~# apt install zlib
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> E: Unable to locate package zlib
> root@kali:~# apt install libcurl
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> E: Unable to locate package libcurl
> root@kali:~# apt-get install librt
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> E: Unable to locate package librt


Tried everything i can think of, but cannot seem to run make on the package

```
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/hcxpcaptool.d -o hcxpcaptool hcxpcaptool.c -lz -lcrypto 
In file included from hcxpcaptool.c:35:
include/gzops.c:1:10: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
          ^~~~~~~~
compilation terminated.
make: *** [Makefile:81: hcxpcaptool] Error 1
```

**Comment by nubbix** [comment]
Never mind, fixed it by installing the missing zlib and libcurl4-dev

**Comment by qkum** [comment]
I get this error when installing hcxtools on my raspberry pi - running Kali Linux. Even after installing the Full version ( 15 gb ). Need hcxtools for running wifite. Great thread this is. Second time it saves me. 

Great work ZerBa, you are your weight wort in gold for the pentesters of the world! Keep up the good work :)

**Comment by ZerBea** [comment]
Well, the Raspberry Pi is really a great machine:

![IMG_20190413_122226](https://user-images.githubusercontent.com/17742243/58640205-de9f6880-82f8-11e9-97e7-97efa2a30611.jpg)

**Comment by ZerBea** [comment]
![IMG_20190502_104154](https://user-images.githubusercontent.com/17742243/58640335-21614080-82f9-11e9-804d-0ae232d69c70.jpg)

Raspberry Pi Zero WH (hardware modified) + EDIMAX EW-7711UAN
(internal WiFi disabled)

**Comment by ZerBea** [comment]
![bigger](https://user-images.githubusercontent.com/17742243/58641682-f0363f80-82fb-11e9-83b4-d6ef9ae8105a.jpg)

Raspberry Pi A+ (hardware mdoified), TENDA W311U+, FANTEC RBP-132H Powerbank, LOGILINK WL0095 panel

**Comment by ZerBea** [comment]
![heavyduty](https://user-images.githubusercontent.com/17742243/58641763-1a87fd00-82fc-11e9-956f-8ceefd74063b.jpg)

Raspberry Pi A+ (hardware mdoified), TENDA W311U+, FANTEC RBP-132H Powerbank, LOGILINK WL0097 dish

**Comment by ZerBea** [comment]
and always keep in mind:
the antenna is the best high frequency amplifier!!!

**Comment by gh0stshell** [comment]
On Raspberry Pi Zero WH running kali 2019.3, got the error as I thought it would be installed by default so I popped open the readme and  just ran apt-get install libcurl4-openssl-dev libssl-dev zlib1g-dev libpcap-dev from the readme and no more fatal error: openssl/sha.h: No such file or directory, i did issue a make clean before running again.
