### ISSUE TITLE
"make" fails - pcap.h: No such file or directory

### ISSUE THREAD

**Issue by tensigh** [ZerBea/hcxtools#61]
I can't seem to run make. 

wlanhcx2cap.c:12:18: fatal error: pcap.h: No such file or directory
 #include <pcap.h>
                  ^
compilation terminated.
Makefile:79: recipe for target 'wlanhcx2cap' failed
make: *** [wlanhcx2cap] Error 1

pcap.h doesn't appear in the directory hcxtools, where can I find it?

**Comment by ZerBea** [comment]
Not a hcxtools issue.
You have to ask the developer of your distribution. If you're running KALI, please read this:
https://unix.stackexchange.com/questions/399626/why-is-kali-linux-so-hard-to-set-up-why-wont-people-help-me

**Comment by tensigh** [comment]
Thanks. I'm not running Kali but I'll see if there's something useful there.

**Comment by JamalMuradov** [comment]
> I can't seem to run make.
> 
> wlanhcx2cap.c:12:18: fatal error: pcap.h: No such file or directory
> #include <pcap.h>
> ^
> compilation terminated.
> Makefile:79: recipe for target 'wlanhcx2cap' failed
> make: *** [wlanhcx2cap] Error 1
> 
> pcap.h doesn't appear in the directory hcxtools, where can I find it?

`apt-get install libpcap0.8-dev` worked for me

**Comment by ZerBea** [comment]
@JamalMuradov that will not work, any longer because I remove wlanhcx2cap.
Also I removed libpcap dependency.
Read more here:
https://github.com/ZerBea/hcxtools/issues/81#issuecomment-461116551
