### ISSUE TITLE
Fatal error while trying to compile

### ISSUE THREAD

**Issue by Insomnia024** [ZerBea/hcxtools#63]
root@kali:~/hcxtools# make
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/hcxpcaptool.d -o hcxpcaptool hcxpcaptool.c -lz -lcrypto 
hcxpcaptool.c:16:10: fatal error: openssl/sha.h: No such file or directory
 #include <openssl/sha.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
Makefile:79: recipe for target 'hcxpcaptool' failed
make: *** [hcxpcaptool] Error 1

**Comment by strasharo** [comment]
https://github.com/ZerBea/hcxtools/issues/57
https://github.com/ZerBea/hcxtools/issues/56
https://github.com/ZerBea/hcxtools/issues/55

**Comment by ZerBea** [comment]
Not hcxtools issue. Missing dependencies using KALI. 
There are some nice how-to's for KALI on youtube.
Also README.md gives informations about the dependencies.

**Comment by dilshah1988** [comment]
simple open your terminal and write this commond. 

"sudo` apt install libcurl4-openssl-dev libssl-dev zlib1g-dev libpcap-dev"
And Hit Enter then Make

**Comment by ZerBea** [comment]
libpcap is no longer needed. I dropped that dependency:

02.02.2019
release hcxtools v 5.1.1
removed....: wlanhcx2psk
replaced by: hcxpsktool

removed....: wlanhcx2cap
replaced by: hcxhash2cap
no more libcap dependency!

**Comment by onno45** [comment]
thankxxx
