### ISSUE TITLE
Issue with Curl.h 

### ISSUE THREAD

**Issue by mblackbourne** [ZerBea/hcxtools#67]
I have curl installed on my machine and I am receiving this error:

`cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/wlanhcx2cap.d -o wlanhcx2cap wlanhcx2cap.c -lpcap 
wlanhcx2cap.c:19:10: fatal error: curl/curl.h: No such file or directory
 #include <curl/curl.h>
          ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:79: wlanhcx2cap] Error 1
`

Am I missing something?

**Comment by strasharo** [comment]
Install the curl devel package on your distribution. On Kali it would be libcurl4-openssl-dev.

**Comment by mblackbourne** [comment]
Thank you that worked! Onward and upward!

**Comment by hktalent** [comment]
apt install  libcurl4-openssl-dev

**Comment by Markreturn123** [comment]
it worked perfectly
