### ISSUE TITLE
When you run the program wifite, I wrote an error that I need to download additional packages. Kali linux

### ISSUE THREAD

**Issue by Kasperait** [ZerBea/hcxtools#68]
I downloaded the package, but the installation I write error 1. What should I do in such situations ? I will give a link to the video : https://youtu.be/rQ78sVEFCtY

**Comment by ZerBea** [comment]
Issue isn't related to hcxtools. That is a missing dependency. You must satisfy the dependencies:
From README.md:
To install requirements on Kali use the following 'apt-get install libcurl4-openssl-dev libssl-dev zlib1g-dev libpcap-dev'
