### ISSUE TITLE
hcxpcaptool -z works | -j doesn't work

### ISSUE THREAD

**Issue by cirolaferrara** [ZerBea/hcxtools#91]
```
$ hcxpcaptool -z output.16800 input.pcapng
reading from 24032019.pcapng

summary:
--------
[...]
1 PMKID(s) written to output.16800
```
It works.
```
$ hcxpcaptool -j output.john input.pcapng
reading from 24032019.pcapng

summary:
--------
[...]
```
I haven't output.john. Same with -J

I'am on raspberry (1st model) hcxpcaptool 5.1.4 compiled from git

**Comment by ZerBea** [comment]
Options -j and -J convert EAPOL(!) to john
-j <file> : output john WPAPSK-PMK file (john wpapsk-opencl)
-J <file> : output raw john WPAPSK-PMK file (john wpapsk-opencl)
For hashcat this is done using the options
-o <file> : output hccapx file (hashcat -m 2500/2501)
-O <file> : output raw hccapx file (hashcat -m 2500/2501)

But both, hashcat and john use the same format for PMKID - so we have only option -z here:
$ john -w:wordlist  --format=wpapsk-opencl hash.16800
$ hashcat -m 16800 hash.16800 wordlist
will work on the same hashfile!

I added a notice to --help to make that clear.
-z <file> : output PMKID file (hashcat hashmode -m 16800 and john)

Please test and close this issue if it works for you.

**Comment by cirolaferrara** [comment]
Thanks. It works
$ john --format=wpapsk hash.16800 --wordlist=mywordlist
