### ISSUE TITLE
hcxpcaptool outfile issue?

### ISSUE THREAD

**Issue by awhitehatter** [ZerBea/hcxtools#92]
Hello, 

hcxpcaptool seems to read PMKIDs in my pcap, but doesn't write the outfile. Am I missing something?

```
me@HOST:~$ sudo hcxpcaptool -V -z handshakes.pmkid *.pcap

reading from handshakes.pcap
                                                
summary:                                        
--------
file name....................: handshakes.pcap
file type....................: pcap 2.4
file hardware information....: unknown
file os information..........: unknown
file application information.: unknown
network type.................: DLT_IEEE802_11_RADIO (127)
endianness...................: little endian
read errors..................: flawless
packets inside...............: 11
skipped packets..............: 0
packets with GPS data........: 0
packets with FCS.............: 11
EAPOL packets (total)........: 11
EAPOL packets (WPA2).........: 11
EAPOL PMKIDs (total).........: 11
EAPOL PMKIDs (WPA2)..........: 11
best PMKIDs..................: 2
```
Then there is no outfile, I've tried messing with the different outputs, nothing each time.

**Comment by awhitehatter** [comment]
Nevermind, grabbed a test pcap from Aircrack, no problems with that. Something is up with my pcap file. Thanks!

**Comment by ZerBea** [comment]
ok

**Comment by l0rda** [comment]
Same issue with pcap file from bettercap.

**Comment by ZerBea** [comment]
Please attach pcap file (compressed as zip - git will accept this).

**Comment by ZerBea** [comment]
To use hashcat mode 16800 you need an ESSID and a PMKID!

If you take a look at https://github.com/ZerBea/hcxtools/issues/92#issue-444146245
you see that we have 2 good PMKIDs, but no(!) ESSID.
hashcat can't run this hash, so there is no need for hcxpcaptool to convert it.
BTW:
hcxdumptool will do that during capturing process. If you run other tools to capture traffic, make sure that they really capture all(!) required packets to recover the PSK. Not all tools will do this!

If you really need to "clean/convert" a cap/pcap/pcapng file,  run
$ tshark -r "inputfile" -R "(wlan.fc.type_subtype == 0x00 || wlan.fc.type_subtype == 0x02 || wlan.fc.type_subtype == 0x04 || wlan.fc.type_subtype == 0x05 || wlan.fc.type_subtype == 0x08 || eapol)" -2 -F pcapng -w "outputfile"

or, if you prefer ancient formats:
$ tshark -r "inputfile" -R "(wlan.fc.type_subtype == 0x00 || wlan.fc.type_subtype == 0x02 || wlan.fc.type_subtype == 0x04 || wlan.fc.type_subtype == 0x05 || wlan.fc.type_subtype == 0x08 || eapol)" -2 -F pcap -w "outputfile

**Comment by ZerBea** [comment]
Nevertheless: the PMKIDs are good and we can convert them to run hashmode 16801 on them.
Added 2 new options to hcxpcaptool to convert raw PMKIDs
-K <file> : output raw PMKID file (hashcat hashmode -m 16801 new format)
-Z <file> : output raw PMKID file (hashcat hashmode -m 16801 old format and john)

use this option(s) if you would like to verify a PMKID and you don't have an ESSID
$ hcxpcaptool -K raw.16801 test.pcapng
reading from test.pcapng
summary:                                        
file name....................: test.pcapng
file type....................: pcapng 1.0
file hardware information....: armv6l
file os information..........: Linux 4.19.42-1-ARCH
file application information.: hcxdumptool 5.1.4
network type.................: DLT_IEEE802_11_RADIO (127)
endianness...................: little endian
read errors..................: flawless
packets inside...............: 1
skipped packets..............: 0
packets with GPS data........: 0
packets with FCS.............: 0
EAPOL packets (total)........: 1
EAPOL packets (WPA2).........: 1
EAPOL PMKIDs (total).........: 1
EAPOL PMKIDs (WPA2)..........: 1
best PMKIDs..................: 1
1 raw PMKID(s) written to raw.16801

keep in mind:
hashcat hash modes 16801 and 2501 are verification modes (verify EAPOL and/or PMKID by existing PMK).

**Comment by l0rda** [comment]
> Please attach pcap file (compressed as zip - git will accept this).

Unfortunately i cannot attach file with sensitive data, but you can try with **bettercap**.

Thanks for your answer about "ESSID and a PMKID". "-Z" option works.

**Comment by ZerBea** [comment]
Unfortunately I don't use bettercap (depend on deprecated tools: https://dougvitale.wordpress.com/2011/12/21/deprecated-linux-networking-commands-and-their-replacements/)

But output of hcxpcaptool -V  doesn't contain sensitive data, so you can add them here:
$ hcxpcaptool -V your_pcap_file

For example a typical hcxdumptool pcapng file (captured by https://github.com/ZerBea/hcxdumptool/wiki/Penetration-testing-system-2)

$ hcxpcaptool -V capture.pcapng.gz
decompressing capture.pcapng.gz to /tmp/capture.pcapng.gz.tmp
reading fromcapture.pcapng.gz.tmp
summary:                                        
file name....................: capture.pcapng.gz.tmp
file type....................: pcapng 1.0
file hardware information....: armv6l
file os information..........: Linux 4.19.37-2-ARCH
file application information.: hcxdumptool 5.1.4
network type.................: DLT_IEEE802_11_RADIO (127)
endianness...................: little endian
read errors..................: flawless
packets inside...............: 19017
skipped packets..............: 0
packets with GPS data........: 0
packets with FCS.............: 0
WDS packets..................: 116
beacons (with ESSID inside)..: 5258
beacons (with MESH-ID inside): 17
probe requests...............: 1097
probe responses..............: 1287
association requests.........: 662
association responses........: 604
reassociation requests.......: 183
reassociation responses......: 167
authentications (OPEN SYSTEM): 2499
authentications (BROADCOM)...: 2369
authentications (SONOS)......: 77
authentications (APPLE)......: 30
EAPOL packets (total)........: 6142
EAPOL packets (WPA1).........: 33
EAPOL packets (WPA2).........: 6109
EAPOL PMKIDs (total).........: 2552
EAPOL PMKIDs (WPA1)..........: 17
EAPOL PMKIDs (WPA2)..........: 2535
EAP packets..................: 726
EAP START packets............: 1
found........................: EAP type ID
found........................: PEAP Authentication
best handshakes..............: 448 (ap-less: 297)
best PMKIDs..................: 740
