### ISSUE TITLE
eror

### ISSUE THREAD

**Issue by celik869013** [ZerBea/hcxtools#93]
![Ekran Alıntısıe](https://user-images.githubusercontent.com/35223115/57975553-e34c4e80-79d3-11e9-898b-d397dcfd72e0.PNG)

**Comment by strasharo** [comment]
https://github.com/ZerBea/hcxtools/issues/70
https://github.com/ZerBea/hcxtools/issues/63
https://github.com/ZerBea/hcxtools/issues/57
https://github.com/ZerBea/hcxtools/issues/56
https://github.com/ZerBea/hcxtools/issues/55

**Comment by ZerBea** [comment]
Issue is related to KALI and not to hcxtools.
https://unix.stackexchange.com/questions/399626/why-is-kali-linux-so-hard-to-set-up-why-wont-people-help-me
